### PR TITLE
Deprecate unused, untested, and obsolete code

### LINKED ISSUE #1321: MaskellSolidSolnPhase has numerous consistency issues
**Problem description**

There are numerous thermodynamic consistency issues with `MaskellSolidSolnPhase`. In addition, it does not even implement many methods that are implemented in most other models that would be needed to assess thermodynamic consistency, such as `cp_mole`, `cv_mole`, `partial_molar_enthalpies`, etc.

In this case, I think the state of this model is poor enough that we should consider simply deprecating it and removing it.

**Steps to reproduce**

```python
>>> p = ct.Solution('test/data/thermo-models.yaml', 'MaskellSolidSoln')
>>> p.TPX = 300, ct.one_atm, (0.3, 0.7)

# Under all conditions, this identity is not satisfied
>>> p.gibbs_mole, sum(p.X * p.chemical_potentials)
(-3434437.826907263, 2009969.7439611293)

# At P != 1 atm, most of the "standard state" properties are inconsistent.
>>> p.TPX = 300, 10*ct.one_atm, (0.3, 0.7)
>>> RT = ct.gas_constant * p.T
>>> p.standard_enthalpies_RT * RT, p.standard_int_energies_RT * RT + p.P * p.volume_mole
(array([ 4559.625, 10119.25 ]), array([354.6375, 848.0125]))

# For limiting compositions, many properties are non-finite:
>>> p.TPX = 300, 10*ct.one_atm, (1.0, 0.0)
>>> p.activity_coefficients
array([inf, nan])

>>> p.gibbs_mole, p.entropy_mole
(nan, nan)
```

**System information**

- Cantera version: 2.6.0 or `main` at 1ab81ace5

**Additional context**

This was discovered as part of https://github.com/Cantera/cantera/pull/1299, which implements https://github.com/Cantera/enhancements/issues/114.

### LINKED ISSUE #1322: IonsFromNeutralPhase has inconsistent implementations of some thermo properties
**Problem description**

The `IonsFromNeutralPhase` class (YAML phase name `ions-from-neutral-molecule`) has several thermodynamic inconsistencies, mostly relating to the Gibbs free energy.

**Steps to reproduce**

```python
>>> p = ct.Solution('test/data/thermo-models.yaml', 'ions-from-neutral-molecule')
>>> p.TPX = 500, 2e5, (0.1, 0.1)

# These pairs should be equal
>>> p.g, p.h - p.T*p.s
(-6295054.121796026, -16996646.128849268)

>>> p.volume_mole, sum(p.X * p.partial_molar_volumes)
(0.018785000000000003, 0.05071950000000001)

>>> p.chemical_potentials
array([-4.66404010e+08, -2.88157316e+06])
# should be equal to the chemical potentials
>>> p.partial_molar_enthalpies - p.T * p.partial_molar_entropies
array([-5.60261127e+08, -7.06809948e+08])

>>> p.activities
array([0.5, 0.5])
# should be equal to the activities
>>> np.exp(p.chemical_potentials / (p.T * ct.gas_constant) - p.standard_gibbs_RT)
array([3.19127299e+09, 1.72355301e+73])
```

**System information**

- Cantera version: 2.6.0 or `main` at 1ab81ace5

**Additional context**

This was discovered as part of https://github.com/Cantera/cantera/pull/1299, which implements https://github.com/Cantera/enhancements/issues/114.

### LINKED ISSUE #1425: Liquid water transport data via Matlab interface
**Problem description**

Transport data for liquid water can be obtained using the Python interface (after [this related issue](https://github.com/Cantera/cantera/issues/289) was solved), but not via Matlab.

**Steps to reproduce**

While this works

```python
import cantera as ct

w = ct.Water()

w.viscosity
```

the equivalent commands in Matlab fail:

```matlab
w = Water()

viscosity(w)

Error using ctmethods

***********************************************************************
NotImplementedError thrown by Transport::viscosity:
Not implemented.
***********************************************************************
```

Is this just an oversight or are there technical reasons for this?

**System information**

- Cantera version: 2.5.1
- OS: CentOS7
- Python 3.10, Matlab R2019a

### PR DESCRIPTION
**Pull request by speth**
The goal of this PR is to put a dent in the amount of unused or unusable code we're dragging around. The specific items picked out here is based partly on looking through coverage reports, and partly on various warts / oddities that I had noticed while working on other things and thought they would be better handled in a PR for this specific purpose.

**Changes proposed in this pull request**

- Deprecate class `IonsFromNeutralVPSSTP` and class `PDSS_IonsFromNeutral`, based on its history in #267 and various errors documented in #1322
- Deprecate class `MaskellSolidSolnPhase`, based on errors documented in #1321 and a lack of meaningful examples
- Standardize on use of canonical YAML format names for thermo / kinetics / transport models, and deprecate the XML-era versions
- Deprecate various unused methods on the `Phase`, `ThermoPhase`, `Kinetics`, and `Transport` classes
- Deprecate some unused methods of class `PDSS` and its derivatives
- Fix an issue building Sphinx docs on macOS due to `DYLD_LIBRARY_PATH` not getting passed through

**If applicable, fill in the issue number this pull request is fixing**

- Closes #1321 
- Closes #1322 
- Fixes #1425 (somewhat incidentally)

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

File: include/cantera/kinetics/Kinetics.h [hunk 1]
```diff
@@ -128,6 +128,8 @@ class Kinetics
     //! Identifies the Kinetics manager type.
     //! Each class derived from Kinetics should override this method to return
     //! a meaningful identifier.
+    //! @since  Starting in Cantera 3.0, the name returned by this method corresponds
+    //!     to the canonical name used in the YAML input format.
     virtual std::string kineticsType() const {
         return "None";
```
Comment (ischoegl) [inline include/cantera/kinetics/Kinetics.h]: Should `None` be lower case to be consistent? (It’s not a proper name)

File: include/cantera/transport/Transport.h [hunk 2]
```diff
@@ -146,9 +146,12 @@ class Transport
      * @param thermo   Pointer to the ThermoPhase class representing this phase.
      * @param ndim     Dimension of the flux vector used in the calculation.
      *
+     * @deprecated The `thermo` and `ndim` parameters will be removed after Cantera 3.0.
+     *     The ThermoPhase object should be specifed when calling the `init` method.
+     *
      * @see TransportFactory
      */
-    Transport(ThermoPhase* thermo=0, size_t ndim = 1);
+    Transport(ThermoPhase* thermo = 0, size_t ndim = npos);
```
Comment (ischoegl) [inline include/cantera/transport/Transport.h]: I think we usually skip whitespace for defaults?

File: include/cantera/transport/Transport.h [hunk 3]
```diff
@@ -158,7 +161,8 @@ class Transport
 
     //! Identifies the model represented by this Transport object. Each derived class
     //! should override this method to return a meaningful identifier.
-    //! @since  New in Cantera 3.0.
+    //! @since  New in Cantera 3.0. The name returned by this method corresponds
+    //!     to the canonical name used in the YAML input format.
     virtual std::string transportModel() const {
         return "None";
```
Comment (ischoegl) [inline include/cantera/transport/Transport.h]: Same as above.

File: include/cantera/transport/Transport.h [hunk 4]
```diff
@@ -781,19 +792,22 @@ class Transport
...
 
     //! Number of dimensions used in flux expressions
+    //! @deprecated To be removed after Cantera 3.0
     size_t m_nDim;
 
     //! Velocity basis from which diffusion velocities are computed.
     //! Defaults to the mass averaged basis = -2
     int m_velocityBasis = VB_MASSAVG;
 
     //! reference to Solution
```
Comment (ischoegl) [inline include/cantera/transport/Transport.h:809]: This isn’t currently used, but could be useful once `Solution` is used consistently. It’s still ok to deprecate though.

File: src/thermo/ThermoFactory.cpp [hunk 5]
```diff
@@ -53,56 +53,56 @@ ThermoFactory::ThermoFactory()
     addAlias("none", "ThermoPhase");
     addAlias("none", "None");
```
Comment (ischoegl) [inline src/thermo/ThermoFactory.cpp]: For context, the default is lowercase `none` here.

above, it may be worth deprecating `ThermoPhase` as well.

**Review by ischoegl — CHANGES_REQUESTED** [review]
Thanks for going over the API … I just have a couple of minor comments.

File: include/cantera/thermo/HMWSoln.h [hunk 6]
```diff
@@ -797,7 +797,7 @@ class HMWSoln : public MolalityVPSSTP
     //! @{
 
     virtual std::string type() const {
-        return "HMWSoln";
+        return "HMW-electrolyte";
```
Comment (ischoegl) [inline include/cantera/thermo/HMWSoln.h:800]: Is there a more descriptive name than `HMW`? While there is copious documentation for the class, the `HMW` doesn't appear to be intuitive.

Comment (speth) [reply include/cantera/thermo/HMWSoln.h:800]: It's the last initials of the three authors who came up with the model. Other sources refer to this model in a similar way as well (e.g. https://academy.gwb.com/high_salinity.php), and I don't know of a more descriptive alternative. We do list the expansion of the acronym in the [glossary](https://cantera.org/documentation/glossary.html#glossary), though that still doesn't provide much information.

File: include/cantera/kinetics/Kinetics.h (hunk 1 above)
Comment (speth) [reply include/cantera/kinetics/Kinetics.h]: Yes, it probably should be. I hesitated only because that special case gets used and checked a fair number of times internally.

Comment (ischoegl) [reply include/cantera/kinetics/Kinetics.h]: I agree that it’s a little more intrusive, but I think it’s the right thing to do.

**Review by ischoegl — APPROVED** [review]
Thank you, this all looks good to me!
