### PR TITLE
Matlab-to-Clib Interface Overhaul

### LINKED ISSUE #1852: MATLAB Interface Is Incompatible with the Latest Version of MATLAB
**Problem description**

The latest version of MATLAB (R2024b) comes with Intel MKL as the default library for BLAS and LAPACK. This version of MKL is built with ILP64 where a 64-bit `int` type is used for all integers in order to support very large array sizes (>2^31-1). The default OpenBLAS package that comes with Cantera uses LP64 where standard integers are 32-bit and the `long` type is required for 64-bit integers. This causes an incompatibility issue when data in an array is passed back and forth between MATLAB and OpenBLAS. In some cases this will just return an incorrect type error but in the worst case scenario will cause a buffer overflow and instantly crashes MATLAB. 

A partial workaround exists to resolve this problem, as mentioned in [this thread](https://www.mathworks.com/matlabcentral/answers/1982374-custom-c-library-gives-error-intel-mkl-error-parameter-8-was-incorrect-on-entry-to-dgemm-when-us). We can bypass ILP64 MKL by setting the environment variable `LD_PRELOAD` and force MATLAB to use the LP64 OpenBLAS library in the Cantera environment. This will correctly set the types of integers and Cantera will successfully solve any linear algebra problems. However, this workaround is unstable and will cause crashes when the `plot` function is invoked, for example to plot to concentration of species over time. 

**Steps to reproduce**

1. In MATLAB, run `ctLoad`;
2. Run example `equil.m`;
3. Exit MATLAB and set `LD_PRELOAD` to the location of the OpenBLAS library in your Cantera environment;
4. Repeat 1) and 2).

**Behavior**

The `gas` object will fail to equilibrate, this error appears in the MATLAB terminal:
```
Error using ctFunc (line 11)

*******************************************************************************
CanteraError thrown by MultiPhase::equilibrate_MultiPhaseEquil:
No convergence for T
*******************************************************************************

Error in ThermoPhase/equilibrate (line 493)
            ctFunc('thermo_equilibrate', tp.tpID, xy, solver, rtol, ...
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in equil (line 39)
        gas.equilibrate('HP');
        ^^^^^^^^^^^^^^^^^^^^^
```
while this error will appear in the linux terminal:
```
Intel oneMKL ERROR: Parameter 6 was incorrect on entry to DGEMV
```
Parameter 6 of DGEMV is the leading dimension of a matrix, which in MKL ILP64 is a 64-bit `int` type but in OpenBLAS is a 64-bit `long`. 

After setting the `LD_PRELOAD` variable to the correct OpenBLAS location. This example will successfully run until the `plot` function is invoked to plot the equivalence ratio vs. temperature. MATLAB instantly crashes and throws either a `free(): invalid pointer` error or `munmap_chunk()` error, both of which indicate a memory corruption has occured. It is unknown whether other built-in MATLAB functions will cause these crashes, but simple manipulations on the data being plotted did not return any errors or cause crashes. A crash dump info is included below:

[matlab_crash_dump_510456-1.txt](https://github.com/user-attachments/files/18761766/matlab_crash_dump_510456-1.txt)

**System information**

- Cantera version: 3.2.0
- OS: Ubuntu 22.04.5 LTS
- Python/MATLAB/other software versions: MATLAB R2024b

**Additional context**

Older versions of MATLAB are untested.

### PR DESCRIPTION
**Pull request by ssun30**
**Changes proposed in this pull request**

- Replace the MATLAB-to-C interface with a more modern MATLAB-to-C++ interface that is more code generation-friendly and has safer memory management.
- Reworked classes to adopt the new interface.
- Integrate the new process of building the new interface into Github Actions. 

**If applicable, fill in the issue number this pull request is fixing**

Resolves #1852. The new interface runs "out of process", meaning memory management is separated on the MATLAB and C++ side. This prevents the incompatible data types between the ILP64 type used by MATLAB's MKL library and the LP64 type Cantera's OpenBLAS library. This also prevents crashes caused by memory leaks which the previous interface is susceptible to. 

This interface requires a MATLAB release newer than R2020b. 

**If applicable, provide an example illustrating new features this pull request is introducing**

The new interface doesn't affect how the experimental MATLAB toolbox is used on the user side, since all the changes are done on the data passing between MATLAB and Cantera C++ core. 

**Checklist**

- [ ] The pull request includes a clear description of this code change
- [ ] Commit messages have short titles and reference relevant issues
- [ ] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [ ] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [ ] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
Thanks for looking into this, @ssun30. Overall, I believe introducing new 4,000+ line `definectMatlab.m` and a 22,000+ line `ctMatlabData.xml` are quite problemantic from a maintenance perspective. Likely, these can be autogenerated (if they haven't been already), and I am :-1: on adopting them in their hard-coded form.

Regarding a new "C++ interface" it does look like a misnomer to me, as things are still routed through Clib, correct? As I have pointed out elsewhere, the experimental CLib version will provide better control over type conversions, and could potentially avoid the additional interface layer this PR is introducing.

That said, I'm not opposed to the solution per se, but the implementation is problematic.

**Comment by ssun30** [comment]
> Thanks for looking into this, @ssun30. Overall, I believe introducing new 4,000+ line `definectMatlab.m` and a 22,000+ line `ctMatlabData.xml` are quite problemantic from a maintenance perspective. Likely, these can be autogenerated (if they haven't been already), and I am 👎 on adopting them in their hard-coded form.
> 
> Regarding a new "C++ interface" it does look like a misnomer to me, as things are still routed through Clib, correct? As I have pointed out elsewhere, the experimental CLib version will provide better control over type conversions, and could potentially avoid the additional interface layer this PR is introducing.
> 
> That said, I'm not opposed to the solution per se, but the implementation is problematic.

Yes, the goal is for the library definitions to be auto-generated (in fact they are, mostly). The library definition files are now included just for testing the CI. The main problem so far is some of the auto-generated definitions are missing some `<MLTYPE>`, `<DIRECTION>`, and `<SIZE>` arguments that for now are filled in manually. As a proof of concept I used MATLAB's default [clibPublishInterfaceWorkflow](https://www.mathworks.com/help/matlab/ref/clibpublishinterfaceworkflow.html) which is a generic workflow. But for our own interface I will use a custom version of this workflow to build the interface. I already have a few MATLAB scripts in the works to do the automation but still requires some polishing to truly remove manual modifications. 

Apart from better type conversion, this new interface has several other advantages compared to the `loadlibrary` approach:

- Out-of-process execution: the memory spaces on either side are isolated. The current 'experimental' interface is susceptible to memory leaks and requires fail-safes to clear temporary pointers and call class destructors. This can become a problem if the user lacks knowledge of how to safely manage memory. Running the Cantera library out of process ensures MATLAB would not crash if the library crashes. 
- Auto doc gen: this new approach of generating the library definitions automatically generates documentations from the header files, we can then have a script to pull the docstrings from the library definitions into the MATLAB wrapper. I think this works well with the experimental Clib which will be fully documented with sourcegen. 
- Long term support (hopefully): MathWorks is (again) no longer maintaining the MATLAB-to-C interface we are using right now and only this new one is actively developed and maintained. 

Eventually my vision is for the wrapper layer (at least most parts of it) to also be automatically generated from the library definitions. The manually coded part would be a mapping between the MATLAB methods with their clib counterparts, and maybe some constructors which for now have a lot of manually coded conditionals.

**Comment by ischoegl** [comment]
@ssun30 … thank you for the comment but I am not sufficiently familiar with the approach. Overall, the final solution needs to be simple as anything else is unmaintainable. The team of maintainers is extremely small so we need to avoid anything that could become an unreasonable burden.

**Comment by ssun30** [comment]
> @ssun30 … thank you for the comment but I am not sufficiently familiar with the approach. Overall, the final solution needs to be simple as anything else is unmaintainable. The team of maintainers is extremely small so we need to avoid anything that could become an unreasonable burden.

@ischoegl I just added the scripts to automatically generate the interface. I don't think it's adding anything to complicate the maintainability. I think it's mostly in a "leave and forget" state where any future changes to the clib should automatically apply to the clib interface. 

I will also roll back some unnecessary changes made to the wrapper functions later.

**Comment by ischoegl** [comment]
Thank you @ssun30 for removing the unnecessary files (they should also be removed from the git history by squashing commits).

Overall, I have the sneaking suspicion that this additional layer does something similar to what Clib already does: separate memory. CLib wraps all C++ internals and makes them safe to handle in a C-style interface. If the outcome of this PR is that we have two (or more) memory copies in each direction, then it is likely not an efficient solution. To use your terminology: Clib handles memory from C++ (and delivers copies of C++ variables etc. at the Clib API), and the MATLAB wrapper then does the same once more before it is accessible by MATLAB? It seems to be both inefficient and overly complicated.

**Comment by ischoegl** [comment]
@ssun30 ... I wanted to follow up once more as there still is a lack of clarity to me. From where I stand, the approach for the MATLAB toolbox prior to this PR was as follows:

1. C++ code base (class based)
1. CLib (to be replaced by auto-generated 'experimental' CLib outside of this effort) wraps classes into C-style functions
1. MATLAB interface; hand-coded; calls into CLib via `calllib`; mimics classes available in Python interface

If I understand correctly, the direction of this PR would introduce an additional layer:

1. C++ ... see above
1. CLib ... see above
1. Autogenerated MATLAB layer (via `ctBuildInterface`)
1. Actual MATLAB Cantera toolbox; hand-coded; calls into wrapper via `clib.ctMatlab.(funcName)`; mimics classes available in Python interface.

Please let me know if I understand this correctly.

**Comment by bryanwweber** [comment]
One other clarification from me, when and by whom is the `ctBuildInterface` function called?

**Comment by ssun30** [comment]
> @ssun30 ... I wanted to follow up once more as there still is a lack of clarity to me. From where I stand, the approach for the MATLAB toolbox prior to this PR was as follows:
> 
> 1. C++ code base (class based)
> 2. CLib (to be replaced by auto-generated 'experimental' CLib outside of this effort) wraps classes into C-style functions
> 3. MATLAB interface; hand-coded; calls into CLib via `calllib`; mimics classes available in Python interface
> 
> If I understand correctly, the direction of this PR would introduce an additional layer:
> 
> 1. C++ ... see above
> 2. CLib ... see above
> 3. Autogenerated MATLAB layer (via `ctBuildInterface`)
> 4. Actual MATLAB Cantera toolbox; hand-coded; calls into wrapper via `clib.ctMatlab.(funcName)`; mimics classes available in Python interface.
> 
> Please let me know if I understand this correctly.

Hi @ischoegl , yes this is the intention. @bryanwweber The `ctBuildInterface` function will be used by 1) the CI workflow 2) the SCONs script when user installs the interface (not implemented yet) and 3) the MLTBX's setup script as an alternative way for the user to install the interface.

**Comment by ischoegl** [comment]
@ssun30 / @rwest  ... I created some documentation for Cantera's [automated code generation approach](https://cantera.org/dev/develop/sourcegen.html) as well as for the new [CLib API](https://cantera.org/dev/develop/clib-extensions.html), which was just merged into the development version. There's also rudimentary documentation for the [.NET API](https://cantera.org/dev/develop/dotnet-extensions.html), which combines auto-generated code with a hand-coded API. We're already using jinja templates elsewhere, and it would be easy to use for the MATLAB API.

_PS: Fwiw, I also added a stub for the [MATLAB Toolbox Reference](https://cantera.org/dev/matlab/index.html)_

**Review by ischoegl — COMMENTED** [review]
Looking at this PR again, I still don't see a need for introducing an extra layer, as this treats CLib's C code as if it were C++. From this perspective, isn't this redundant? Fwiw, this goes back to a comment from a couple of months ago, see https://github.com/Cantera/cantera/pull/1868#issuecomment-2792657958

**Comment by rwest** [comment]
We had a long and I think helpful meeting at MathWorks last week, and have some thoughts on this. There are pros and cons to the many options. One concern (if I got this correct) is the callib method is not going to see any further fixes from their end.  (And currently segfaults?).  Whether there's a way to get direct to the Cantera C++ without the C layer (reducing the number of layers) I can't recall and/or lost track. The saga continues....

**Comment by ischoegl** [comment]
> We had a long and I think helpful meeting at MathWorks last week, and have some thoughts on this. There are pros and cons to the many options. One concern (if I got this correct) is the callib method is not going to see any further fixes from their end. (And currently segfaults?). Whether there's a way to get direct to the Cantera C++ without the C layer (reducing the number of layers) I can't recall and/or lost track. The saga continues....

@rwest ... thanks for chiming in! I wasn't aware that MathWorks was thinking of discontinuing low-level `calllib` support, but there still are [limitations to their C++ support](https://www.mathworks.com/help/matlab/matlab_external/limitations-to-cpp-support-in-matlab-cpp-library-interface.html), which, - at least when we discussed this at the very beginning of the toolbox work, - were deemed too limiting (fwiw, we do use vectors of shared pointers to objects in C++, [see a CLib wrapped example here](https://cantera.org/dev/cxx/db/dde/group__CAPIctsol.html#ga0f57671d24229d81fc6478ad2812939e)). These limitations aren't an issue when calling into Cantera's CLib.

Regarding segfaults: I am not aware of what exact issues you are referring to - if there's an issue in Cantera's CLib, then the right approach would be to file an issue report on GH (there's the caveat that there now are two CLib versions). One thing I need to point out, however, is that the current version of the Cantera MATLAB toolbox mostly ignores exceptions being thrown in the C++ layer. Instead, all the checks are re-implemented, which creates the problematic situation that C++ exceptions are ignored if there's a missing MATLAB guard, and subsequent calls into CLib may cause hard crashes. It would be, imho, preferable to let C++ handle all exceptions and just rethrow them in MATLAB.

Finally, at least to me it appears that the MATLAB code generation envisioned by this PR is perpendicular to the intent of Cantera/enhancements#39. Ideally, class methods that call into CLib should be generated automatically rather than hand-coded. This admittedly goes well beyond what I believe makes sense for the initial release of the new MATLAB toolbox, which is overall close.

**Comment by rwest** [comment]
I'll let Su try to correct or clarify my comments above. I likely got some things wrong. I agree with this "goes well beyond what I believe makes sense for the initial release of the new MATLAB toolbox, which is overall close."
I think we're still exploring the next new new MATLAB interface 😝 but should get the current one in soon.

**Comment by ischoegl** [comment]
> I'll let Su try to correct or clarify my comments above. I likely got some things wrong. I agree with this "goes well beyond what I believe makes sense for the initial release of the new MATLAB toolbox, which is overall close." I think we're still exploring the next new new MATLAB interface 😝 but should get the current one in soon.

Sounds good. From my perspective, what’s “under the hood” is secondary as long as things work and the overall approach is consistent with Cantera’s overall design philosophy. If done right, implementation details can be swapped out in the future without a change in the user-facing API.

**Comment by ischoegl** [comment]
> This interface requires a MATLAB release newer than R2020b. 

As an aside, if we require a much newer version than in the past, I’d suggest to go to R2021a, where [support for keyword arguments is added](https://www.mathworks.com/help/matlab/matlab_prog/namevalue-in-function-calls.html).

**Comment by ischoegl** [comment]
@ssun30 ... I looked at some of the [MATLAB documentation](https://www.mathworks.com/help/matlab/matlab_external/load-cpp-library-in-process-or-out-of-process.html?searchHighlight=Alternatively&s_tid=srchtitle_support_results_3_Alternatively). If this ends up being just for 'out-of-process' execution, I would prefer to make things as simple as possible and skip the publication of an interface, e.g., the 'alternative' approach that calls clib commands directly in the library namespace. In effect, this is already done in this PR. My hangup is that there is no need for the published/generated wrapper file, as you're using direct calls in `ctFunc.m` anyway?

To make sure that I understand the process: Is is true that, using the modern C++ Interface, it may be as simple as 
```
% Step 1: Generate definition with multiple headers, single library
defFile = clibgen.generateLibraryDefinition( ...
    ["ct_<one>.h", "ct_<two>.h", ..., "ct_<three>.h"], ...
    "Libraries", "cantera_shared.dll", ...
    "LibraryName", "ctMatlab");

% Step 2: Build interface  
build(defFile);

% Step 3: Configure for out-of-process execution
libraryconfig = clibConfiguration("ctMatlab", ExecutionMode="outofprocess");

% Step 4: Call functions from any header - all under single namespace
result = clib.ctMatlab.someFunction(42);
```
Steps 1 and 2 need to be run once (unless rebuilding), and step 3 does the actual out-of-process configuration during a MATLAB session.

Of course, there needs to be additional code to resolve file locations and shared library types, where there is overlap with the installation question from #1911. I'd suggest resolving that one first, then rebase this one to make it clear what is done exactly.

**Comment by ischoegl** [comment]
Hi @ssun30 ... thanks for trying to rebase, but it appears that some of the recently merged work on #1911 was undone and/or changed to an earlier version.

I also noticed that in your commit "[MATLAB] Proof-of-concept for the new Interface" (currently https://github.com/Cantera/cantera/pull/1868/commits/4c13ec0f6ce26415e8fdded72c4cb2a7e51aaeb7) you are adding a rather large XML file that is later removed.

**Comment by ssun30** [comment]
> @ssun30 ... I looked at some of the [MATLAB documentation](https://www.mathworks.com/help/matlab/matlab_external/load-cpp-library-in-process-or-out-of-process.html?searchHighlight=Alternatively&s_tid=srchtitle_support_results_3_Alternatively). If this ends up being just for 'out-of-process' execution, I would prefer to make things as simple as possible and skip the publication of an interface, e.g., the 'alternative' approach that calls clib commands directly in the library namespace. In effect, this is already done in this PR. My hangup is that there is no need for the published/generated wrapper file, as you're using direct calls in `ctFunc.m` anyway?
> 
> To make sure that I understand the process: Is is true that, using the modern C++ Interface, it may be as simple as
> 
> ```
> % Step 1: Generate definition with multiple headers, single library
> defFile = clibgen.generateLibraryDefinition( ...
>     ["ct_<one>.h", "ct_<two>.h", ..., "ct_<three>.h"], ...
>     "Libraries", "cantera_shared.dll", ...
>     "LibraryName", "ctMatlab");
> 
> % Step 2: Build interface  
> build(defFile);
> 
> % Step 3: Configure for out-of-process execution
> libraryconfig = clibConfiguration("ctMatlab", ExecutionMode="outofprocess");
> 
> % Step 4: Call functions from any header - all under single namespace
> result = clib.ctMatlab.someFunction(42);
> ```
> 
> Steps 1 and 2 need to be run once (unless rebuilding), and step 3 does the actual out-of-process configuration during a MATLAB session.
> 
> Of course, there needs to be additional code to resolve file locations and shared library types, where there is overlap with the installation question from #1911. I'd suggest resolving that one first, then rebase this one to make it clear what is done exactly.

Your description is true. The user can call all functions defined in the headers with the modern C++ interface, but the same is also true for the existing `calllib` approach. The wrapper files exist solely to ease the learning curve so a user can, for example, just call `t1 = gas.T` and `ctFunc` calls the correct function for them, instead of `t1 = clib.ctMatlab.thermo_temperature(gas.id)`. 

> Hi @ssun30 ... thanks for trying to rebase, but it appears that some of the recently merged work on #1911 was undone and/or changed to an earlier version.
> 
> I also noticed that in your commit "[MATLAB] Proof-of-concept for the new Interface" (currently [4c13ec0](https://github.com/Cantera/cantera/commit/4c13ec0f6ce26415e8fdded72c4cb2a7e51aaeb7)) you are adding a rather large XML file that is later removed.

I will check commits and remove changes that undo the recent changes. 

One question I have is that, currently `scons install` still moves the legacy clib headers to the installed location while the generated clib stays under `interfaces/clib/include`. I'm planning to open a PR to resolve the installation issues but also switch to the new generated clib. When are we going to deprecate the legacy clib?

**Comment by ischoegl** [comment]
> Your description is true. The user can call all functions defined in the headers with the modern C++ interface, but the same is also true for the existing `calllib` approach. The wrapper files exist solely to ease the learning curve so a user can, for example, just call `t1 = gas.T` and `ctFunc` calls the correct function for them, instead of `t1 = clib.ctMatlab.thermo_temperature(gas.id)`.

Thanks for confirming. Overall, please understand that I am fully onboard with the wrapper you've been working on for some time (the 'out-of-process' approach changes this only marginally). I simply want to point out that the 'published interface' (i.e., the generated `definectMatlab.m` file) is an unnecessary step and should be removed; it is a distraction and not useful to the user base. Instead, the C++ interface should be used as a drop-in replacement for the older `calllib` approach.

> One question I have is that, currently `scons install` still moves the legacy clib headers to the installed location while the generated clib stays under `interfaces/clib/include`. I'm planning to open a PR to resolve the installation issues but also switch to the new generated clib. When are we going to deprecate the legacy clib?

The legacy CLib is de facto deprecated now. The MATLAB toolbox is the only API left that depends on it, and the plan is to remove the legacy CLib immediately after the 3.2 release. Beyond, I strongly believe that installation and CLib migration should be addressed in separate, single-issue PRs.

**Comment by ssun30** [comment]
> > Your description is true. The user can call all functions defined in the headers with the modern C++ interface, but the same is also true for the existing `calllib` approach. The wrapper files exist solely to ease the learning curve so a user can, for example, just call `t1 = gas.T` and `ctFunc` calls the correct function for them, instead of `t1 = clib.ctMatlab.thermo_temperature(gas.id)`.
> 
> Thanks for confirming. Overall, please understand that I am fully onboard with the wrapper you've been working on for some time (the 'out-of-process' approach changes this only marginally). I simply want to point out that the 'published interface' (i.e., the generated `definectMatlab.m` file) is an unnecessary step and should be removed; it is a distraction and not useful to the user base. Instead, the C++ interface should be used as a drop-in replacement for the older `calllib` approach.

Ah I see. Yes the 'published interface' is definitely just an intermediate step that I only use for debugging purposes for now. Eventually all the intermediate files will only be generated during the build process, and the C++ interface will be the only file visible to the user.

**Review by ischoegl — CHANGES_REQUESTED** [review]
> Ah I see. Yes the 'published interface' is definitely just an intermediate step that I only use for debugging purposes for now. Eventually all the intermediate files will only be generated during the build process, and the C++ interface will be the only file visible to the user.

Please remove the 'published interface' from this PR (or, at least, make it optional). From a maintenance perspective, it makes little sense to have 100+ lines of undocumented code in `ctEditLibraryDefinitions.m` and `ctGenerateLibraryDefinitions.m` if much of what they generate is essentially bypassed by the actual implementation (i.e., to my understanding, `definectMatlab.m` is completely unnecessary). Instead, please focus on a minimal implementation that is a drop-in replacement for `calllib`.

**Comment by speth** [comment]
I'm fully in agreement with @ischoegl on the path forward for this PR -- let's just get this working with the minimal replacement for `calllib`. And let's prioritize this PR over the additional CI testing or any other changes.

One suggestion I have is that rather than struggling with `git rebase` to cleanup the issues that @ischoegl noted with changes being undone/redone and large files being added and removed, the easiest thing to do with this PR will be for us to just "squash and merge" once it's ready, and then we don't have to worry about the messy intermediate history.

**Comment by speth** [comment]
As a further point emphasizing the importance of focusing on this PR over any other MATLAB-related work, problems associated with the fragile `LD_PRELOAD` workaround are once again causing CI errors (see [this log](https://github.com/Cantera/cantera/actions/runs/17736873927/job/50400791704) from PR #1977) that degrade the ability to evaluate PRs that have nothing to do with MATLAB.

**Comment by ischoegl** [comment]
@ssun30 ... thank you for squashing the commits to remove the large XML. I believe at this point, the sticking point is the published interface. I would be willing to test what you have put together here, regardless, but the CI fails, and there are no updates to the `readme.md` file that provide installation instructions. _PS: I realize that this is still in 'draft' mode, but in order for this to make it into the upcoming 3.2 release, there needs to be some progress._

**Review by ischoegl — COMMENTED** [review]
@ssun30 ... while you're debugging the CI, please make sure that the instructions are updated so this can be tested on other machines. Right now, I get the following issue while loosely following the outdated `readme.md` file:

```
ctPaths('Set', '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/')
Unrecognized function or variable 'samplePath'.

Error in [ctPaths](matlab:matlab.lang.internal.introspective.errorDocCallback('ctPaths', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctPaths.m', 55)) ([line 55](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctPaths.m',55,0)))
            addpath(genpath(toolboxPath), genpath(samplePath));
                                                  ^^^^^^^^^^
```

**Comment by ischoegl** [comment]
@ssun30 (and @rwest) ... I tried installing what you've got locally on macOS (mostly by trial-and-error as the `readme.md` isn't updated). In the interest of moving this PR along, I am documenting how I got stuck below:

* I needed to use the root folder of the git repo, i.e., `export CANTERA_ROOT=/work/GitHub/cantera/` (I had originally tried to use the installed location, i.e., `export CANTERA_ROOT=/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev`, but that's incompatible with the current implementation)
* After setting the paths, I was able to compile with `ctBuildInterface()` (with some errors being displayed due to `ldd` not existing on macOS).
* Running `ctLoad()` threw this exception

```
>> ctLoad()
Unable to load interface library: '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.dylib'. Reason:
The specified module could not be found.
Ensure the C++ dependent libraries for the interface library are added to run-time path.

Error in [ctString](matlab:matlab.lang.internal.introspective.errorDocCallback('ctString'))

Error in [ctVersion](matlab:matlab.lang.internal.introspective.errorDocCallback('ctVersion', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctVersion.m', 9)) ([line 9](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctVersion.m',9,0)))
    v = ctString('ct_getCanteraVersion');
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in [ctLoad](matlab:matlab.lang.internal.introspective.errorDocCallback('ctLoad', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctLoad.m', 18)) ([line 18](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctLoad.m',18,0)))
    fprintf('Cantera %s is ready for use (%s mode).\n', ctVersion, mode);
                                                        ^^^^^^^^^
[Related documentation](matlab:helpview('matlab','error_CPP_InterfaceLibraryNotLoaded'))
```
which points at some paths being created incorrectly.

Regarding the build process, I have this:
```
Interface file 'ctMatlabInterface.dylib' built in folder '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'.

To use the library, add the interface file folder to the MATLAB path.
[addpath('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('addpath(''/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'')'))
Execution mode 'ctMatlab' set to 'outofprocess'. To modify, call [clibConfiguration('ctMatlab','ExecutionMode','inprocess')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('clibConfiguration(''ctMatlab'',''ExecutionMode'',''inprocess'')')).
 Copied 1 run-time library files to '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'
    /work/GitHub/cantera//build/lib/libcantera_shared.dylib

 Run-time dependencies copied to interface library folder.
```

Fwiw, I also found out that `ctPaths` appears to be defunct (and broken).

PS: The `definectMatlab.m` (4000ish lines) is generated in the repo (`interfaces/matlab_experimental/cantera`), along with other files. At the least, those should be added to a `.gitignore` file ...

File: interfaces/matlab_experimental/cantera/ctEditLibraryDefinitions.m [hunk 1]
```diff
@@ -0,0 +1,70 @@
+function ctEditLibraryDefinitions(fileDir)
+    fname = fileDir + "/definectMatlab.m";
```
Comment (ischoegl) [inline interfaces/matlab_experimental/cantera/ctEditLibraryDefinitions.m:13]: This needs a docstring.

File: interfaces/matlab_experimental/cantera/ctBuildInterface.m [hunk 2]
```diff
@@ -0,0 +1,28 @@
+function ctBuildInterface(ctDir, includeDir, ctLibDir)
+    % Builds the Cantera MATLAB C++ Interface from the Cantera CLib
+    % header files and the compiled Cantera library.
```
Comment (ischoegl) [inline interfaces/matlab_experimental/cantera/ctBuildInterface.m]: This needs an improved docstring

File: interfaces/matlab_experimental/cantera/ctGenerateLibraryDefinitions.m [hunk 3]
```diff
@@ -0,0 +1,27 @@
+function ctGenerateLibraryDefinitions(includeDir, headerDir, ctLibDir, outputDir)
+    % Generate paths for header files
```
Comment (ischoegl) [inline interfaces/matlab_experimental/cantera/ctGenerateLibraryDefinitions.m]: This needs an improved docstring.

File: interfaces/matlab_experimental/readme.md [hunk 4]
```diff
@@ -1,40 +1,111 @@
...
+   Choose one of the following options:
+
+   * Pull Cantera source code from [GitHub](https://github.com/Cantera/cantera)
+   * Download from the MATLAB File Exchange (placeholder link)
+
+2. **Obtain Cantera library and header files**
+   Choose one of the following methods:
+
+   * **Compile from source** and install in your Conda environment by following
+   instructions: [Cantera Source Install](https://cantera.org/stable/develop/index.html)
```
Comment (ischoegl) [inline interfaces/matlab_experimental/readme.md:29]: The LLM apparently didn't catch the `clib_legacy = True` option that is _essential_ for this to work 😉

File: .gitignore [hunk 5]
```diff
@@ -15,7 +15,8 @@ include/cantera/base/config.h
 include/cantera/base/config.h.build
 include/cantera/base/system.h.gch
 include/cantera/ext/
-interfaces/matlab_experimental/Utility/ctRoot.m
+interfaces/matlab_experimental/cantera/definectMatlab.m
+interfaces/matlab_experimental/cantera/ctMatlabData.xml
```
Comment (ischoegl) [inline .gitignore:20]: There's also the `interfaces/matlab_experimental/cantera/ctMatlab` folder.

**Review by ischoegl — CHANGES_REQUESTED** [review]
I just tested the current status and, on macOS, still don't get a running system. After regenerating all files (I made sure to remove the old install) and following the updated `readme.md`, I now get:
```
>> ctLoad()
Unable to load interface library: '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.dylib'. Reason:
The specified module could not be found.
Ensure the C++ dependent libraries for the interface library are added to run-time path.
```

The library exists at this location! The new C++ ways apparently introduce some uncomfortable library dependencies that need to be resolved (I believe this is the same issue as the one you faced with CI). I tried launching MATLAB either the usual way or from within the conda environment, and it didn't make a difference.

On the upside, I am happy to see the environment gone!

I am still not happy about the published interface, but, at the moment, it is more important to get this to run.

PS: here's my full listing:
```
>> ctDir = '/work/GitHub/cantera';
>> ctIncludeDir = '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include';
>> ctLibDir = '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib';
>> ctBuildInterface(ctDir, ctIncludeDir, ctLibDir);
Paths used in the build process:
Cantera Root: /work/GitHub/cantera
Include Directory: /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include
Header Directory: /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include/cantera/clib
Cantera Library: /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib
Output Folder: /work/GitHub/cantera/interfaces/matlab_experimental/cantera
MEX configured to use 'Xcode Clang++' for C++ language compilation.
Deleted file '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/definectMatlab.m'.
C++ compiler set to 'Xcode Clang++'.
Definition file [definectMatlab.m](matlab: open('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/definectMatlab.m')) contains definitions for 351 constructs supported by MATLAB.
- 264 constructs are fully defined.
- 87 constructs partially defined and commented out.

To include the 87 undefined constructs in the interface, uncomment and complete the definitions in [definectMatlab.m](matlab: open('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/definectMatlab.m')).
To build the interface, call build(definectMatlab).
Building interface file 'ctMatlabInterface.dylib' for clib interface 'ctMatlab'.
Build Log:
/usr/bin/xcrun -sdk macosx26.0 clang++ -c -fno-common -arch arm64 -mmacosx-version-min=12.0 -fexceptions -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fwrapv -ffp-contract=off  -fobjc-arc -std=c++14 -stdlib=libc++ -O2 -DNDEBUG   -I"/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include" -I"/Applications/MATLAB_R2025a.app/extern/include"  "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.cpp" -o "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.o"

/usr/bin/xcrun -sdk macosx26.0 clang++ -Wl,-twolevel_namespace  -arch arm64 -mmacosx-version-min=12.0 -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -framework Cocoa -bundle  -stdlib=libc++   "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.o"  "/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib/libcantera_shared.dylib" "/Applications/MATLAB_R2025a.app/extern/bin/maca64/libMatlabDataArray.dylib"  -Wl,-rpath,@loader_path/ -O   -o "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.dylib" -sectcreate __TEXT us_resources "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlab.zip"


---
Interface file 'ctMatlabInterface.dylib' built in folder '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'.

To use the library, add the interface file folder to the MATLAB path.
[addpath('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('addpath(''/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'')'))
Execution mode 'ctMatlab' set to 'outofprocess'. To modify, call [clibConfiguration('ctMatlab','ExecutionMode','inprocess')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('clibConfiguration(''ctMatlab'',''ExecutionMode'',''inprocess'')')).
 Copied 1 run-time library files to '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'
    /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib/libcantera_shared.dylib

 Run-time dependencies copied to interface library folder.
```

**Comment by ssun30** [comment]
> @ssun30 (and @rwest) ... I tried installing what you've got locally on macOS (mostly by trial-and-error as the `readme.md` isn't updated). In the interest of moving this PR along, I am documenting how I got stuck below:
> 
> * I needed to use the root folder of the git repo, i.e., `export CANTERA_ROOT=/work/GitHub/cantera/` (I had originally tried to use the installed location, i.e., `export CANTERA_ROOT=/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev`, but that's incompatible with the current implementation)
> * After setting the paths, I was able to compile with `ctBuildInterface()` (with some errors being displayed due to `ldd` not existing on macOS).
> * Running `ctLoad()` threw this exception
> 
> ```
> >> ctLoad()
> Unable to load interface library: '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.dylib'. Reason:
> The specified module could not be found.
> Ensure the C++ dependent libraries for the interface library are added to run-time path.
> 
> Error in [ctString](matlab:matlab.lang.internal.introspective.errorDocCallback('ctString'))
> 
> Error in [ctVersion](matlab:matlab.lang.internal.introspective.errorDocCallback('ctVersion', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctVersion.m', 9)) ([line 9](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctVersion.m',9,0)))
>     v = ctString('ct_getCanteraVersion');
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error in [ctLoad](matlab:matlab.lang.internal.introspective.errorDocCallback('ctLoad', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctLoad.m', 18)) ([line 18](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctLoad.m',18,0)))
>     fprintf('Cantera %s is ready for use (%s mode).\n', ctVersion, mode);
>                                                         ^^^^^^^^^
> [Related documentation](matlab:helpview('matlab','error_CPP_InterfaceLibraryNotLoaded'))
> ```
> 
> which points at some paths being created incorrectly.
> 
> Regarding the build process, I have this:
> 
> ```
> Interface file 'ctMatlabInterface.dylib' built in folder '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'.
> 
> To use the library, add the interface file folder to the MATLAB path.
> [addpath('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('addpath(''/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'')'))
> Execution mode 'ctMatlab' set to 'outofprocess'. To modify, call [clibConfiguration('ctMatlab','ExecutionMode','inprocess')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('clibConfiguration(''ctMatlab'',''ExecutionMode'',''inprocess'')')).
>  Copied 1 run-time library files to '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'
>     /work/GitHub/cantera//build/lib/libcantera_shared.dylib
> 
>  Run-time dependencies copied to interface library folder.
> ```
> 
> Fwiw, I also found out that `ctPaths` appears to be defunct (and broken).
> 
> PS: The `definectMatlab.m` (4000ish lines) is generated in the repo (`interfaces/matlab_experimental/cantera`), along with other files. At the least, those should be added to a `.gitignore` file ...

hi @ischoegl , I fixed the CI issues and updated the readme file. As for the ctLoad issue on MacOS, what are the outputs for the dependencies of `ctMatlabInterface.dylib` from otool?

**Comment by ischoegl** [comment]
Here's what I have:
```
(cantera-dev) ischoegl@schroedinger ctMatlab % otool -L ctMatlabInterface.dylib
ctMatlabInterface.dylib:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 24.0.0)
	@rpath/libcantera_shared.3.2.0.dylib (compatibility version 3.2.0, current version 3.2.0)
	@rpath/libMatlabDataArray.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 2000.63.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1356.0.0)
```
Likely the runtime search path? I did provide complete paths to the installer ... it appears to copy the unversioned shared library while it links to the versioned one?
```
(cantera-dev) ischoegl@schroedinger ctMatlab % ls
ctMatlabInterface.dylib	libcantera_shared.dylib
```

Fwiw, I'm on MATLAB R2025a and macOS 15.7.

File: interfaces/matlab_experimental/readme.md [hunk 6]
```diff
@@ -1,40 +1,111 @@
...
+
+4. **Unload the toolbox**
+   To stop using the interface, run:
+
+   ```matlab
+   ctCleanUp
+   ctUnload
+   ```
+
+---
```
Comment (ischoegl) [inline interfaces/matlab_experimental/readme.md:113]: Please also add instructions on how to run the test suite when compiling locally.

**Comment by ssun30** [comment]
> I just tested the current status and, on macOS, still don't get a running system. After regenerating all files (I made sure to remove the old install) and following the updated `readme.md`, I now get:
> 
> ```
> >> ctLoad()
> Unable to load interface library: '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.dylib'. Reason:
> The specified module could not be found.
> Ensure the C++ dependent libraries for the interface library are added to run-time path.
> ```
> 
> The library exists at this location! The new C++ ways apparently introduce some uncomfortable library dependencies that need to be resolved (I believe this is the same issue as the one you faced with CI). I tried launching MATLAB either the usual way or from within the conda environment, and it didn't make a difference.
> 
> On the upside, I am happy to see the environment gone!
> 
> I am still not happy about the published interface, but, at the moment, it is more important to get this to run.
> 
> PS: here's my full listing:
> 
> ```
> >> ctDir = '/work/GitHub/cantera';
> >> ctIncludeDir = '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include';
> >> ctLibDir = '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib';
> >> ctBuildInterface(ctDir, ctIncludeDir, ctLibDir);
> Paths used in the build process:
> Cantera Root: /work/GitHub/cantera
> Include Directory: /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include
> Header Directory: /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include/cantera/clib
> Cantera Library: /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib
> Output Folder: /work/GitHub/cantera/interfaces/matlab_experimental/cantera
> MEX configured to use 'Xcode Clang++' for C++ language compilation.
> Deleted file '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/definectMatlab.m'.
> C++ compiler set to 'Xcode Clang++'.
> Definition file [definectMatlab.m](matlab: open('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/definectMatlab.m')) contains definitions for 351 constructs supported by MATLAB.
> - 264 constructs are fully defined.
> - 87 constructs partially defined and commented out.
> 
> To include the 87 undefined constructs in the interface, uncomment and complete the definitions in [definectMatlab.m](matlab: open('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/definectMatlab.m')).
> To build the interface, call build(definectMatlab).
> Building interface file 'ctMatlabInterface.dylib' for clib interface 'ctMatlab'.
> Build Log:
> /usr/bin/xcrun -sdk macosx26.0 clang++ -c -fno-common -arch arm64 -mmacosx-version-min=12.0 -fexceptions -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fwrapv -ffp-contract=off  -fobjc-arc -std=c++14 -stdlib=libc++ -O2 -DNDEBUG   -I"/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/include" -I"/Applications/MATLAB_R2025a.app/extern/include"  "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.cpp" -o "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.o"
> 
> /usr/bin/xcrun -sdk macosx26.0 clang++ -Wl,-twolevel_namespace  -arch arm64 -mmacosx-version-min=12.0 -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -framework Cocoa -bundle  -stdlib=libc++   "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.o"  "/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib/libcantera_shared.dylib" "/Applications/MATLAB_R2025a.app/extern/bin/maca64/libMatlabDataArray.dylib"  -Wl,-rpath,@loader_path/ -O   -o "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlabInterface.dylib" -sectcreate __TEXT us_resources "/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab/ctMatlab.zip"
> 
> 
> ---
> Interface file 'ctMatlabInterface.dylib' built in folder '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'.
> 
> To use the library, add the interface file folder to the MATLAB path.
> [addpath('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('addpath(''/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'')'))
> Execution mode 'ctMatlab' set to 'outofprocess'. To modify, call [clibConfiguration('ctMatlab','ExecutionMode','inprocess')](matlab: internal.matlab.desktop.commandwindow.executeCommandForUser('clibConfiguration(''ctMatlab'',''ExecutionMode'',''inprocess'')')).
>  Copied 1 run-time library files to '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/cantera/ctMatlab'
>     /opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/lib/libcantera_shared.dylib
> 
>  Run-time dependencies copied to interface library folder.
> ```

This problem should be fixed by now. By default MATLAB on MacOS does not set the correct `DYLD_LIBRARY_PATH` variables for an external process. The missing dependency is `libMatlabDataArray.dylib`.

File: interfaces/matlab_experimental/readme.md (hunk 6 above)
Comment (ssun30) [reply interfaces/matlab_experimental/readme.md:113]: The test suite should run the same way for local compilation as other methods. The process of loading the library should no longer depend on the location of the header files (these are no longer needed after `ctBuildInterface`).

File: test/matlab_experimental/ctTestConstPressureReactor.m [hunk 7]
```diff
@@ -141,6 +141,7 @@ function integrate(self, surf)
     methods (Test)
 
         function testReactorSurfaceType(self)
+            self.assumeFail('Skipped until generated Clib is implemented');
```
Comment (ischoegl) [inline test/matlab_experimental/ctTestConstPressureReactor.m]: Minor comment: the generated CLib _is implemented_ but currently not used by the MATLAB tb.

File: interfaces/matlab_experimental/readme.md [hunk 8]
```diff
@@ -1,40 +1,112 @@
...
+
+### Installation Steps
+
+1. **Download the MATLAB Cantera toolbox**
+   Choose one of the following options:
+
+   * Pull Cantera source code from [GitHub](https://github.com/Cantera/cantera)
+   * Download from the MATLAB File Exchange (placeholder link)
```
Comment (ischoegl) [inline interfaces/matlab_experimental/readme.md]: The file exchange may cause confusion; I recommend omitting this until it's actually available.

File: interfaces/matlab_experimental/readme.md [hunk 9]
```diff
@@ -1,40 +1,112 @@
...
+
+2. **Obtain Cantera library and header files**
+   Choose one of the following methods:
+
+   * **Compile from source** and install in your Conda environment by following
+   instructions: [Cantera Source Install](https://cantera.org/stable/develop/index.html)
+   Note that the `clib_legacy` flag must be set to `true` for the current interface.
+   * **Install development interface via Conda**: [Cantera Conda Development Install](https://cantera.org/stable/install/conda.html#development-c-fortran-90-interface)
```
Comment (ischoegl) [inline interfaces/matlab_experimental/readme.md]: The conda version won't use the `clib_legacy` flag as the default is the generated CLib. Until CLib is ported, the only option is to compile from source.

**Review by ischoegl — CHANGES_REQUESTED** [review]
Thanks, @ssun30. Almost there, the main issue I ran into is this one:

```
>> ctLoad()
Cantera 3.2.0a4 is ready for use (outofprocess mode).
>> cd test/matlab_experimental/
>> runMatlabInterfaceTests
Error using [matlab.unittest.internal.createTestSuite](matlab:matlab.lang.internal.introspective.errorDocCallback('matlab.unittest.internal.createTestSuite', '/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/+matlab/+unittest/+internal/createTestSuite.m', 21)) ([line 21](matlab: opentoline('/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/+matlab/+unittest/+internal/createTestSuite.m',21,0)))
Unable to create a test suite from /Volumes/Data/work/GitHub/cantera/test/matlab_experimental/test/matlab_experimental.

Error in [testsuite](matlab:matlab.lang.internal.introspective.errorDocCallback('testsuite', '/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/testsuite.m', 95)) ([line 95](matlab: opentoline('/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/testsuite.m',95,0)))
suite = matlab.unittest.internal.createTestSuite(tests, options);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in [runMatlabInterfaceTests](matlab:matlab.lang.internal.introspective.errorDocCallback('runMatlabInterfaceTests', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/runMatlabInterfaceTests.m', 5)) ([line 5](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/runMatlabInterfaceTests.m',5,0)))
suite = testsuite(testFolder);
        ^^^^^^^^^^^^^^^^^^^^^
```

PS: I spot-tested samples, and some ran :tada: (although others didn't, e.g., `diamond_cvd` but that may be related to #1722?)

**Comment by ssun30** [comment]
> Thanks, @ssun30. Almost there, the main issue I ran into is this one:
> 
> ```
> >> ctLoad()
> Cantera 3.2.0a4 is ready for use (outofprocess mode).
> >> cd test/matlab_experimental/
> >> runMatlabInterfaceTests
> Error using [matlab.unittest.internal.createTestSuite](matlab:matlab.lang.internal.introspective.errorDocCallback('matlab.unittest.internal.createTestSuite', '/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/+matlab/+unittest/+internal/createTestSuite.m', 21)) ([line 21](matlab: opentoline('/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/+matlab/+unittest/+internal/createTestSuite.m',21,0)))
> Unable to create a test suite from /Volumes/Data/work/GitHub/cantera/test/matlab_experimental/test/matlab_experimental.
> 
> Error in [testsuite](matlab:matlab.lang.internal.introspective.errorDocCallback('testsuite', '/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/testsuite.m', 95)) ([line 95](matlab: opentoline('/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/testsuite.m',95,0)))
> suite = matlab.unittest.internal.createTestSuite(tests, options);
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error in [runMatlabInterfaceTests](matlab:matlab.lang.internal.introspective.errorDocCallback('runMatlabInterfaceTests', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/runMatlabInterfaceTests.m', 5)) ([line 5](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/runMatlabInterfaceTests.m',5,0)))
> suite = testsuite(testFolder);
>         ^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> PS: I spot-tested samples, and some ran 🎉 (although others didn't, e.g., `diamond_cvd` but that may be related to #1722?)

That was caused by that script not using the correct relative paths. Should be fixed now. 

The `diamond_cvd` sample is unrelated to #1722 but because the legacy clib method `surf_setCoverages` not having a defined length of the surface coverage array. As such, `ctEditLibraryDefinitions.m` couldn't set the correct `<SHAPE>` parameter for the corresponding MATLAB function. The same goes for the getter method for surface coverages, and setter/getter for surface concentrations. These edge cases should no longer be the case with the generated cib.

**Comment by ssun30** [comment]
> > Thanks, @ssun30. Almost there, the main issue I ran into is this one:
> > ```
> > >> ctLoad()
> > Cantera 3.2.0a4 is ready for use (outofprocess mode).
> > >> cd test/matlab_experimental/
> > >> runMatlabInterfaceTests
> > Error using [matlab.unittest.internal.createTestSuite](matlab:matlab.lang.internal.introspective.errorDocCallback('matlab.unittest.internal.createTestSuite', '/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/+matlab/+unittest/+internal/createTestSuite.m', 21)) ([line 21](matlab: opentoline('/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/+matlab/+unittest/+internal/createTestSuite.m',21,0)))
> > Unable to create a test suite from /Volumes/Data/work/GitHub/cantera/test/matlab_experimental/test/matlab_experimental.
> > 
> > Error in [testsuite](matlab:matlab.lang.internal.introspective.errorDocCallback('testsuite', '/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/testsuite.m', 95)) ([line 95](matlab: opentoline('/Applications/MATLAB_R2025a.app/toolbox/matlab/testframework/unittest/core/testsuite.m',95,0)))
> > suite = matlab.unittest.internal.createTestSuite(tests, options);
> >         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > Error in [runMatlabInterfaceTests](matlab:matlab.lang.internal.introspective.errorDocCallback('runMatlabInterfaceTests', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/runMatlabInterfaceTests.m', 5)) ([line 5](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/runMatlabInterfaceTests.m',5,0)))
> > suite = testsuite(testFolder);
> >         ^^^^^^^^^^^^^^^^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS: I spot-tested samples, and some ran 🎉 (although others didn't, e.g., `diamond_cvd` but that may be related to #1722?)
> 

That was caused by that script not using the correct relative paths. Should be fixed now.

The `diamond_cvd` sample is unrelated to #1722 but because the legacy clib method `surf_setCoverages` not having a defined length of the surface coverage array. As such, `ctEditLibraryDefinitions.m` couldn't set the correct `<SHAPE>` parameter for the corresponding MATLAB function. The same goes for the getter method for surface coverages, and setter/getter for surface concentrations. These edge cases should no longer be a concern with the generated cib (I tested the generated Clib and all arrays have defined lengths).

**Review by ischoegl — COMMENTED** [review]
Making progress! The latest fix was successful for the test suite. There are three failed tests, though, when running locally:
```
>> runMatlabInterfaceTests
Running ctTestConstPressureReactor
Cantera 3.2.0a4 is ready for use (outofprocess mode).

================================================================================
ctTestConstPressureReactor/testReactorSurfaceType was filtered.
    Test Diagnostic: Skipped until Clib is ported to the generated version
[Details](matlab:matlab.automation.internal.displayToWebWindowAsText('PHN0cm9uZz5BbiBhc3N1bXB0aW9uIHdhcyBub3QgbWV0IGluIGN0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yL3Rlc3RSZWFjdG9yU3VyZmFjZVR5cGUgYW5kIGl0IGZpbHRlcmVkIHRoZSByZW1haW5kZXIgb2YgdGhlIHRlc3QuPC9zdHJvbmc+CiAgICAtLS0tLS0tLS0tLS0tLS0tCiAgICBUZXN0IERpYWdub3N0aWM6CiAgICAtLS0tLS0tLS0tLS0tLS0tCiAgICBTa2lwcGVkIHVudGlsIENsaWIgaXMgcG9ydGVkIHRvIHRoZSBnZW5lcmF0ZWQgdmVyc2lvbgogICAgLS0tLS0tLS0tLS0tLS0tLS0tCiAgICBTdGFjayBJbmZvcm1hdGlvbjoKICAgIC0tLS0tLS0tLS0tLS0tLS0tLQogICAgSW4gPGEgaHJlZj0ibWF0bGFiOm9wZW50b2xpbmUoJy9Wb2x1bWVzL0RhdGEvd29yay9HaXRIdWIvY2FudGVyYS90ZXN0L21hdGxhYl9leHBlcmltZW50YWwvY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IubScsMTQ0LDEpIj4vVm9sdW1lcy9EYXRhL3dvcmsvR2l0SHViL2NhbnRlcmEvdGVzdC9tYXRsYWJfZXhwZXJpbWVudGFsL2N0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yLm0gKGN0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yLnRlc3RSZWFjdG9yU3VyZmFjZVR5cGUpIGF0IDE0NDwvYT4K','QXNzdW1wdGlvbkZhaWxlZDogY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IvdGVzdFJlYWN0b3JTdXJmYWNlVHlwZQ=='))
================================================================================
.
================================================================================
Error occurred in ctTestConstPressureReactor/testClosed and it did not run to completion.
    ---------
    Error ID:
    ---------
    'Cantera:ctError'
    --------------
    Error Details:
    --------------
    Error using [ctFunc](matlab:matlab.lang.internal.introspective.errorDocCallback('ctFunc', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m', 12)) ([line 12](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m',12,0)))
    
    *******************************************************************************
    CanteraError thrown by Application::findInputFile:
    
    Input file ../data/ch4_minimal.yaml not found in directories
    '.',
    '/usr/local/Caskroom/miniconda/base/envs/ct-test/share/cantera/data',
    '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/share/cantera/data'
    
    To fix this problem, either:
        a) move the missing files into the local directory;
        b) define environment variable CANTERA_DATA to
             point to the directory containing the file.
    *******************************************************************************
    
    Error in [Solution](matlab:matlab.lang.internal.introspective.errorDocCallback('Solution', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m', 78)) ([line 78](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m',78,0)))
                    ID = ctFunc('soln_newSolution', src, name, transport_model);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error in [ctTestConstPressureReactor/makeReactors](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/makeReactors', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 40)) ([line 40](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',40,0)))
                self.gas = Solution(src, 'testConstPressureReactor');
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error in [ctTestConstPressureReactor/testClosed](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/testClosed', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 153)) ([line 153](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',153,0)))
                self.makeReactors();
                ^^^^^^^^^^^^^^^^^^^^
================================================================================
.
================================================================================
Error occurred in ctTestConstPressureReactor/testWithHeatTransfer and it did not run to completion.
    ---------
    Error ID:
    ---------
    'Cantera:ctError'
    --------------
    Error Details:
    --------------
    Error using [ctFunc](matlab:matlab.lang.internal.introspective.errorDocCallback('ctFunc', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m', 12)) ([line 12](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m',12,0)))
    
    *******************************************************************************
    CanteraError thrown by Application::findInputFile:
    
    Input file ../data/ch4_minimal.yaml not found in directories
    '.',
    '/usr/local/Caskroom/miniconda/base/envs/ct-test/share/cantera/data',
    '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/share/cantera/data'
    
    To fix this problem, either:
        a) move the missing files into the local directory;
        b) define environment variable CANTERA_DATA to
             point to the directory containing the file.
    *******************************************************************************
    
    Error in [Solution](matlab:matlab.lang.internal.introspective.errorDocCallback('Solution', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m', 78)) ([line 78](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m',78,0)))
                    ID = ctFunc('soln_newSolution', src, name, transport_model);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error in [ctTestConstPressureReactor/makeReactors](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/makeReactors', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 40)) ([line 40](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',40,0)))
                self.gas = Solution(src, 'testConstPressureReactor');
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error in [ctTestConstPressureReactor/testWithHeatTransfer](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/testWithHeatTransfer', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 158)) ([line 158](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',158,0)))
                self.makeReactors('addQ', true);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
================================================================================
.
================================================================================
Error occurred in ctTestConstPressureReactor/testWithMdot and it did not run to completion.
    ---------
    Error ID:
    ---------
    'Cantera:ctError'
    --------------
    Error Details:
    --------------
    Error using [ctFunc](matlab:matlab.lang.internal.introspective.errorDocCallback('ctFunc', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m', 12)) ([line 12](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m',12,0)))
    
    *******************************************************************************
    CanteraError thrown by Application::findInputFile:
    
    Input file ../data/ch4_minimal.yaml not found in directories
    '.',
    '/usr/local/Caskroom/miniconda/base/envs/ct-test/share/cantera/data',
    '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/share/cantera/data'
    
    To fix this problem, either:
        a) move the missing files into the local directory;
        b) define environment variable CANTERA_DATA to
             point to the directory containing the file.
    *******************************************************************************
    
    Error in [Solution](matlab:matlab.lang.internal.introspective.errorDocCallback('Solution', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m', 78)) ([line 78](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m',78,0)))
                    ID = ctFunc('soln_newSolution', src, name, transport_model);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error in [ctTestConstPressureReactor/makeReactors](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/makeReactors', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 40)) ([line 40](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',40,0)))
                self.gas = Solution(src, 'testConstPressureReactor');
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error in [ctTestConstPressureReactor/testWithMdot](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/testWithMdot', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 163)) ([line 163](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',163,0)))
                self.makeReactors('addMdot', true);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
================================================================================
.
================================================================================
ctTestConstPressureReactor/testWithSurfaceReactions was filtered.
    Test Diagnostic: Skipped until Clib is ported to the generated version
[Details](matlab:matlab.automation.internal.displayToWebWindowAsText('PHN0cm9uZz5BbiBhc3N1bXB0aW9uIHdhcyBub3QgbWV0IGluIGN0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yL3Rlc3RXaXRoU3VyZmFjZVJlYWN0aW9ucyBhbmQgaXQgZmlsdGVyZWQgdGhlIHJlbWFpbmRlciBvZiB0aGUgdGVzdC48L3N0cm9uZz4KICAgIC0tLS0tLS0tLS0tLS0tLS0KICAgIFRlc3QgRGlhZ25vc3RpYzoKICAgIC0tLS0tLS0tLS0tLS0tLS0KICAgIFNraXBwZWQgdW50aWwgQ2xpYiBpcyBwb3J0ZWQgdG8gdGhlIGdlbmVyYXRlZCB2ZXJzaW9uCiAgICAtLS0tLS0tLS0tLS0tLS0tLS0KICAgIFN0YWNrIEluZm9ybWF0aW9uOgogICAgLS0tLS0tLS0tLS0tLS0tLS0tCiAgICBJbiA8YSBocmVmPSJtYXRsYWI6b3BlbnRvbGluZSgnL1ZvbHVtZXMvRGF0YS93b3JrL0dpdEh1Yi9jYW50ZXJhL3Rlc3QvbWF0bGFiX2V4cGVyaW1lbnRhbC9jdFRlc3RDb25zdFByZXNzdXJlUmVhY3Rvci5tJywxNjgsMSkiPi9Wb2x1bWVzL0RhdGEvd29yay9HaXRIdWIvY2FudGVyYS90ZXN0L21hdGxhYl9leHBlcmltZW50YWwvY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IubSAoY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IudGVzdFdpdGhTdXJmYWNlUmVhY3Rpb25zKSBhdCAxNjg8L2E+Cg==','QXNzdW1wdGlvbkZhaWxlZDogY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IvdGVzdFdpdGhTdXJmYWNlUmVhY3Rpb25z'))
================================================================================
.Cantera has been unloaded

Done ctTestConstPressureReactor
```
[...]
```
Totals:
   481 Passed, 3 Failed ([rerun](matlab:matlab.unittest.internal.rerunFailedTests('results','WxMJLrbzksUukDqaqNVBcW7qktw4UYQYmL6HPQ=='))), 31 Incomplete.
   32.932 seconds testing time.

>> pwd

ans =

    '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental'
```

**Comment by ssun30** [comment]
> Making progress! The latest fix was successful for the test suite. There are three failed tests, though, when running locally:
> 
> ```
> >> runMatlabInterfaceTests
> Running ctTestConstPressureReactor
> Cantera 3.2.0a4 is ready for use (outofprocess mode).
> 
> ================================================================================
> ctTestConstPressureReactor/testReactorSurfaceType was filtered.
>     Test Diagnostic: Skipped until Clib is ported to the generated version
> [Details](matlab:matlab.automation.internal.displayToWebWindowAsText('PHN0cm9uZz5BbiBhc3N1bXB0aW9uIHdhcyBub3QgbWV0IGluIGN0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yL3Rlc3RSZWFjdG9yU3VyZmFjZVR5cGUgYW5kIGl0IGZpbHRlcmVkIHRoZSByZW1haW5kZXIgb2YgdGhlIHRlc3QuPC9zdHJvbmc+CiAgICAtLS0tLS0tLS0tLS0tLS0tCiAgICBUZXN0IERpYWdub3N0aWM6CiAgICAtLS0tLS0tLS0tLS0tLS0tCiAgICBTa2lwcGVkIHVudGlsIENsaWIgaXMgcG9ydGVkIHRvIHRoZSBnZW5lcmF0ZWQgdmVyc2lvbgogICAgLS0tLS0tLS0tLS0tLS0tLS0tCiAgICBTdGFjayBJbmZvcm1hdGlvbjoKICAgIC0tLS0tLS0tLS0tLS0tLS0tLQogICAgSW4gPGEgaHJlZj0ibWF0bGFiOm9wZW50b2xpbmUoJy9Wb2x1bWVzL0RhdGEvd29yay9HaXRIdWIvY2FudGVyYS90ZXN0L21hdGxhYl9leHBlcmltZW50YWwvY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IubScsMTQ0LDEpIj4vVm9sdW1lcy9EYXRhL3dvcmsvR2l0SHViL2NhbnRlcmEvdGVzdC9tYXRsYWJfZXhwZXJpbWVudGFsL2N0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yLm0gKGN0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yLnRlc3RSZWFjdG9yU3VyZmFjZVR5cGUpIGF0IDE0NDwvYT4K','QXNzdW1wdGlvbkZhaWxlZDogY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IvdGVzdFJlYWN0b3JTdXJmYWNlVHlwZQ=='))
> ================================================================================
> .
> ================================================================================
> Error occurred in ctTestConstPressureReactor/testClosed and it did not run to completion.
>     ---------
>     Error ID:
>     ---------
>     'Cantera:ctError'
>     --------------
>     Error Details:
>     --------------
>     Error using [ctFunc](matlab:matlab.lang.internal.introspective.errorDocCallback('ctFunc', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m', 12)) ([line 12](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m',12,0)))
>     
>     *******************************************************************************
>     CanteraError thrown by Application::findInputFile:
>     
>     Input file ../data/ch4_minimal.yaml not found in directories
>     '.',
>     '/usr/local/Caskroom/miniconda/base/envs/ct-test/share/cantera/data',
>     '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/share/cantera/data'
>     
>     To fix this problem, either:
>         a) move the missing files into the local directory;
>         b) define environment variable CANTERA_DATA to
>              point to the directory containing the file.
>     *******************************************************************************
>     
>     Error in [Solution](matlab:matlab.lang.internal.introspective.errorDocCallback('Solution', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m', 78)) ([line 78](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m',78,0)))
>                     ID = ctFunc('soln_newSolution', src, name, transport_model);
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     Error in [ctTestConstPressureReactor/makeReactors](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/makeReactors', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 40)) ([line 40](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',40,0)))
>                 self.gas = Solution(src, 'testConstPressureReactor');
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     Error in [ctTestConstPressureReactor/testClosed](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/testClosed', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 153)) ([line 153](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',153,0)))
>                 self.makeReactors();
>                 ^^^^^^^^^^^^^^^^^^^^
> ================================================================================
> .
> ================================================================================
> Error occurred in ctTestConstPressureReactor/testWithHeatTransfer and it did not run to completion.
>     ---------
>     Error ID:
>     ---------
>     'Cantera:ctError'
>     --------------
>     Error Details:
>     --------------
>     Error using [ctFunc](matlab:matlab.lang.internal.introspective.errorDocCallback('ctFunc', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m', 12)) ([line 12](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m',12,0)))
>     
>     *******************************************************************************
>     CanteraError thrown by Application::findInputFile:
>     
>     Input file ../data/ch4_minimal.yaml not found in directories
>     '.',
>     '/usr/local/Caskroom/miniconda/base/envs/ct-test/share/cantera/data',
>     '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/share/cantera/data'
>     
>     To fix this problem, either:
>         a) move the missing files into the local directory;
>         b) define environment variable CANTERA_DATA to
>              point to the directory containing the file.
>     *******************************************************************************
>     
>     Error in [Solution](matlab:matlab.lang.internal.introspective.errorDocCallback('Solution', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m', 78)) ([line 78](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m',78,0)))
>                     ID = ctFunc('soln_newSolution', src, name, transport_model);
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     Error in [ctTestConstPressureReactor/makeReactors](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/makeReactors', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 40)) ([line 40](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',40,0)))
>                 self.gas = Solution(src, 'testConstPressureReactor');
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     Error in [ctTestConstPressureReactor/testWithHeatTransfer](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/testWithHeatTransfer', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 158)) ([line 158](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',158,0)))
>                 self.makeReactors('addQ', true);
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ================================================================================
> .
> ================================================================================
> Error occurred in ctTestConstPressureReactor/testWithMdot and it did not run to completion.
>     ---------
>     Error ID:
>     ---------
>     'Cantera:ctError'
>     --------------
>     Error Details:
>     --------------
>     Error using [ctFunc](matlab:matlab.lang.internal.introspective.errorDocCallback('ctFunc', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m', 12)) ([line 12](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Utility/ctFunc.m',12,0)))
>     
>     *******************************************************************************
>     CanteraError thrown by Application::findInputFile:
>     
>     Input file ../data/ch4_minimal.yaml not found in directories
>     '.',
>     '/usr/local/Caskroom/miniconda/base/envs/ct-test/share/cantera/data',
>     '/opt/homebrew/Caskroom/miniforge/base/envs/cantera-dev/share/cantera/data'
>     
>     To fix this problem, either:
>         a) move the missing files into the local directory;
>         b) define environment variable CANTERA_DATA to
>              point to the directory containing the file.
>     *******************************************************************************
>     
>     Error in [Solution](matlab:matlab.lang.internal.introspective.errorDocCallback('Solution', '/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m', 78)) ([line 78](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/interfaces/matlab_experimental/Base/Solution.m',78,0)))
>                     ID = ctFunc('soln_newSolution', src, name, transport_model);
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     Error in [ctTestConstPressureReactor/makeReactors](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/makeReactors', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 40)) ([line 40](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',40,0)))
>                 self.gas = Solution(src, 'testConstPressureReactor');
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     Error in [ctTestConstPressureReactor/testWithMdot](matlab:matlab.lang.internal.introspective.errorDocCallback('ctTestConstPressureReactor/testWithMdot', '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m', 163)) ([line 163](matlab: opentoline('/Volumes/Data/work/GitHub/cantera/test/matlab_experimental/ctTestConstPressureReactor.m',163,0)))
>                 self.makeReactors('addMdot', true);
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ================================================================================
> .
> ================================================================================
> ctTestConstPressureReactor/testWithSurfaceReactions was filtered.
>     Test Diagnostic: Skipped until Clib is ported to the generated version
> [Details](matlab:matlab.automation.internal.displayToWebWindowAsText('PHN0cm9uZz5BbiBhc3N1bXB0aW9uIHdhcyBub3QgbWV0IGluIGN0VGVzdENvbnN0UHJlc3N1cmVSZWFjdG9yL3Rlc3RXaXRoU3VyZmFjZVJlYWN0aW9ucyBhbmQgaXQgZmlsdGVyZWQgdGhlIHJlbWFpbmRlciBvZiB0aGUgdGVzdC48L3N0cm9uZz4KICAgIC0tLS0tLS0tLS0tLS0tLS0KICAgIFRlc3QgRGlhZ25vc3RpYzoKICAgIC0tLS0tLS0tLS0tLS0tLS0KICAgIFNraXBwZWQgdW50aWwgQ2xpYiBpcyBwb3J0ZWQgdG8gdGhlIGdlbmVyYXRlZCB2ZXJzaW9uCiAgICAtLS0tLS0tLS0tLS0tLS0tLS0KICAgIFN0YWNrIEluZm9ybWF0aW9uOgogICAgLS0tLS0tLS0tLS0tLS0tLS0tCiAgICBJbiA8YSBocmVmPSJtYXRsYWI6b3BlbnRvbGluZSgnL1ZvbHVtZXMvRGF0YS93b3JrL0dpdEh1Yi9jYW50ZXJhL3Rlc3QvbWF0bGFiX2V4cGVyaW1lbnRhbC9jdFRlc3RDb25zdFByZXNzdXJlUmVhY3Rvci5tJywxNjgsMSkiPi9Wb2x1bWVzL0RhdGEvd29yay9HaXRIdWIvY2FudGVyYS90ZXN0L21hdGxhYl9leHBlcmltZW50YWwvY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IubSAoY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IudGVzdFdpdGhTdXJmYWNlUmVhY3Rpb25zKSBhdCAxNjg8L2E+Cg==','QXNzdW1wdGlvbkZhaWxlZDogY3RUZXN0Q29uc3RQcmVzc3VyZVJlYWN0b3IvdGVzdFdpdGhTdXJmYWNlUmVhY3Rpb25z'))
> ================================================================================
> .Cantera has been unloaded
> 
> Done ctTestConstPressureReactor
> ```
> 
> [...]
> 
> ```
> Totals:
>    481 Passed, 3 Failed ([rerun](matlab:matlab.unittest.internal.rerunFailedTests('results','WxMJLrbzksUukDqaqNVBcW7qktw4UYQYmL6HPQ=='))), 31 Incomplete.
>    32.932 seconds testing time.
> 
> >> pwd
> 
> ans =
> 
>     '/Volumes/Data/work/GitHub/cantera/test/matlab_experimental'
> ```

I wasn't able to reliably replicate this error. This test looks for a yaml data file in `../data` which should've been added to MATLAB search path by `ctTestSetUp`. There are other tests that do the same thing and they ran without problems. I did get this error a couple of times before on MacOS and Windows but running the script again resolved it. This was why I originally had each unit test copying those test data files into the local folder. This should be more robust after we implement the generated clib since we can use the `ct_addDataDirectories` to directly add the test data directory.

**Review by ischoegl — DISMISSED** [review]
> I wasn't able to reliably replicate this error. This test looks for a yaml data file in `../data` which should've been added to MATLAB search path by `ctTestSetUp`. There are other tests that do the same thing and they ran without problems. I did get this error a couple of times before on MacOS and Windows but running the script again resolved it. This was why I originally had each unit test copying those test data files into the local folder. This should be more robust after we implement the generated clib since we can use the `ct_addDataDirectories` to directly add the test data directory.

I can confirm that re-running the test suite does not produce the error. I'm approving this PR so the next two items can be tackled (either one can go first):
* Installation procedure needs to be worked out for local compilation (i.e., avoid pollution of root folder)
* Code needs to transition to the generated CLib

Beyond, I'll still mention #1722, which is a pretty significant caveat to having a fully operational MATLAB Toolbox. Also, documentation needs to be added. At the same time, getting this merged is progress!

I'll wait for a day or two before this gets merged, so @speth and @bryanwweber can chime in.

**Review by ischoegl — APPROVED** [review]
