### PR TITLE
[OneD] Fix issue in Sim1D::setFixedTemperature

### LINKED ISSUE #934: test_onedim.TestFreeFlame fails on OSX 10.15.6
**Problem description**
test_onedim.TestFreeFlame fails on OSX

**Steps to reproduce**
Run `scons test `

**Behavior**
======================================================================
FAIL: test_write_hdf (cantera.test.test_onedim.TestFreeFlame)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/santosh1/packages/canteraSource/build/python/cantera/test/test_onedim.py", line 649, in test_write_hdf
    meta = f.read_hdf(filename)
  File "/Users/santosh1/packages/canteraSource/build/python/cantera/onedim.py", line 635, in read_hdf
    self.settings = meta
  File "/Users/santosh1/packages/canteraSource/build/python/cantera/onedim.py", line 663, in settings
    setattr(self, key, s[key])
  File "interfaces/cython/cantera/onedim.pyx", line 1411, in cantera._cantera.Sim1D.fixed_temperature.__set__
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by StFlow::setupGrid:
grid points must be monotonically increasing
***********************************************************************

**System information**

- Cantera version: [2.5.0b1 commit # 2cd06194e]
- OS: OSX 10.15.6 Catalina
- Python/MATLAB/other software versions: XCode 11.7, python 3.7, numpy 1.17

**Attachments**

**Additional context**
@bryanwweber could reproduce these, but the CI could not

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Avoid exact comparison of floats as criterion whether new point needs to be added.

**If applicable, fill in the issue number this pull request is fixing**

Fixes #934

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by santoshshanbhogue** [comment]
Yup, can confirm that this fixes #934 on OSX 10.15.16. Thanks @ischoegl 

`
*****************************
***    Testing Summary    ***
*****************************

Tests passed: 1125
Up-to-date tests skipped: 0
Tests failed: 1
Failed tests:
    - python:test_onedim.TestIonBurnerFlame.test_ion_profile

*****************************
[`](url)

**Comment by ischoegl** [comment]
@santoshshanbhogue ... thank you for confirming! Per discussion, this was not caught by CI. The one remaining failure pertains to #935, which I will not address in this PR.

File: src/oneD/Sim1D.cpp [hunk 1]
```diff
@@ -445,14 +445,21 @@ int Sim1D::setFixedTemperature(double t)
...
                     d_free->m_tfixed = t;
                     addnewpt = false;
                     break;
-                } else if ((value(n,2,m)<t) && (value(n,2,m+1)>t)) {
+                } else if (fabs(value(n, 2, m + 1) - t) <= ttol * t) {
+                    zfixed = d.grid(m + 1);
+                    d_free->m_zfixed = zfixed;
+                    d_free->m_tfixed = t;
+                    addnewpt = false;
+                    break;
```
Comment (speth) [inline src/oneD/Sim1D.cpp]: I'm not sure I understand the purpose of adding this second case - won't point `m+1` always be considered in the next iteration of the loop over `m`?

File: src/oneD/Sim1D.cpp [hunk 2]
```diff
@@ -445,14 +445,21 @@ int Sim1D::setFixedTemperature(double t)
...
+                } else if ((value(n, 2, m) - t) * (value(n, 2, m + 1) - t) < 0.) {
```
Comment (speth) [inline src/oneD/Sim1D.cpp]: What's the motivation for this change? I think the previous expression more clearly conveyed its intention.

**Review by speth — CHANGES_REQUESTED** [review]
Adding a tolerance here makes sense to me, but I had a couple of questions about the implementation.

File: src/oneD/Sim1D.cpp (hunk 1 above)
Comment (ischoegl) [reply src/oneD/Sim1D.cpp]: It would, but there is one more point to check than there are iterations, and end points need to be checked. I didn’t feel like it was a speed-critical issue.

File: src/oneD/Sim1D.cpp (hunk 2 above)
Comment (ischoegl) [reply src/oneD/Sim1D.cpp]: It’s equivalent - so either is fine.

File: src/oneD/Sim1D.cpp (hunk 1 above)
Comment (speth) [reply src/oneD/Sim1D.cpp]: I'm more concerned about the code duplication than the redundant computation.

In addition, I don't think the last grid point should be a candidate for the fixed point temperature, given that the last grid point is usually being used to impose a zero gradient condition.

Comment (ischoegl) [reply src/oneD/Sim1D.cpp]: I agree that the last point isn’t a good candidate, but I’m not sure that it is safe to assume that it won’t come up. Personally I thought that it was straightforward from a conceptual viewpoint (code readability) ... I.e. you check whether a new point would be close to the ‘left’ and ‘right’ point within each interval.

Comment (ischoegl) [reply src/oneD/Sim1D.cpp]: PS: one thing that I did consider here would be to prevent closely spaced grid-points (which would be a change of behavior, but probably advantageous from a numerical point of view). I.e. if we’re close to a point, just adopt it and update the temperature (easily done by relaxing the tolerance) ... thoughts?

File: src/oneD/Sim1D.cpp (hunk 2 above)
Comment (ischoegl) [reply src/oneD/Sim1D.cpp]: Reverted (but simplified).

**Comment by ischoegl** [comment]
@speth ... I decided to go over the code to simplify / make it more readable. 

As with the other PR, I can rebase once #946 is merged.

File: src/oneD/Sim1D.cpp (hunk 1 above)
Comment (ischoegl) [reply src/oneD/Sim1D.cpp]: I streamlined the code to take care of code duplications.

**Review by speth — APPROVED** [review]
Looks good to me. I think this can be merged as soon as the tests pass.

**Review by bryanwweber — APPROVED** [review]
