### PR TITLE
Make ct2ctml check for string size

### LINKED ISSUE #416: Creating a Solution from a CTI string throws an error because the argument is too long on Windows
### Cantera version
2.3.0b1
### Operating System
Windows 10/Windows 7
### Python/MATLAB version
3.5.2
### Expected Behavior
A `Solution` is instantiated
### Actual Behavior
An error message is thrown by `ctml_writer`, the relevant part of which is
```
The filename or extension is too long.
[code 0x00ce (206)]
```
### Steps to reproduce
```
import cantera as ct
with open('species.txt', 'r') as cti_file:
    cti_source = cti_file.read()
ct.Solution(source=cti_source)
```
with the attached `species.txt`
[species.txt](https://github.com/Cantera/cantera/files/671344/species.txt)

### PR DESCRIPTION
**Pull request by santoshshanbhogue**
Fixes #416  .

Changes proposed in this pull request:
- Add a test in `ct2ctml.cpp` to check for string size when a string is passed using the `source=` argument

Caveats:
- Figured out how to test for the max argv size on *nix systems
- Not sure if this can be done on Windows (MinGW vs. VisualStudio), hence hardwired a `max_argv_size`
- Should we create a test that raises this error?

### CODE REVIEW

**Comment by santoshshanbhogue** [comment]
I tested this with a very long mechanism (m-Butanoate mech. downloaded from LLNL) on a Mac that has a 256k argv limit (262144 chars). The mechanism is > 300000 characters. It passes the test when I trim it to 259000 characters and fails when I trim it to just 26300

Ubuntu has a 2048K limit ! Did not venture to search a mech. that long

What is the best way to do a cross platform test ? Right now I use virtual machines. Is there a more efficient way?

**Comment by santoshshanbhogue** [comment]
Not sure what is going on with code-coverage

**Comment by bryanwweber** [comment]
@santoshshanbhogue Codecov is saying that you haven't added any tests to cover this code. If you write some tests, the continuous integration will handle testing on Windows, OS X, and Ubuntu. However, I agree with @speth (https://github.com/Cantera/cantera/issues/416#issuecomment-269061097) and think it would be better to figure out how to write files to a temp directory if necessary, and fail if that's not possible, rather than throwing an error for a too-long mechanism.

**Comment by santoshshanbhogue** [comment]
Thanks @bryanwweber. I'll continue to monitor the CI tests; but ct2ctml now creates a temp cti file and the user is also notified. If codecov fails, I'll need some pointers on where to add the tests for these...

**Comment by speth** [comment]
Codecov is guaranteed to fail because the patch adds code that is not covered by the test suite. You can add tests to `test_convert.py`, under the `CtmlConverterTest` class.

I would suggest adding two tests, one for cases that are (a) long but shorter than the crossover point and (b) one long enough to trigger the creation of a temp file. One easy way to do the latter is take a copy of `h2o2.cti` and append spaces to make it the desired length, e.g. something like `cti_source + ' '*50000`.

Did you test that 80000 characters is OK on Windows? When I tested GRI3.0 there, I found that that was too long and 64k is the apparent maximum for Windows 8.1, 64-bit. I'm not sure what it is on other versions of Windows. I'd be satisfied with capping it at ~32k just err on the side of caution.

File: src/base/ct2ctml.cpp [hunk 1]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+#ifndef _WIN32
+    int max_argv_size = sysconf(_SC_ARG_MAX);
+#endif
+
+    if (text.size() > max_argv_size) {
+
+      // If the file is too big to be passed as a command line argument later
+      // in the file, then create a temporary file and execute this function
+      // as though an input file was specified as the source. Notify the user
+      ofstream temp_cti_file("tempCtiFile.cti");
```
Comment (speth) [inline src/base/ct2ctml.cpp]: We should not be polluting the user's working directory with random files. I think it would be better to use `std::tmpnam` to generate a file name and then make sure we delete it before leaving this function.

File: src/base/ct2ctml.cpp [hunk 2]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+
+      if(temp_cti_file) {
+	temp_cti_file << text;
+	file = "tempCtiFile.cti";
+	arg = "r'tempCtiFile.cti'";
+
+	writelog("Created tempCtiFile.cti\n");
```
Comment (speth) [inline src/base/ct2ctml.cpp]: I don't think there should be any log output unless something goes wrong.

File: src/base/ct2ctml.cpp [hunk 3]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+
+    if (text.size() > max_argv_size) {
+
+      // If the file is too big to be passed as a command line argument later
+      // in the file, then create a temporary file and execute this function
+      // as though an input file was specified as the source. Notify the user
+      ofstream temp_cti_file("tempCtiFile.cti");
+
+      if(temp_cti_file) {
+	temp_cti_file << text;
```
Comment (speth) [inline src/base/ct2ctml.cpp]: Please update your editor's indentation settings: 4 spaces per indentation level, and use only spaces, no tabs -- currently this is a mix of tabs and spaces.

File: src/base/ct2ctml.cpp [hunk 4]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+	file = "tempCtiFile.cti";
+	arg = "r'tempCtiFile.cti'";
+
+	writelog("Created tempCtiFile.cti\n");
+      }
+      else {
+	// If we are here, then a temp file could not be created
+	stringstream message;
```
Comment (speth) [inline src/base/ct2ctml.cpp]: The `stringstream` here is unnecessary -- just supply this as the argument to `CanteraError` (you can just indent subsequent lines by one level instead of all the way to the open parentheses in cases like this). I might also recommend a more succinct error message.

File: src/base/ct2ctml.cpp [hunk 5]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+      ofstream temp_cti_file("tempCtiFile.cti");
+
+      if(temp_cti_file) {
+	temp_cti_file << text;
+	file = "tempCtiFile.cti";
+	arg = "r'tempCtiFile.cti'";
+
+	writelog("Created tempCtiFile.cti\n");
+      }
+      else {
```
Comment (speth) [inline src/base/ct2ctml.cpp]: `} else {` on one line.

File: src/base/ct2ctml.cpp [hunk 6]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+    // for Windows, we set an arbitrary limit of 80,000 chars
+#ifdef _WIN32
+    int max_argv_size = 80000;
+#endif
+
+#ifndef _WIN32
+    int max_argv_size = sysconf(_SC_ARG_MAX);
+#endif
+
+    if (text.size() > max_argv_size) {
```
Comment (speth) [inline src/base/ct2ctml.cpp]: `max_argv_size` is the length of the whole of `argv`, so we should add the approximate length of the rest of the command (~500 characters) here.

File: src/base/ct2ctml.cpp [hunk 7]
```diff
@@ -85,6 +89,52 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+    // to fit in the command line when routed to python as:
+    //       python -c ...
+    // statement downstream in the code
+
+    // So, check the max size of a string that can be passed on the command line
+    // This is OS Specific. *nix systems have the sysconf() function that tells 
+    // us the largest argument we can pass. Since such a function does not exist
+    // for Windows, we set an arbitrary limit of 80,000 chars
+#ifdef _WIN32
+    int max_argv_size = 80000;
```
Comment (speth) [inline src/base/ct2ctml.cpp]: As I mentioned before, I'm not convinced that this value is sufficiently small.

**Review by speth — CHANGES_REQUESTED** [review]

File: src/base/ct2ctml.cpp (hunk 7 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Yup, lowered this to 32kB

File: src/base/ct2ctml.cpp (hunk 6 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Done

File: src/base/ct2ctml.cpp (hunk 1 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Good idea. Modified accordingly at two places (one to create and another to remove)

File: src/base/ct2ctml.cpp (hunk 3 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: 😄 My bogeyman. Updated my .emacs profile

File: src/base/ct2ctml.cpp (hunk 2 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Removed

File: src/base/ct2ctml.cpp (hunk 5 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Done

File: src/base/ct2ctml.cpp (hunk 4 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Done

**Comment by santoshshanbhogue** [comment]
@speth if all tests pass, I could squash some commits if it improves the readability of the changelog file. Also, do you recommend running an update on fmt and googletests ? They don't automatically update with git pull

**Comment by santoshshanbhogue** [comment]
Also, I used the `pdep-tests.cti` file because I could not find a cti file for the h2o2 mech in the `test/data` directory. 
I tested the argv size on Win 10 64-bit which I run on a VM and for that GRI3.0 runs fine. Hence my initial guess of 80,000 chars. But I have lowered it to 32kB after your report with a Win 8

**Comment by santoshshanbhogue** [comment]
Okay, this is a new one. Passes on OS X and on Linux with Python 2 but fails linux on Python 3...

**Comment by speth** [comment]
The test failures are an annoyance of Python 3.2 and it's lack of support for the `u'foobar'` syntax for unicode strings. I think if you use `pjoin(self.test_work_dir, 'pdep_test.cti')` instead of just `'pdep-test.cti'` it will work, as the base version of this file does not use that syntax.

Please leave the submodules at their current commits. We don't want to necessarily be at the bleeding edge of every dependency, and we especially don't want to change versions of these dependencies with a release pending.

And yes, ultimately squashing the commits would be desirable.

File: interfaces/cython/cantera/test/test_convert.py [hunk 8]
```diff
@@ -459,3 +459,34 @@ def test_reaction_orders(self):
         self.assertNear(R.orders.get('OH'), 0.15)
         self.assertTrue(R.allow_negative_orders)
         self.assertNear(R.orders.get('H2'), -0.25)
+
+    #Here we are testing if passing a very long string will result in a Solution
```
Comment (speth) [inline interfaces/cython/cantera/test/test_convert.py]: There should be a space after the '#'.

File: interfaces/cython/cantera/test/test_convert.py [hunk 9]
```diff
@@ -459,3 +459,34 @@ def test_reaction_orders(self):
...
+    #object. This should result in a temp file creation in most OS's
+    def test_long_source_input(self):
+        convertMech(pjoin(self.test_data_dir, 'pdep-test.inp'),
```
Comment (speth) [inline interfaces/cython/cantera/test/test_convert.py]: Is there a reason for running `convertMech` here instead of just loading `pdep-test.cti` from `self.test_data_dir`?

File: interfaces/cython/cantera/test/test_convert.py [hunk 10]
```diff
@@ -459,3 +459,34 @@ def test_reaction_orders(self):
...
+                    outName=pjoin(self.test_work_dir, 'pdep_test.cti'), quiet=True)
+
+        gas = ct.Solution(pjoin(self.test_work_dir, 'pdep_test.cti'))
+
+        with open(pjoin(self.test_work_dir, 'pdep_test.cti'),'r') as file:
```
Comment (speth) [inline interfaces/cython/cantera/test/test_convert.py]: Please use a name which does not shadow the built-in function `file`.

File: src/base/ct2ctml.cpp [hunk 11]
```diff
@@ -79,6 +84,9 @@ void ct2ctml(const char* file, const int debug)
 static std::string call_ctml_writer(const std::string& text, bool isfile)
 {
     std::string file, arg;
+    bool temp_file_created=false;
```
Comment (speth) [inline src/base/ct2ctml.cpp]: missing spaces around the '='

File: src/base/ct2ctml.cpp [hunk 12]
```diff
@@ -87,6 +95,45 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+
+    // So, check the max size of a string that can be passed on the command line
+    // This is OS Specific. *nix systems have the sysconf() function that tells 
+    // us the largest argument we can pass. Since such a function does not exist
+    // for Windows, we set a safe limit of 32 kB
+#ifdef _WIN32
+    int max_argv_size = 32768;
+#endif
+
+#ifndef _WIN32
```
Comment (speth) [inline src/base/ct2ctml.cpp]: The `#ifdefs` can be merged using `#else`.

File: src/base/ct2ctml.cpp [hunk 13]
```diff
@@ -170,6 +217,17 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
         writelog(message.str());
     }
+
+    if (temp_file_created) {
+        //Means a temp file was created and has to be removed
+        bool temp_file_del_status = std::remove(temp_cti_file_name.c_str());
+        if (temp_file_del_status) {
+            std::string fileWarning = "WARNING: Error removing tmp file ";
+            fileWarning += temp_cti_file_name;
+            writelog(fileWarning);
```
Comment (speth) [inline src/base/ct2ctml.cpp]: Can be written as:
```c++
writelog("WARNING: Error removing tmp file '{}\n'", temp_cti_file_name);
```

File: src/base/ct2ctml.cpp [hunk 14]
```diff
@@ -170,6 +217,17 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
         message << "--------------- end of converter log ---------------\n";
         writelog(message.str());
     }
+
+    if (temp_file_created) {
+        //Means a temp file was created and has to be removed
```
Comment (speth) [inline src/base/ct2ctml.cpp]: Missing a space after the `//`

**Review by speth — CHANGES_REQUESTED** [review]

File: interfaces/cython/cantera/test/test_convert.py (hunk 8 above)
Comment (bryanwweber) [reply interfaces/cython/cantera/test/test_convert.py]: I'd actually prefer if these were a docstring of the function, instead of a comment above the function. Comments like this have a bad habit of being left behind if the function is moved.

File: src/base/ct2ctml.cpp (hunk 13 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Done

File: src/base/ct2ctml.cpp (hunk 14 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Corrected

File: src/base/ct2ctml.cpp (hunk 12 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Done

File: src/base/ct2ctml.cpp (hunk 11 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Corrected

File: interfaces/cython/cantera/test/test_convert.py (hunk 10 above)
Comment (santoshshanbhogue) [reply interfaces/cython/cantera/test/test_convert.py]: Corrected

File: interfaces/cython/cantera/test/test_convert.py (hunk 9 above)
Comment (santoshshanbhogue) [reply interfaces/cython/cantera/test/test_convert.py]: I am pretty sure I tried that and the test failed...

File: interfaces/cython/cantera/test/test_convert.py (hunk 8 above)
Comment (santoshshanbhogue) [reply interfaces/cython/cantera/test/test_convert.py]: Changed to doc-strings

File: interfaces/cython/cantera/test/test_convert.py (hunk 9 above)
Comment (santoshshanbhogue) [reply interfaces/cython/cantera/test/test_convert.py]: Because I don't have py3.2 (not supported by anaconda) I could not investigate this in detail, but this thing is counterintuitive. I mean, if anything, from the code upstream, there should be a copy in `self.test_work_dir` but I still get an error

Comment (speth) [reply interfaces/cython/cantera/test/test_convert.py]: The copy in the source directory should be in `self.test_data_dir`, not `self.test_work_dir`. A copy will exist in the work directory after other tests have run, but that depends on the order the tests run so shouldn't be counted on.

File: src/base/ct2ctml.cpp [hunk 15]
```diff
@@ -87,6 +93,45 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+
+    if (text.size() > max_argv_size - 500) {
+        // If the file is too big to be passed as a command line argument later
+        // in the file, then create a temporary file and execute this function
+        // as though an input file was specified as the source.
+        // We assume the text passed + 500 chars = total size of argv
+
+        ofstream temp_cti_file(temp_cti_file_name);
+            
+        if(temp_cti_file) {
```
Comment (speth) [inline src/base/ct2ctml.cpp]: missing space between `if` and `(`

File: src/base/ct2ctml.cpp [hunk 16]
```diff
@@ -87,6 +93,45 @@ static std::string call_ctml_writer(const std::string& text, bool isfile)
...
+            temp_cti_file << text;
+            file = temp_cti_file_name;
+            arg = "r'" + file + "'";
+            temp_file_created=true;
```
Comment (speth) [inline src/base/ct2ctml.cpp]: missing spaces around `=`.

**Review by speth — CHANGES_REQUESTED** [review]

File: src/base/ct2ctml.cpp (hunk 15 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Fixed

File: src/base/ct2ctml.cpp (hunk 16 above)
Comment (santoshshanbhogue) [reply src/base/ct2ctml.cpp]: Fixed

**Review by speth — APPROVED** [review]
