### PR TITLE
Some CLib/sourcegen/dotnet updates

### LINKED ISSUE #199: Deprecate clib 'xyz_newFromFile' from CLib
**Abstract**

Historically, `ThermoPhase` and `Kinetics` objects were instantiated in the clib API via `thermo_newFromFile` and `kin_newFromFile`. Cantera/cantera#1448 introduced access for `Solution` objects to clib, which can now be instantiated via `soln_newSolution` (and `soln_newInterface`). 

The historic instantiation route was important for the (now removed) legacy MATLAB toolbox, but is also still actively used in the Fortran and .NET interfaces. The main advantage of the new clib API functions is that they (i) allow for handling that is consistent with other parts of Cantera, and (ii) take care of all configuration steps.

**Motivation**

Describe the need for the proposed change:

* What problem is it trying to solve? ... make handling of `Solution` consistent across all interfaces
* Who is affected by the change? ... users of clib and derived APIs (e.g .NET)
* Why is this a good solution? ... removes legacy code

_Edit: Fortran is not affected by CLib, as it reimplements the `_newFromFile` routines separately._

**Possible Solutions**

Remove all instances of `thermo_newFromFile` and `kin_newFromFile`, and replace them by single call to `soln_newSolution`. Inclusion of surface kinetics in .NET requires resolution of Cantera/cantera#1450.

**References**

* Cantera/cantera#1448
* Cantera/cantera#1450
* Cantera/cantera#1670

### LINKED ISSUE #1450: sourcegen fails to process clib signature
**Problem description**

The following function signature causes a syntax error in sourcgen:

```c
int soln_newInterface(const char* infile, const char* name, int na, const int* adjacent);
```

**Steps to reproduce**

Add function with signature and run GH CI (see #1448).

Fwiw, a similar signature in `ctonedim.h` (which is currently not included in .NET) will presumably fail also:

```c
int sim1D_new(size_t nd, const int* domains);
```

**Behavior**

See [GH Action](https://github.com/Cantera/cantera/actions/runs/4332135791/jobs/7564643836)
<details>
  <summary>Relevant details from log</summary>

```
2023-03-04T18:21:24.9253446Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1031: Type expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:24.9383516Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1001: Identifier expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:24.9385819Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1026: ) expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:24.9387491Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1002: ; expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:24.9389312Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,113): error CS0145: A const field requires a value to be provided [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:24.9391610Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,121): error CS1003: Syntax error, ',' expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.0662852Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1031: Type expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.0667480Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1001: Identifier expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.0670849Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1026: ) expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.0673541Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1002: ; expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.0676471Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,113): error CS0145: A const field requires a value to be provided [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.0679731Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,121): error CS1003: Syntax error, ',' expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1429675Z 
2023-03-04T18:21:25.1430446Z Build FAILED.
2023-03-04T18:21:25.1432509Z 
2023-03-04T18:21:25.1433930Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1031: Type expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1436932Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1001: Identifier expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1439026Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1026: ) expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1441390Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1002: ; expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1443993Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,113): error CS0145: A const field requires a value to be provided [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1447134Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/netstandard2.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,121): error CS1003: Syntax error, ',' expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1449333Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1031: Type expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1451544Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1001: Identifier expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1453548Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1026: ) expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1455523Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,102): error CS1002: ; expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1457449Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,113): error CS0145: A const field requires a value to be provided [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1460279Z ##[error]/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/obj/Debug/net6.0/sourcegen/Interop.LibCantera.ct.h.g.cs(22,121): error CS1003: Syntax error, ',' expected [/home/runner/work/cantera/cantera/interfaces/dotnet/Cantera/Cantera.csproj]
2023-03-04T18:21:25.1461576Z     0 Warning(s)
2023-03-04T18:21:25.1461811Z     12 Error(s)
```
</details>

**System information**

- Cantera version: current `main`
- OS: GH Actions

**Additional context**

Bug emerged in #1448; as an aside, it would be terrific if the following could be updated:
https://github.com/Cantera/cantera/blob/c3eb05c84462d8ca8040a9fd29c72df8dcb83335/interfaces/sourcegen/README.md?plain=1#L36

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

This PR introduces combines some simple CLib updates with required fixes/updates in `sourcegen` and `dotnet` (with inconsequential changes in MATLAB)

- Remove most obsolete functions from CLib
- Fix unsupported crosswalks and improve formatting of generated code (sourcegen)
- Implement support for object handles returned from other objects (sourcegen)
- Eliminate `thermo_newFromFile` from CLib and .NET
- Switch `thermo_equilibrate` solver specification from magic number to string (consistent with Python and Fortran APIs)

The PR cherry-picks/reimplements some relevant commits from #1761, #1765 and #1770.

**If applicable, fill in the issue number this pull request is fixing**

Closes #1450, closes Cantera/enhancements#199 (.NET side)

**If applicable, provide an example illustrating new features this pull request is introducing**

N/A

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
:tada: ... figuring out .NET and sourcegen took a while, but this is now ready for a review.

File: interfaces/matlab_experimental/Base/ThermoPhase.m [hunk 1]
```diff
@@ -458,13 +458,10 @@ function display(tp)
...
-            %     solver using the element potential method will be used. If
-            %     solver = 1, a slower but more robust Gibbs minimization solver
-            %     will be used. If solver >= 2, a version of the VCS algorithm will
-            %     be used. If solver < 0 or is unspecified, the fast solver
-            %     will be tried first, then if it fails the Gibbs minimization solver
-            %     will be tried.
+            %     Specifies the equilibrium solver to use. Choices are
+            %     'element_potential' (fast solver using the element potential method),
+            %     'gibbs' (slower but more robust Gibbs minimization solver), 'vcs'
+            %     (VCS algorithm). For the default 'auto' setting, the fast solver
```
Comment (speth) [inline interfaces/matlab_experimental/Base/ThermoPhase.m:457]: This comment appears to end mid-sentence.

File: interfaces/sourcegen/sourcegen/_helpers.py [hunk 2]
```diff
@@ -13,6 +13,11 @@ def with_unpack_iter(cls: type) -> type:
     return cls
 
 
+def hanging_text(text: str, spaces: int) -> str:
+    ret = ("\n" + " "*spaces).join(text.split("\n"))
+    return "\n".join([_.rstrip() for _ in ret.split("\n")])
```
Comment (speth) [inline interfaces/sourcegen/sourcegen/_helpers.py]: `_` is usually only used for a variable that's explicitly being ignored. Here, I'd suggest just calling it `line`.

File: interfaces/dotnet/Cantera/src/Application.cs [hunk 3]
```diff
@@ -127,6 +127,7 @@ static void LogToConsole(object? sender, LogMessageEventArgs e)
     /// looking up the given name.
     /// </summary>
     public static ThermoPhase CreateThermoPhase(string filename,
-                                                string? phaseName = null) =>
-        new ThermoPhase(filename, phaseName);
+                                                string? phaseName = null,
+                                                string? transModel = null) =>
+        new ThermoPhase(filename, phaseName, transModel);
```
Comment (speth) [inline interfaces/dotnet/Cantera/src/Application.cs]: Until the .NET interface handles transport, I think it would be preferable to just initialize the `Solution` with a transport model of `none`. The idea of having the `ThermoPhase` constructor take a transport model argument is a bit confusing.

File: interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py [hunk 4]
```diff
@@ -197,32 +201,32 @@ def _write_file(self, filename: str, contents: str):
     def _scaffold_interop(self, header_file_path: Path, cs_funcs: List[CsFunc]):
         functions_text = "\n\n".join(map(self._get_interop_func_text, cs_funcs))
 
-        interop_text = normalize_indent(f"""
-            {normalize_indent(self._config.preamble)}
+        interop_text = textwrap.dedent(f"""
+            {hanging_text(self._config.preamble, 12)}
```
Comment (speth) [inline interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py:205]: Was `normalize_indent` failing somewhere? I looked at several of the `.g.cs` files and didn't spot any indentation changes as a result of changing this. Not having to specify the indent level was kind of nice.

**Review by speth — CHANGES_REQUESTED** [review]
This looks good to me. Just a couple of minor comments/questions. Also, can you rebase now that #1761 has been merged?

File: interfaces/dotnet/Cantera/src/Application.cs (hunk 3 above)
Comment (ischoegl) [reply interfaces/dotnet/Cantera/src/Application.cs]: Good point. I just did minimal replumbing here - I don't know enough about .NET to set up proper inheritance so we can instantiate a new `Solution` class that properly exposes all `ThermoPhase` methods (i.e. `Solution` needs to use multiple inheritance eventually, similar to what is done in Python and MATLAB).

File: interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py (hunk 4 above)
Comment (ischoegl) [reply interfaces/sourcegen/sourcegen/csharp/_CSharpSourceGenerator.py:205]: It was indeed misbehaving - while `normalize_indent` works for current content, I experimented with adding an actual `Solution` object (by creating a `Solution.g.cs` file), and it messed up formatting for `Interop.Handles.g.cs`. It's probably temporary anyways, as using a templating library like Jinja (per your suggestion in Cantera/enhancements#39) is likely a better option long term anyways. At least that's what I'm anticipating for the CLib work I started based on #1777.

**Comment by ischoegl** [comment]
@speth … thanks for your review! I rebased and addressed your comments, so it should be ready.

**Review by speth — APPROVED** [review]
Thanks, @ischoegl, this looks good to me.
