### PR TITLE
Fix consistency of IAPWS water EoS

### LINKED ISSUE #1315: Incorrect implementation of internal energy in WaterSSTP (liquid-water-IAPWS95)
**Problem description**

Calculations of the internal energy in the `WaterSSTP` class (YAML model name `liquid-water-IAPWS95`) give thermodynamically inconsistent results, compared to using the identity _u = h - P*v_ and _du/dT = c<sub>v</sub>_.

**Steps to reproduce**

```python
>>> s = ct.PureFluid('liquidvapor.yaml', 'liquid-water-IAPWS95')
>>> s.TP = 360, 101325

>>> s.enthalpy_mole
-281174223.8705604

>>> s.int_energy_mole + s.P * s.volume_mole
-101223397991.49594

>>> cv1 = s.cv_mole
>>> u1 = s.int_energy_mole
>>> dT = 0.01
>>> T = 360
>>> s.TD = T + dT, None
>>> cv2 = s.cv_mole
>>> u2 = s.int_energy_mole
>>> 0.5 * (cv1 + cv2)
69121.5991841279

>>> (u2 - u1)/dT
-256291643.85375977
```

**System information**

- Cantera version: 2.6.0 or `main` at 1ab81ace5

**Additional context**

This was discovered as part of https://github.com/Cantera/cantera/pull/1299, which implements https://github.com/Cantera/enhancements/issues/114.

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

- Fix dimensionalization of internal energy in `WaterSSTP` (was off by a factor of $T$)
- Correct conversion of nondimensional IAPWS equation of state to always be based on converting to a mass basis using the original defined value of $R$, then convert to a molar using the nominal molecular weight. This is the approach recommended by the IAPWS95 documentation.

A number of regression test values have changed, generally by factors on the order of $18.015268/18.015\approx 1.0000148$ which is the ratio of the molecular weight for water corresponding to the IAPWS95 value for $R$ and Cantera's molecular weight for water.

**If applicable, fill in the issue number this pull request is fixing**

Closes #1315

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by bryanwweber** [comment]
I have no idea what's causing the Windows 2019 failures, that wouldn't also be the same on Windows 2022. Setuptools did release a new version today that updates distutils, but that doesn't seem to be fixed by capping the version of `setuptools` in `pyproject.toml`. Anyhow, #1392 (although currently DO NOT MERGE) enables running everything from Windows 2022 by fixing SCons/scons#3664, and all the builds on Windows 2022 succeed, so 🤷

I was trying to test over in #1392 what happens when SCons is < 4.4.0 and you have the `msvc_toolset_version` variable present, but I'm getting a shell error or something, so the failures are unrelated.

Also, the example failure is due to a new warning from Matplotlib 3.6.0, and us setting the environment variable to treat warnings as errors. I fixed that in #991 by installing Matplotlib <3.6.0, but it may be worth restricting the environment variable to only treat Cantera-generated warnings as errors.

I'm also _very_ curious what you're working on that this was a priority to fix 😄 Unless it's just a general "well, I see how to fix this, so might as well" 😂

**Comment by speth** [comment]
> I'm also _very_ curious what you're working on that this was a priority to fix 😄 Unless it's just a general "well, I see how to fix this, so might as well" 😂

This isn't impacting anything specific I'm working on. Mostly just trying to make a little progress on the pile of bugs that were uncovered by #1299. I thought this was low-hanging fruit after figuring out the first one (scaling by R instead of RT), and then realized there were still some inexplicable discrepancies which were trickier to hunt down.

File: src/thermo/WaterPropsIAPWS.cpp [hunk 1]
```diff
@@ -334,8 +341,8 @@ doublereal WaterPropsIAPWS::psat(doublereal temperature, int waterState)
     for (int i = 0; i < 30; i++) {
         if (method == 1) {
             corr(temperature, p, densLiq, densGas, delGRT);
-            doublereal delV = M_water * (1.0/densLiq - 1.0/densGas);
-            dp = - delGRT * Rgas * temperature / delV;
+            doublereal delV = 1.0/densLiq - 1.0/densGas;
```
Comment (ischoegl) [inline src/thermo/WaterPropsIAPWS.cpp]: There are a  couple of `doublereal` instances in updated code

File: src/thermo/WaterPropsIAPWS.cpp [hunk 2]
```diff
@@ -144,10 +149,10 @@ doublereal WaterPropsIAPWS::density_const(doublereal pressure,
     if (rhoguess == -1.0) {
         if (phase != -1) {
             if (temperature > T_c) {
-                rhoguess = pressure * M_water / (Rgas * temperature);
+                rhoguess = pressure / (R_water * temperature);
```
Comment (ischoegl) [inline src/thermo/WaterPropsIAPWS.cpp:152]: There are a couple of conditions in the phase diagram that are apparently not be covered by current unit tests (this appears to be one of them). I have a faint recollection of the model not being usable in some regions, so this may not be worth addressing.

**Review by ischoegl — COMMENTED** [review]
@speth … thanks for taking on some of the bugs. The code changes make sense to me (caveat: I have not reviewed underlying equations and am relying on the thermodynamics-inspired tests that uncovered the bug in the first place); I only have minor comments.

**Comment by ischoegl** [comment]
> I have no idea what's causing the Windows 2019 failures, that wouldn't also be the same on Windows 2022. […]

The windows 2022 runner works a little different, as it builds in a conda environment.

**Comment by ischoegl** [comment]
> Also, the example failure is due to a new warning from Matplotlib 3.6.0, and us setting the environment variable to treat warnings as errors. I fixed that in #991 by installing Matplotlib <3.6.0, but it may be worth restricting the environment variable to only treat Cantera-generated warnings as errors.

One other alternative would be to create a pytest runner that handles the examples, so we get access to the warnings filters.

PS: neither of the issues are related to the bug fix in this PR …

File: src/thermo/WaterPropsIAPWS.cpp (hunk 2 above)
Comment (speth) [reply src/thermo/WaterPropsIAPWS.cpp:152]: That's correct -- the class's description says it is only meant for use in the liquid region, and I think there are a number of tricky things that would need to be dealt with to extend it beyond that, even though the underlying Helmholtz function is valid everywhere.

Beyond that, improving test coverage for this class was not a goal of this PR. I think the validity of this particular change is clear by inspection.

**Comment by speth** [comment]
I'm going to pass on trying to fix the pre-existing CI failures as part of this PR.

I briefly tried adjusting the `PYTHONWARNINGS` environment variable, and couldn't figure out how to get it to actually catch warnings from a specific module. I think `PYTHONWARNINGS=error:::cantera` should have been the right thing, but it didn't do anything when I deliberately triggered a warning from Cantera.

**Review by ischoegl — APPROVED** [review]
