### PR TITLE
Fix SolutionArray YAML overwrite / order components

### LINKED ISSUE #1772: 1D flame solution save() doesn't appear to overwrite, despite keyword being given
When calling `f.save('backup.yaml', name="solution", overwrite=True)`, the output file does not get overwritten. I may be using this feature incorrectly, but I thought the` overwrite=True `meant that the contents of the file will be overwritten by the current state of the flame.

Minimal example to showcase the issue is below. `backup.yaml ` should have the contents of the `backup_2.yaml`. Looking at the `mass-flux` entry shows that it has the values from `backup_1.yaml`. The first backup file (`backup_1.yaml`) is from the starting solution, and `backup_2.yaml` is the solution in the flame after increasing the boundary mass fluxes and re-calling `solve()`.

I may be using this feature incorrectly and I haven't had time to look at the save() method, but it felt like it might be a bug.

```
import cantera as ct

p = 101325 # pressure [Pascals]

fuel_inlet_temp= 800.0  # fuel inlet temperature [Kelvin]
oxidizer_inlet_temp= 711.0  # oxidizer inlet temperature [Kelvin]
fuel_mdot= 0.5 # kg/m^2/s
width= 50.0e-3 # Distance between inlets [m]

oxidizer_composition= 'O2:1.0'  # oxidizer composition (right)
fuel_composition= 'H2:1.0'  # fuel composition (left)

# Reaction mechanism
mechanism= 'h2o2.yaml'

gas = ct.Solution(mechanism)

gas.TPY = fuel_inlet_temp, p, oxidizer_composition
density_f = gas.density

gas.TPY = oxidizer_inlet_temp, p, oxidizer_composition
density_o = gas.density

#Unity Lewis number testing
gas.transport_model = 'unity-Lewis-number'

f = ct.CounterflowDiffusionFlame(gas, width=width)

f.set_refine_criteria(ratio=15, slope= 0.15, curve= 0.08, prune= 0.04)
#Set the state of the two inlets
f.fuel_inlet.mdot = fuel_mdot
f.fuel_inlet.X = fuel_composition
f.fuel_inlet.T = fuel_inlet_temp

#Create a guestimate for what the oxidizer mdot would be
f.oxidizer_inlet.mdot = (fuel_mdot / density_f) * density_o*4
f.oxidizer_inlet.X = oxidizer_composition
f.oxidizer_inlet.T = oxidizer_inlet_temp

# Generate initial condition
f.solve(auto=True, loglevel=6)
f.save('backup_1.yaml', name="solution", overwrite=True)
f.save('backup.yaml', name="solution", overwrite=True)

print('mdot info:')
print('Fuel mdot: ' + str(f.fuel_inlet.mdot))
print('Oxidizer mdot: ' + str(f.oxidizer_inlet.mdot))
print('BC State:')
print('Left U: ' + str(f.velocity[0]))
print('Right U: ' + str(f.velocity[-1]))


# Now change the conditions, re-run the flame and overwrite the solution
f.fuel_inlet.mdot = f.fuel_inlet.mdot*2
f.oxidizer_inlet.mdot = f.oxidizer_inlet.mdot*2
f.solve()
f.save('backup_2.yaml', name="solution", overwrite=True)
f.save('backup.yaml', name="solution", overwrite=True)

```

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Fix issue where YAML `SolutionArray` output entries were not correctly overwritten 
- Order YAML output based on components

**If applicable, fill in the issue number this pull request is fixing**

Closes #1772

**If applicable, provide an example illustrating new features this pull request is introducing**

`SolutionArray` output respects `component` order (previously the order could be scrambled, especially when overwriting):
```YAML
arr:
  generator: Cantera SolutionArray
  cantera-version: 3.1.0a3
  git-commit: "'9a730d862'"
  date: Wed Aug 14 20:13:21 2024
  data:
    size: 3
    basis: mass
    components: [T, D, H2, H, O, O2, OH, H2O, HO2, H2O2, AR, N2, spam]
    T: [3185.196897445414, 3185.196897445414, 3185.196897445414]
    D: [0.1383648238149952, 0.1383648238149952, 0.1383648238149952]
    H2: [7.461973701196079e-03, 7.461973701196079e-03, 7.461973701196079e-03]
    H: [2.754568580688943e-03, 2.754568580688943e-03, 2.754568580688943e-03]
    O: [0.05418042113328690, 0.05418042113328690, 0.05418042113328690]
    O2: [0.3131633165600913, 0.3131633165600913, 0.3131633165600913]
    OH: [0.1300522902586164, 0.1300522902586164, 0.1300522902586164]
    H2O: [0.4921274938532937, 0.4921274938532937, 0.4921274938532937]
    HO2: [2.473953814465240e-04, 2.473953814465240e-04, 2.473953814465240e-04]
    H2O2: [1.254053138021190e-05, 1.254053138021190e-05, 1.254053138021190e-05]
    AR: [0.0, 0.0, 0.0]
    N2: [0.0, 0.0, 0.0]
    spam: [eggs, eggs, eggs]
```

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Review by bryanwweber — APPROVED** [review]
Thanks! This looks good to me!

File: src/base/SolutionArray.cpp [hunk 1]
```diff
@@ -1273,6 +1277,23 @@ void SolutionArray::writeEntry(AnyMap& root, const string& name, const string& s
...
+        }
+    }
+
+    const vector<string> header = { "type", "size", "basis", "components" };
+    for (auto entry : boost::adaptors::reverse(header)) {
+        ordering.push_back({"head", entry});
+    }
+
+    data["__type__"] = "SolutionArray";
+    AnyMap::addOrderingRules("SolutionArray", ordering);
```
Comment (speth) [inline src/base/SolutionArray.cpp:1295]: This is problematic -- the `addOrderingRules` method is meant to be called exactly once for a given "type", hence why it's a static method. This usage will result in a memory leak as duplicate fields will be added to the ordering rules every time this method is called.

 The mechanism we currently have for setting order for a dynamic set of keys is through the `setLoc` method, though that may be an imperfect fit here.

Comment (bryanwweber) [reply src/base/SolutionArray.cpp:1295]: Sorry Ray! Thanks for catching this

Comment (ischoegl) [reply src/base/SolutionArray.cpp:1295]: @speth ... likewise thanks for catching. Hadn't used that feature before - will create an issue.
