### PR TITLE
Fix open WaterPropsIAPWS issues / add WaterSSTP as alternative Water backend

### LINKED ISSUE #577: PDSS Water calculation error at 287.9K
### Cantera version
2.4.0
### Operating System
Windows 7 (Linux also tested)
### Python/MATLAB version
3.6.5 (Anaconda distribution)

### Description of the problem
When trying to use the PDSS module for non-ideal mixtures, the calculation of the water density crashes at exactly 287.9 K regardless of the pressure used. Other temperatures work just fine.

A small model to check this is to get the xml file for the solution of NaCl from the repository:
[https://github.com/Cantera/cantera/blob/master/test_problems/VCSnonideal/NaCl_equil/HMW_NaCl.xml](url)
and changing a few lines of code (18-23) to disable the solute molalities. We change from:
```
      <soluteMolalities>
             Na+:6.0954
             Cl-:6.0954
             H+:2.1628E-9
             OH-:1.3977E-6
      </soluteMolalities>
```
to
```
      <!--soluteMolalities>
             Na+:6.0954
             Cl-:6.0954
             H+:2.1628E-9
             OH-:1.3977E-6
      </soluteMolalities-->
```

and we run this small code under jupyter notebook:
````
import numpy as np
import cantera as ct

liq = ct.Solution('HMW_NaCl.xml', 'NaCl_electrolyte') 
liq.TP = 287.9, 1e5
print(liq.report())
````
Then, the following error occurs:

> CanteraError                              Traceback (most recent call last)
> <ipython-input-9-4c3c5efe80a2> in <module>()
>       1 liq = ct.Solution('HMW_NaCl.xml', 'NaCl_electrolyte')
> ----> 2 liq.TP = 287.9, 1e5
>       3 print(liq.report())
> 
> interfaces\cython\cantera\thermo.pyx in cantera._cantera.ThermoPhase.TP.__set__()
> 
> CanteraError: 
> ***********************************************************************
> CanteraError thrown by WaterPropsIAPWS::corr:
> Error occurred trying to find liquid density at (T,P) = 287.9  1678.12
> ***********************************************************************
> 
We tried to track the function which is causing the error by comparing inputs and outputs of the failed iteration (which would work if we call the function separately). We tracked the error to the following files/classes/functions:
1)WaterPropsIAPWS.cpp -> void WaterPropsIAPWS::corr ->densLiq = _density_(temperature, pressure, WATER_LIQUID, densLiq)
2)WaterPropsIAPWS.cpp -> doublereal WaterPropsIAPWS::density ->_m_phi.dfind_(p_red, tau, deltaGuess)
3)WaterPropsIAPWSphi.cpp->doublereal WaterPropsIAPWSphi::dfind(doublereal p_red, doublereal tau, doublereal deltaGuess)

And there we did not go deeper. It would give no convergence when called with the previous code, but it would work if we did the calculation alone with the supposed input data of the corresponding failed iteration.

For more data or questions, we would be glad to give/answer them, respectively.

### LINKED ISSUE #646: Improve WaterSSTP helper class documentation
### Cantera version
2.4.0

### Operating System
All

### Python/MATLAB version
All

### Actual Behavior
At present, there are a number of classes in the `thermo` directory which provide supporting calculations to the `WaterSSTP` ThermoPhase class.  These classes:

- `WaterProps`
- `WaterPropsIAPWS`
- `WaterPropsIAPWSphi`

Are not instantiatable on their own, but provide low-level functionality necessary for property calculations in the aforementioned `WaterSSTP` class.

This aspect of these three files should be stated more explicitly, near the top of each of the relefvant `.cpp` and `.h` files, so that interested users can more easily locate the relevant thermoPhase class, and avoid wasting time trying to understand these helper classes, which are most likely not what they are interested in (directly) implementing.

### LINKED ISSUE #721: Setting the state of PureLiquidWater with T,P raises a CanteraError
### Cantera version
2.5.0a3

### Operating System
macOS, but probably not specific

### Python/MATLAB version
3.7, but probably not specific

### Expected Behavior
Setting the state of `PureLiquidWater` with T, P works when going from gas to liquid states

### Actual Behavior
Setting the state of `PureLiquidWater` with T, P raises a `CanteraError` when going from gas to liquid states

### Steps to reproduce
```In [1]: import cantera as ct

In [2]: water = ct.PureFluid('/Users/bryan/GitHub/cantera/build/python/cantera/test/data/liquid-water.xml')

In [3]: water.TP
Out[3]: (300.0, 101325.00046662119)

In [4]: water.TP = 2000, ct.one_atm

In [5]: water.TP = 298, ct.one_atm
---------------------------------------------------------------------------
CanteraError                              Traceback (most recent call last)
<ipython-input-5-c5704cc5079b> in <module>
----> 1 water.TP = 298, ct.one_atm

~/GitHub/cantera/interfaces/cython/cantera/thermo.pyx in cantera._cantera.ThermoPhase.TP.__set__()
   1030             T = values[0] if values[0] is not None else self.T
   1031             P = values[1] if values[1] is not None else self.P
-> 1032             self.thermo.setState_TP(T, P)
   1033
   1034     property TPX:

CanteraError:
***********************************************************************
CanteraError thrown by setPressure:
error: dens = 0.109769, rc = 322, waterState = 0
***********************************************************************

In [6]: water.density
Out[6]: 0.10976927970023702

In [7]: water.critical_density
Out[7]: 322.0

In [8]: water.TP
Out[8]: (298.0, 14910.063602909962)

In [9]: water.TP = 2000, ct.one_atm

In [10]: water.density
Out[10]: 0.10976927970023702

In [11]: water.TP
Out[11]: (2000.0, 101325.00000000144)
```

(I modified the function to produce more useful error output)

The definition of the relevant function is:

https://github.com/Cantera/cantera/blob/fe7be79552433c3779ffbd5b018a493114fffdbc/src/thermo/WaterSSTP.cpp#L267-L281

where `WATER_GAS` is defined as `0`.

One possible solution is to check the value of the pressure passed in relative to the saturation pressure at the system temperature and determine the guessed phase that way, depending on how the saturation pressure is defined.

### PR DESCRIPTION
**Pull request by ischoegl**
There are some open issues with `WaterPropsIAWSS`; adding access to `WaterSSTP` via an alternative backend to the `Water` wrapper facilitates interactions with underlying C++ objects.

The `WaterPropsIAPWS` helper classes implement a highly accurate Industrial Formulation for the equation of state for pure water, which is currently used by `WaterSSTP` and `PDSS_Water` classes. The former is loadable via YAML as part of the `ThermoFactory` approach, but only implements the liquid portion. Per @bryanwweber ’s observations (in #721):

> The `WaterSSTP` phase, as implied by the name in the XML file (`PureLiquidWater`), is intended to represent only the liquid states of water. It is based on the `WaterPropsIAPWS` class, which can represent liquid to vapor states, but the `WaterSSTP` class is used in a few places where liquids only are the assumption. Hypothetically, a different class that implements the full behavior of the EOS could be written using `WaterPropsIAPWS`, but this ain't it.

The current loader is cumbersome and involves a custom input file, e.g.
```
water = ct.PureFluid('test/data/liquid-water.xml')
```
from within the cantera source folder (see #721), i.e. suitable input files aren’t distributed outside the test suite. The proposed change enables loading of the `WaterSSTP` model via
```
water = ct.Water(backend='IAPWS95')
```
while the existing behavior remains the default. Beyond, this PR also fixes some open issues.

**Changes proposed in this pull request**

- Add phase using `liquid-water-IAPWS95` to `liquidvapor.yaml`
- Add an alternative `backend=iawps95` switch to the existing Python `Water` interface to facilitate usage to the `liquid-water-IAPWS95` thermo model; the existing behavior corresponds to `backend=default`
- Update Python docstrings with information already available in MATLAB wrapper classes
- Clarify role of `WaterSSTP` helper classes (based on @24sharkS 's solution in #809)
- Ensure that state of `WaterSSTP` remains liquid (or supercritical) - this checks the classical criterion for saturated conditions.

**If applicable, fill in the issue number this pull request is fixing**

Fixes #577, fixes #646, fixes #721

**Related Issues**

Cantera/enhancements#6, #809 

**Checklist**

- [x] There is a clear use-case for this code change
- [x] The commit message has a short title & references relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] The pull request is ready for review

**Other thoughts**

1. Short-term, this fixes some issues and (hopefully) helps clarify the IAPWS formulation.
2. Long-term, it may make sense to add [CoolProp](https://github.com/CoolProp/CoolProp) objects as additional alternative `backend` s for existing wrapper objects, see Cantera/enhancements#35.

### CODE REVIEW

**Comment by ischoegl** [comment]
**Other thoughts:** it may make sense to raise an error for `Q` (vapor fraction), unless `WaterSSTP::m_allowGasPhase` is `True`.

File: include/cantera/thermo/WaterSSTP.h [hunk 1]
```diff
@@ -140,9 +140,11 @@ class WaterSSTP : public SingleSpeciesTP
     explicit WaterSSTP(XML_Node& phaseRef, const std::string& id = "");
 
     virtual std::string type() const {
-        return "Water";
+        return "WaterSSTP";
```
Comment (speth) [inline include/cantera/thermo/WaterSSTP.h]: If anything, this should be `liquid-water-IAPWS95`, no? I've been trying to (slowly) kill off these obscure initialisms, especially in the most user-accessible parts of the code.

File: include/cantera/thermo/WaterProps.h [hunk 2]
```diff
@@ -83,6 +83,9 @@ class PDSS_Water;
 //! The WaterProps class is used to house several approximation routines for
 //! properties of water.
 /*!
+ * This is a helper class for WaterSSTP and is not instantiable on its own
+ * (see \ref thermoprops and class \link Cantera::WaterSSTP WaterSSTP\endlink).
```
Comment (speth) [inline include/cantera/thermo/WaterProps.h]: Technically, you can instantiate these classes on their own. I think the confusion is more about the fact that they aren't instances of `ThermoPhase`. So maybe something like "not instantiable as a ThermoPhase object on its own"?

File: interfaces/cython/cantera/liquidvapor.py [hunk 3]
```diff
@@ -4,47 +4,180 @@
...
+    which can be used in the liquid, vapor, saturated liquid/vapor, and
+    supercritical regions of the phase diagram.
+
+    The ``iapws95`` backend implements an IAPWS (International Association for
+    the Properties of Water and Steam) formulation for thermodynamic properties
+    taken from
+
+        J. V. Sengers, J. T. R. Watson, *Improved International Formulations for
+        the Viscosity and Thermal Conductivity of Water Substance,* J. Phys.
+        Chem. Ref. Data, 15, 1291, 1986.
```
Comment (speth) [inline interfaces/cython/cantera/liquidvapor.py:38]: I don't think this is the correct reference for the thermodynamic properties -- as the paper title says, this for the viscosity and thermal conductivity. The one that should be listed here is the Wagner and Pruss paper (which is what you added to `liquidvapor.yaml`).

File: interfaces/cython/cantera/liquidvapor.py [hunk 4]
```diff
@@ -4,47 +4,180 @@
...
+
+    which currently only implements liquid and supercritical regions.
+
+    For more details, see classes Cantera::PureFluid, tpx::water,
+    Cantera::WaterSSTP and Cantera::WaterTransport in the Cantera C++ source
```
Comment (speth) [inline interfaces/cython/cantera/liquidvapor.py]: To generate links to the C++ documentation, write these as ``` :ct:`PureFluid` ``` etc. I'm not actually sure what to do about `tpx::water`, though.

File: interfaces/cython/cantera/liquidvapor.py [hunk 5]
```diff
@@ -4,47 +4,180 @@
 from . import PureFluid, _cantera
 
 
-def Water():
+def Water(backend='default'):
```
Comment (speth) [inline interfaces/cython/cantera/liquidvapor.py]: Perhaps `Reynolds` would be a better name for this backend?

File: include/cantera/thermo/WaterSSTP.h [hunk 6]
```diff
@@ -238,6 +240,9 @@ class WaterSSTP : public SingleSpeciesTP
         return m_waterProps.get();
     }
 
+    //! Switch that enables calculations in the gas phase
+    void allowGasPhase(bool flag) { m_allowGasPhase = flag; }
```
Comment (speth) [inline include/cantera/thermo/WaterSSTP.h]: I'm worried about the addition of this member function, because it implies that the `m_allowGasPhase` flag actually works, which I think isn't true. As an example, if this flag is set to `true`, setting T and P to (300, 101325) and then (400, 101325) leads to a density of 937.411 kg/m^3, which is clearly wrong.

**Review by speth — COMMENTED** [review]
While I appreciate some of the improvements here, and think they're worth including, I am concerned about making the current implementation of the IAPWS95 equation of state more user accessible because it is so incomplete when it comes to the two phase and vapor regions. Without being able to handle those portions of the phase diagram, I don't think it makes sense to include a phase definition in `liquidvapor.yaml`.

And given the prospect of using CoolProp (Cantera/enhancements#35), I'm not sure it would be worth extending the implementation of this phase definition to handle those regions.

File: include/cantera/thermo/WaterProps.h (hunk 2 above)
Comment (ischoegl) [reply include/cantera/thermo/WaterProps.h]: I mainly copied from #809 here (and elsewhere) but will update.

File: include/cantera/thermo/WaterSSTP.h (hunk 6 above)
Comment (ischoegl) [reply include/cantera/thermo/WaterSSTP.h]: I really didn’t want to implement this either, but an example in the test suite (`test_problems/cathermo/testWaterTP/testWaterSSTP.cpp`) depends on it. I’d certainly refuse to add it to Python ...

File: include/cantera/thermo/WaterSSTP.h (hunk 1 above)
Comment (ischoegl) [reply include/cantera/thermo/WaterSSTP.h]: I'm very much in favor of going away from acronyms also, although I'm not sure that this clearly differentiates from `PDSS_Water` (the `TP` portion did point at one feature of this class that makes it suited for the two-phase region).

Going forward, I do not know the prospects of `iawps-95` - if it's useful enough to keep around I hope to see it as a more accurate and fully featured implementation than `reynolds`, - in which case the `liquid` is somewhat limiting. Since the `TP` approach pre-empts extensions to two-phase it will require a different approach with a different class heritage. So I am adopting the suggestion, as this is consistent with the label used for the thermo factory.

File: interfaces/cython/cantera/liquidvapor.py (hunk 3 above)
Comment (ischoegl) [reply interfaces/cython/cantera/liquidvapor.py:38]: Correct. Apparently made a mistake when copy-pasting (I initially had a separate class for IAPWS).

File: interfaces/cython/cantera/liquidvapor.py (hunk 4 above)
Comment (ischoegl) [reply interfaces/cython/cantera/liquidvapor.py]: Updated, but left the `tpx::water` etc for lack of better options.

File: interfaces/cython/cantera/liquidvapor.py (hunk 5 above)
Comment (ischoegl) [reply interfaces/cython/cantera/liquidvapor.py:7]: (although opting for lower-case)

File: include/cantera/thermo/WaterProps.h (hunk 2 above)
Comment (ischoegl) [reply include/cantera/thermo/WaterProps.h]: Updated this to
```
 * This is a helper class for WaterSSTP and PDSS_Water and does not constitute
 * a complete implementation of a thermo phase by itself (see \ref thermoprops
 * and classes \link Cantera::WaterSSTP WaterSSTP\endlink and
 * \link Cantera::PDSS_Water PDSS_Water\endlink).
```
to reflect that `WaterSSTP` is not the only class using this.

File: include/cantera/thermo/WaterSSTP.h (hunk 6 above)
Comment (ischoegl) [reply include/cantera/thermo/WaterSSTP.h]: Beyond adding a longer docstring:
```
    //! Switch that enables calculations in the gas phase
    /**
     *  Since this phase represents a liquid (or supercritical) phase, it is an
     *  error to return a gas-phase answer. The sole intended use for this
     *  member function is to check the thermodynamic consistency of the
     *  underlying WaterProps class with ideal-gas thermo functions.
     */
    void allowGasPhase(bool flag) { m_allowGasPhase = flag; }
```
 I don't have a good alternative idea, as I really do not want to break the test suite (which really targets the implementation of the underlying `WaterProps` class).

**Comment by ischoegl** [comment]
@speth ... thank you for the review! I believe all is taken care of ... see 1069692 

> While I appreciate some of the improvements here, and think they're worth including, I am concerned about making the current implementation of the IAPWS95 equation of state more user accessible because it is so incomplete when it comes to the two phase and vapor regions. Without being able to handle those portions of the phase diagram, I don't think it makes sense to include a phase definition in liquidvapor.yaml.

With the changes of this PR, appropriate errors are raised if a user attempts to set a state outside of the permissible region (and it's only possible to deactivate in C++, where caveats are now clearly stated). Since `IAPWS` is presumably more accurate, I believe it's in the interest of users to be able to access what's already implemented. Perhaps someone will find this of use and take initiative to expand further: the Python front-end is certainly a more convenient starting point.

> And given the prospect of using CoolProp (Cantera/enhancements#35), I'm not sure it would be worth extending the implementation of this phase definition to handle those regions.

I personally agree, but am not sure what will become of `PDSS_Water` (as much of the code is shared with `WaterSSTP`, the Python access would still be useful). My obvious recommendation would be to simply allow for different backends for all wrappers once the `CoolProp` connection is implemented.

**Comment by ischoegl** [comment]
A small change takes care of #577. The updated Python `Water` wrapper was convenient to track this issue down :wink:

**Comment by ischoegl** [comment]
Inactive for 3 months - closing.

**Comment by ischoegl** [comment]
Based on a UG post there may be value in wrapping this up after all

**Comment by ischoegl** [comment]
@bryanwweber and @speth ... let me know if this is of interest for 2.5 (I believe all feedback is taken care of). It’s the last of my pending PRs.

**Comment by ischoegl** [comment]
.... Triggering CI

File: include/cantera/thermo/WaterSSTP.h (hunk 6 above)
Comment (speth) [reply include/cantera/thermo/WaterSSTP.h]: Taking a second look at this, I think I'd settle for naming this function `_allowGasPhase`, using the leading underscore to indicate that this function is in some sense internal and not to be used.

**Review by speth — CHANGES_REQUESTED** [review]
Overall, I think this looks pretty good. I'm happy to merge this pending my one suggestion below.

File: include/cantera/thermo/WaterSSTP.h (hunk 6 above)
Comment (ischoegl) [reply include/cantera/thermo/WaterSSTP.h]: done!

**Review by speth — APPROVED** [review]

**Comment by ischoegl** [comment]
@speth ... thanks for the review (and the ones that came before) as well as all the work towards 2.5 ...

**Comment by speth** [comment]
No problem. As you can tell from some of the recent activity, @bryanwweber and I are just working out the last few things that need to be taken care of for the 2.5.0 release.
