### PR TITLE
`ck2yaml` Strip optional +M from PLOG reactions

### LINKED ISSUE #1165: ck2yaml crashes when parsing a third body reaction with PLOG
**Problem description**

ck2yaml crashes when parsing a third body reaction with PLOG. 
I've tried searching open/closed issues for this, but either I'm searching with the wrong keywords or this is a new issue. 

**Steps to reproduce**

1. Download AramcoMech 3.0 CHEMKIN files (zip file in [supplementary materials](https://www.sciencedirect.com/science/article/pii/S0010218018303675?via%3Dihub#sec0028))
2. Run `ck2yaml --input="AramcoMech 3.0.MECH" --thermo="AramcoMech 3.0.THERM" --transport="AramcoMech 3.0.TRAN"`
3. See error:

```
Error reading reaction starting on line 5544:
"""
C4H6+M<=>C2H3+C2H3+M                                         +1.3489600E+072 -1.6550000E+001 +1.4340000E+005
PLOG /                                       +3.9473700E-002 +2.3442300E+074 -1.7690000E+001 +1.4080000E+005 /
PLOG /                                       +7.8947400E-002 +2.2908700E+074 -1.7510000E+001 +1.4210000E+005 /
PLOG /                                       +1.5789500E-001 +4.3651600E+073 -1.7130000E+001 +1.4290000E+005 /
PLOG /                                       +3.1578900E-001 +1.3489600E+072 -1.6550000E+001 +1.4340000E+005 /
"""

ERROR: Unable to parse 'AramcoMech 3.0.MECH' near line 5544:
Reaction C4H6+M<=>C2H3+C2H3+M
 contains parameters for more than one reaction type.
```

**System information**

- Cantera version: 2.6.0a3
- OS: Windows 10
- Python version: 3.8.10

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Strip 'decorative' `M` from PLOG reaction defined in CHEMKIN (`ck2yaml`)
- Raise exception for superfluous `M` in YAML
- Add unit tests

`cti2yaml` and `ctml2yaml` do not require handling as the legacy formats do not include the optional `+M`. See also: f8c38150d6e129f4f3c1e26ba8103ce2c377a625 (handling of optional `(+M)` for Chebyshev)

**If applicable, fill in the issue number this pull request is fixing**

Closes #1165

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

File: src/kinetics/Reaction.cpp [hunk 1]
```diff
@@ -256,6 +256,11 @@ void Reaction::setRate(shared_ptr<ReactionRate> rate)
         reactants.erase("(+M)");
         products.erase("(+M)");
     }
+
+    if (reactants.count("M") && std::dynamic_pointer_cast<PlogRate>(m_rate)) {
+        throw InputFileError("Reaction::setRate", input, "Invalid Syntax: found "
+            "superfluous 'M' in pressure-dependent-Arrhenius reaction.");
```
Comment (speth) [inline src/kinetics/Reaction.cpp]: This is a bit of a nitpick, but I would argue that this is not a syntax error -- this is still a parsable reaction expression. I'd suggest just starting the error message with "Found superfluous...".

**Review by speth — CHANGES_REQUESTED** [review]
Looks good to me. Just one very minor nitpick.

**Review by speth — APPROVED** [review]
Thanks, @ischoegl, this looks good.
