### PR TITLE
Reproducible names for zeroD objects

### LINKED ISSUE #1764: Broken name attribute for reactor `Wall` objects
**Problem description**

Reactor `Wall` objects do have documented name attributes, but they are not retrievable.

**Steps to reproduce**

On IPython, run
```
In [1]: %run samples/python/reactors/piston.py
time [s]    T1 [K]      T2 [K]      V1 [m^3]    V2 [m^3]    V1+V2 [m^3]  X(CO)
     0.004       900.0    900.0015         0.5         0.1         0.6      0.2853
[...]
     0.200      2319.4   2774.2346      0.4917      0.1083         0.6     0.03109
To view a plot of these results, run this script with the option --plot

In [2]: w.name  # 'w' is a variable holding a 'Wall' object
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 w.name

AttributeError: 'cantera.reactor.Wall' object has no attribute 'name'
```

**Behavior**

Although `name` is a documented parameter, it cannot be retrieved (even if no name is provided, a default name should be generated automatically).
https://github.com/Cantera/cantera/blob/32a8d4b8fde73e52ee7aa73dfd650bce68e46a03/interfaces/cython/cantera/reactor.pyx#L947-L972

**System information**

- Cantera version: current `main`
- OS: macOS
- Python/MATLAB/other software versions: Python 3.11

**Additional context**

Originally reported on UG, [see post](https://groups.google.com/g/cantera-users/c/V8T2Y2R1jhc)

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

This PR seeks to implement reproducible (and unique) reactor, flow device and wall names in the C++ layer, which was previously only handled by the Python API. Rather than auto-creating unique names based on the number of certain object types created within a Cantera session, this PR switches to an approach that creates names dependent on `ReactorNet` objects, which guarantees that reproducible auto-generated names are attached to various `zeroD` objects.

- Ensure that reactors, walls and connectors have names that are stored in C++ layer
- Names are generated automatically if none are provided
- Names should be reproducible for a given `ReactorNet`, which is important for serialization (e.g. Cantera/enhancements#206)
- Update API's for Python and MATLAB
- ~Remove deprecated functions from `clib` (in anticipation of Cantera/enhancements#211)~

**If applicable, fill in the issue number this pull request is fixing**

Closes #1764

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
The PR goes somewhat beyond fixing #1764, as it pushes all names to C++ and exposes them to MATLAB as well. It should be ready for a review.

**Comment by ischoegl** [comment]
Minor cleanup. As an aside, I believe we should deprecate creation of empty `Wall` and `FlowDevice` objects as well (similar to the recent decision about empty `Reactor` objects); Python doesn't allow for it (and this PR removes support from MATLAB), so we should not support it at the C++ level either. A corresponding change goes beyond the scope of this PR.

**Comment by ischoegl** [comment]
Fixed Python docstrings. _Edit: another force-push to fix a new CI error. Not anticipating any other changes beyond 882182d before a review._

**Comment by ischoegl** [comment]
Rebased, with commits removing obsolete CLib methods moved to #1773.

File: include/cantera/zeroD/FlowDevice.h [hunk 1]
```diff
@@ -115,6 +133,9 @@ class FlowDevice
     }
 
 protected:
+    string m_name = "";  //!< Flow device name.
```
Comment (speth) [inline include/cantera/zeroD/FlowDevice.h]: Since the one and only constructor sets a value for `m_name`, there's no need set it here. Also, the default value for a `std::string` is the empty string anyway.

File: include/cantera/zeroD/ReactorBase.h [hunk 2]
```diff
@@ -76,6 +76,9 @@ class ReactorBase
         m_name = name;
     }
 
+    //! Set the default name of a reactor. Returns `false` if it was previously set.
+    bool setDefaultName(const string& typ, int count);
```
Comment (speth) [inline include/cantera/zeroD/ReactorBase.h]: Does this method need to take `typ` as an argument? It could just call `type()` internally instead.

File: src/zeroD/ReactorBase.cpp [hunk 3]
```diff
@@ -31,6 +37,18 @@ ReactorBase::~ReactorBase()
...
+bool ReactorBase::setDefaultName(const string& typ, int count)
+{
+    if (m_defaultNameSet) {
+        return false;
+    }
+    m_defaultNameSet = true;
+    if (m_name == "(none)" || m_name == "") {
+        m_name = fmt::format("{}_{}", typ, count);
+    }
+    return true;
```
Comment (speth) [inline src/zeroD/ReactorBase.cpp]: The logic between this and `ReactorNet::updateNames` results in the count being incremented even for reactors that already have names. Is this the intended behavior?

File: src/zeroD/ReactorNet.cpp [hunk 4]
```diff
@@ -305,6 +306,72 @@ void ReactorNet::addReactor(Reactor& r)
...
+        auto inType = in.type();
+        if (in.setDefaultName(inType, m_count[inType])) {
+            m_count[inType]++;
+        }
+        if (in.in().type() == "Reservoir") {
+            auto& res = in.in();
+            auto resType = res.type();
+            res.setDefaultName(resType, m_count[resType]);
+            m_count[resType]++;
+        }
```
Comment (speth) [inline src/zeroD/ReactorNet.cpp]: One possibility for simplifying this somewhat repetitious pattern would be to have `setDefaultName` take the `m_count` map as the one and only argument, and be responsible for updating the count for that reactor/wall/etc. type.

File: src/zeroD/ReactorNet.cpp [hunk 5]
```diff
@@ -305,6 +306,72 @@ void ReactorNet::addReactor(Reactor& r)
...
+    }
+
+    for (size_t i=0; i<r.nSurfs(); i++) {
+        auto surf = r.surface(i);
+        auto surfType = surf->type();
+        if (surf->name() == "(none)" || surf->name() == "") {
+            surf->setName(fmt::format("{}_{}", surfType, m_count[surfType]));
+        }
+        m_count[surfType]++;
+    }
```
Comment (speth) [inline src/zeroD/ReactorNet.cpp]: Should `ReactorSurface` objects get the same treatment of having a `setDefaultName` method?

File: test/clib/test_ctreactor.cpp [hunk 6]
```diff
@@ -13,6 +13,15 @@ TEST(ctreactor, reactor_soln)
     int sol = soln_newSolution("gri30.yaml", "gri30", "none");
     int reactor = reactor_new3("IdealGasReactor", sol, "test");
     ASSERT_EQ(reactor, 0);
+
+    int ret = reactor_setName(reactor, "spam");
+    ASSERT_EQ(ret, 0);
+    int buflen = reactor_name(reactor, 0, 0);
+    char* buf = new char[buflen];
```
Comment (speth) [inline test/clib/test_ctreactor.cpp]: Instead of `new` and `delete`, you can use `vector<char> buf(buflen)`. I think there are one or two other `clib` tests where that's what we use.

File: test/python/test_reactor.py [hunk 7]
```diff
@@ -236,10 +236,34 @@ def test_maxsteps(self):
...
+        assert self.r1.name.startswith(f"{self.r1.type}_")  # default name
+        assert self.r2.name.startswith(f"{self.r2.type}_")  # default name
+        assert self.w.type == "Wall"
+        assert self.w.name.startswith("Wall_")  # default name
+        self.w.name = "name-of-wall"
+        assert self.w.name == "name-of-wall"
+
+    def test_wall_type2(self):
+        self.make_reactors(n_reactors=1)
+        res = ct.Reservoir(self.gas1)  # warning raised from C++ code
```
Comment (speth) [inline test/python/test_reactor.py]: What warning, and why?

**Review by speth — CHANGES_REQUESTED** [review]
Thanks, @ischoegl. Moving this naming process to the C++ level certainly makes sense. Just a few comments on the implementation.

File: src/zeroD/ReactorBase.cpp (hunk 3 above)
Comment (ischoegl) [reply src/zeroD/ReactorBase.cpp]: This is indeed the intended behavior.

File: test/clib/test_ctreactor.cpp (hunk 6 above)
Comment (ischoegl) [reply test/clib/test_ctreactor.cpp]: :+1: There are quite a few instances.

File: src/zeroD/ReactorNet.cpp (hunk 4 above)
Comment (ischoegl) [reply src/zeroD/ReactorNet.cpp]: :tada: Great suggestion!

File: include/cantera/zeroD/ReactorBase.h (hunk 2 above)
Comment (ischoegl) [reply include/cantera/zeroD/ReactorBase.h]: Per your other suggestion using the map as argument instead.

File: test/python/test_reactor.py (hunk 7 above)
Comment (ischoegl) [reply test/python/test_reactor.py]: Good catch. Likely copy-pasta.

**Comment by ischoegl** [comment]
@speth ... thanks for the review! Your suggestion to simplify `setDefaultName` is much appreciated!

**Comment by ischoegl** [comment]
@speth ... assuming that this is ready to merge, I'll use this to start on Cantera/enhancements#213.

**Review by speth — APPROVED** [review]
