### PR TITLE
Reliable input file errors

### LINKED ISSUE #1281: Invalid reactions no longer reliably raise InputFileError
**Problem description**

In Cantera 2.5, a YAML reaction definition without any rate constant information would raise an `InputFileError` showing the problematic reaction definition. Now, an error is thrown by `ArrheniusBase::validate` which does not show the corresponding input location.

Also, reactions containing undeclared species only produce the desired error message if the reaction rate is specified as a `dict`, but not if it is specified as a list.

**Steps to reproduce**

1. Create an input file with the following contents:
```yaml
phases:
- name: gas
  thermo: ideal-gas
  species: [{h2o2.yaml/species: all}]
  kinetics: gas
  reactions: all
  state: {T: 300.0, P: 1 atm, X: {O2: 0.21, N2: 0.79}}

reactions:
- equation: 2 OH (+M) <=> H2O2 (+M)
  type: falloff
- equation: O + H2 <=> H + OH
- equation: CH3 + OH => CH3O + H
  rate-constant: {A: 1.0, b: 0, Ea: 0}
- equation: CH3 + OH => CH3O + H
  rate-constant: [0, 0, 0]
```
3. Import the phase in Python

**Behavior**

In Cantera 2.6.0, this raises an exception where an `InputFileError` is only given for the third reaction:
```
*******************************************************************************
CanteraError thrown by addReactions:

*******************************************************************************
CanteraError thrown by ArrheniusBase::validate:
Rate object for reaction '2 OH (+M) <=> H2O2 (+M)' is not configured.
*******************************************************************************

*******************************************************************************
CanteraError thrown by ArrheniusBase::validate:
Rate object for reaction 'H2 + O <=> H + OH' is not configured.
*******************************************************************************

*******************************************************************************
InputFileError thrown by Reaction::checkSpecies:
Error on line 12 of ./bad.yaml:
Reaction 'CH3 + OH => CH3O + H'
contains undeclared species: 'CH3', 'CH3O'
|  Line |
|     7 | 
|     8 | reactions:
|     9 | - equation: 2 OH (+M) <=> H2O2 (+M)
|    10 |   type: falloff
|    11 | - equation: O + H2 <=> H + OH
>    12 > - equation: CH3 + OH => CH3O + H
            ^
|    13 |   rate-constant: {A: 1.0, b: 0, Ea: 0}
|    14 | - equation: CH3 + OH => CH3O + H
|    15 |   rate-constant: [0, 0, 0]
*******************************************************************************

*******************************************************************************
CanteraError thrown by ArrheniusBase::validate:
Rate object for reaction 'CH3 + OH => CH3O + H' is not configured.
*******************************************************************************
*******************************************************************************
```

In Cantera 2.5.1, this input file produced useful error `InputFileError` messages for all four reactions:
```
***********************************************************************
CanteraError thrown by addReactions:

***********************************************************************
InputFileError thrown by AnyMap::operator[]:
Error on line 9 of ./bad.yaml:
Key 'low-P-rate-constant' not found.
Existing keys: equation, type
|  Line |
|     4 |   species: [{h2o2.yaml/species: all}]
|     5 |   kinetics: gas
|     6 |   reactions: all
|     7 | 
|     8 | reactions:
>     9 > - equation: 2 OH (+M) <=> H2O2 (+M)
            ^
|    10 |   type: falloff
|    11 | - equation: O + H2 <=> H + OH
|    12 | - equation: CH3 + OH => CH3O + H
***********************************************************************

***********************************************************************
InputFileError thrown by AnyMap::operator[]:
Error on line 11 of ./bad.yaml:
Key 'rate-constant' not found.
Existing keys: equation
|  Line |
|     6 |   reactions: all
|     7 | 
|     8 | reactions:
|     9 | - equation: 2 OH (+M) <=> H2O2 (+M)
|    10 |   type: falloff
>    11 > - equation: O + H2 <=> H + OH
            ^
|    12 | - equation: CH3 + OH => CH3O + H
|    13 |   rate-constant: {A: 1.0, b: 0, Ea: 0}
|    14 | - equation: CH3 + OH => CH3O + H
***********************************************************************

***********************************************************************
InputFileError thrown by Kinetics::addReaction:
Error on line 12 of ./bad.yaml:
Reaction 'CH3 + OH => CH3O + H' contains the undeclared species 'CH3'
|  Line |
|     7 | 
|     8 | reactions:
|     9 | - equation: 2 OH (+M) <=> H2O2 (+M)
|    10 |   type: falloff
|    11 | - equation: O + H2 <=> H + OH
>    12 > - equation: CH3 + OH => CH3O + H
            ^
|    13 |   rate-constant: {A: 1.0, b: 0, Ea: 0}
|    14 | - equation: CH3 + OH => CH3O + H
|    15 |   rate-constant: [0, 0, 0]
***********************************************************************

***********************************************************************
InputFileError thrown by Kinetics::addReaction:
Error on line 14 of ./bad.yaml:
Reaction 'CH3 + OH => CH3O + H' contains the undeclared species 'CH3'
|  Line |
|     9 | - equation: 2 OH (+M) <=> H2O2 (+M)
|    10 |   type: falloff
|    11 | - equation: O + H2 <=> H + OH
|    12 | - equation: CH3 + OH => CH3O + H
|    13 |   rate-constant: {A: 1.0, b: 0, Ea: 0}
>    14 > - equation: CH3 + OH => CH3O + H
            ^
|    15 |   rate-constant: [0, 0, 0]
***********************************************************************
***********************************************************************
```

**System information**

- Cantera version: 2.6.0

### LINKED ISSUE #1283: UnitSystem::convert should raise InputFileError where possible
**Problem description**

Incorrect units specified in YAML input files result in error messages that aren't easy to trace back to the problematic input data.

**Steps to reproduce**

Importing the following YAML file:
```yaml
phases:
- name: gas
  thermo: ideal-gas
  species: [{h2o2.yaml/species: all}]
  kinetics: gas
  reactions: all

reactions:
- equation: O + H2 <=> H + OH  # Reaction 3
  rate-constant: {A: 3.87e+04 cm^6/mol^2/s, b: 2.7, Ea: 6260.0}
```

produces the error message:
```
CanteraError: 
*******************************************************************************
CanteraError thrown by addReactions:

*******************************************************************************
CanteraError thrown by UnitSystem::convert:
Incompatible units:
    Units(1.0000000000000002e-06 m^6 / kmol^2 / s) and
    Units(m^3 / kmol / s)
*******************************************************************************
*******************************************************************************
```

Which doesn't tell the user which reaction was the source of the problem. Raising an `InputFileError` would be a nice improvement, though it will require some changes to how this is handled in the `UnitSystem` class.

**System information**

- Cantera version: 2.6.0

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Address `InputFileError` issues
- Simplify `ReactionRate::check`
- Avoid `NAN` as sentinel values for `ReactionRate` initialization status (see `--fast-math` enhancement issue)

**If applicable, fill in the issue number this pull request is fixing**

Closes #1281, closes #1283, partially addresses Cantera/enhancements#125

**If applicable, provide an example illustrating new features this pull request is introducing**

Loading the following YAML
```yaml
phases:
- name: gas
  thermo: ideal-gas
  species: [{h2o2.yaml/species: all}]
  kinetics: gas
  reactions: all
  state: {T: 300.0, P: 1 atm, X: {O2: 0.21, N2: 0.79}}

reactions:
- equation: O + H2 <=> H + OH
  rate-constant: {A: 3.87e+04 cm^6/mol^2/s, b: 2.7, Ea: 6260.0}
- equation: 2 OH (+M) <=> H2O2 (+M)
  type: falloff
- equation: CH3 + OH => CH3O + H
  rate-constant: {A: 1.0, b: 0, Ea: 0}
```
results in the following error:
```
CanteraError:
*******************************************************************************
CanteraError thrown by addReactions:

*******************************************************************************
InputFileError thrown by UnitSystem::convert:
Error on line 11 of ./test.yaml:
Incompatible units:
    Units(1.0000000000000002e-06 m^6 / kmol^2 / s) and
    Units(m^3 / kmol / s)
|  Line |
|     6 |   reactions: all
|     7 |   state: {T: 300.0, P: 1 atm, X: {O2: 0.21, N2: 0.79}}
|     8 |
|     9 | reactions:
|    10 | - equation: O + H2 <=> H + OH
>    11 >   rate-constant: {A: 3.87e+04 cm^6/mol^2/s, b: 2.7, Ea: 6260.0}
                               ^
|    12 | - equation: 2 OH (+M) <=> H2O2 (+M)
|    13 |   type: falloff
|    14 | - equation: CH3 + OH => CH3O + H
*******************************************************************************

*******************************************************************************
InputFileError thrown by FalloffRate::validate:
Error on line 12 of ./test.yaml:
Rate object for reaction '2 OH (+M) <=> H2O2 (+M)' is not configured.
|  Line |
|     7 |   state: {T: 300.0, P: 1 atm, X: {O2: 0.21, N2: 0.79}}
|     8 |
|     9 | reactions:
|    10 | - equation: O + H2 <=> H + OH
|    11 |   rate-constant: {A: 3.87e+04 cm^6/mol^2/s, b: 2.7, Ea: 6260.0}
>    12 > - equation: 2 OH (+M) <=> H2O2 (+M)
            ^
|    13 |   type: falloff
|    14 | - equation: CH3 + OH => CH3O + H
|    15 |   rate-constant: {A: 1.0, b: 0, Ea: 0}
*******************************************************************************

*******************************************************************************
InputFileError thrown by Reaction::checkSpecies:
Error on line 14 of ./test.yaml:
Reaction 'CH3 + OH => CH3O + H'
contains undeclared species: 'CH3', 'CH3O'
|  Line |
|     9 | reactions:
|    10 | - equation: O + H2 <=> H + OH
|    11 |   rate-constant: {A: 3.87e+04 cm^6/mol^2/s, b: 2.7, Ea: 6260.0}
|    12 | - equation: 2 OH (+M) <=> H2O2 (+M)
|    13 |   type: falloff
>    14 > - equation: CH3 + OH => CH3O + H
            ^
|    15 |   rate-constant: {A: 1.0, b: 0, Ea: 0}
*******************************************************************************
*******************************************************************************
```

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
@speth ... not sure what I did to `ChebyshevRate` that broke ` YamlWriter.chebyshev_units_from_Yaml` ... stumped.

File: include/cantera/kinetics/Arrhenius.h [hunk 1]
```diff
@@ -159,19 +158,24 @@ class ArrheniusBase : public ReactionRate
...
-    double m_logA; //!< Logarithm of pre-exponential factor
-    double m_order; //!< Reaction order
+    bool m_negativeA_ok = false; //!< Permissible negative A values
+    double m_A = NAN; //!< Pre-exponential factor
+    double m_b = NAN; //!< Temperature exponent
+    double m_Ea_R = 0.; //!< Activation energy (in temperature units)
+    double m_E4_R = 0.; //!< Optional 4th energy parameter (in temperature units)
+    double m_logA = NAN; //!< Logarithm of pre-exponential factor
+    double m_order = NAN; //!< Reaction order
     std::string m_A_str = "A"; //!< The string for temperature exponent
```
Comment (bryanwweber) [inline include/cantera/kinetics/Arrhenius.h]: There's a bit of copy-pasta here, if you don't mind fixing it.

```suggestion
    std::string m_A_str = "A"; //!< The string for pre-exponential factor
```

File: interfaces/cython/cantera/test/test_kinetics.py [hunk 2]
```diff
@@ -480,6 +480,16 @@ def test_sticking_coeff_err(self):
                 ct.Interface("sticking_coeff_check.yaml", "Pt_surf", [gas])
 
 
+def check_raises(yaml, err_msg, line=None):
```
Comment (bryanwweber) [inline interfaces/cython/cantera/test/test_kinetics.py]: It seems like `line` is required, any reason to give it a default value?

File: interfaces/cython/cantera/test/test_kinetics.py [hunk 3]
```diff
@@ -608,6 +610,63 @@ def test_skip_undeclared_surf_species(self):
...
+        # invalid actiation energy units
+        gas_def = self._gas_def + """
+            reactions:
+            - equation: O + H2 <=> H + OH  # Reaction 3
+              rate-constant: {A: 3.87e+04, b: 2.7, Ea: 6260.0 m}
+            """
+        check_raises(gas_def, "UnitSystem::convertActivationEnergy:", line=12)
+
+    def test_failing_unconfigured1(self):
+        # invalid actiation energy units
```
Comment (bryanwweber) [inline interfaces/cython/cantera/test/test_kinetics.py]: Are these comments correct, in this function and the following ones?

**Review by bryanwweber — COMMENTED** [review]
Just a couple small comments I noticed quickly. I haven't gone through everything 😄

File: interfaces/cython/cantera/test/test_kinetics.py (hunk 2 above)
Comment (ischoegl) [reply interfaces/cython/cantera/test/test_kinetics.py]: This does indeed work. I was mostly just trying to keep the `line=` when calling for clarity.

File: interfaces/cython/cantera/test/test_kinetics.py (hunk 3 above)
Comment (ischoegl) [reply interfaces/cython/cantera/test/test_kinetics.py]: no. copy-pasta.

**Comment by bryanwweber** [comment]
@ischoegl This needs a rebase to fix the merge conflict. I'd also like @speth to take a look at this when he has a chance.

File: src/kinetics/Arrhenius.cpp [hunk 4]
```diff
@@ -86,11 +71,12 @@ void ArrheniusBase::setRateParameters(
     if (m_A > 0.0) {
         m_logA = std::log(m_A);
     }
+    m_valid = true;
 }
 
 void ArrheniusBase::getRateParameters(AnyMap& node) const
 {
-    if (std::isnan(m_A)) {
+    if (!valid()) {
```
Comment (bryanwweber) [inline src/kinetics/Arrhenius.cpp:79]: I think `isValid()` would be a more descriptive name for this method.

File: src/kinetics/ChebyshevRate.cpp [hunk 5]
```diff
@@ -112,14 +109,20 @@ void ChebyshevRate::setLimits(double Tmin, double Tmax, double Pmin, double Pmax
 
 void ChebyshevRate::setData(const Array2D& coeffs)
 {
-    m_coeffs = coeffs;
-    dotProd_.resize(coeffs.nRows());
+    m_valid = coeffs.data().size();
```
Comment (bryanwweber) [inline src/kinetics/ChebyshevRate.cpp]: Does this type coercion result in warnings from the compiler on any major platforms? Elsewhere, this similar condition was expressed with `.empty()`, which may be better here.

File: src/kinetics/PlogRate.cpp [hunk 6]
```diff
@@ -105,6 +100,7 @@ void PlogRate::setRates(const std::multimap<double, ArrheniusRate>& rates)
     size_t j = 0;
     rates_.clear();
     pressures_.clear();
+    m_valid = rates.size();
```
Comment (bryanwweber) [inline src/kinetics/PlogRate.cpp]: Same here.

File: src/kinetics/PlogRate.cpp [hunk 7]
```diff
@@ -120,6 +116,14 @@ void PlogRate::setRates(const std::multimap<double, ArrheniusRate>& rates)
         j++;
         rates_.push_back(rate.second);
     }
+    if (!m_valid) {
+        // ensure that reaction rate can be evaluated (but returns NaN)
+        rates_.reserve(2);
```
Comment (bryanwweber) [inline src/kinetics/PlogRate.cpp]: Is this needed before `push_back()` is used?

File: src/kinetics/PlogRate.cpp [hunk 8]
```diff
@@ -120,6 +116,14 @@ void PlogRate::setRates(const std::multimap<double, ArrheniusRate>& rates)
...
+        pressures_[std::log(1.e-7)] = {0, 1};
+        rates_.push_back(ArrheniusRate());
+        pressures_[std::log(1.e14)] = {1, 2};
```
Comment (bryanwweber) [inline src/kinetics/PlogRate.cpp]: Why these pressures? Would `TINY` and `HUGE` be better? You can probably also drop the log, right? Just -7 and 14 are the results of those calculations?

**Review by bryanwweber — COMMENTED** [review]
A few comments for consideration 😄

File: src/kinetics/Arrhenius.cpp (hunk 4 above)
Comment (ischoegl) [reply src/kinetics/Arrhenius.cpp:79]: As `Reaction::valid()` already exists (and the method returns the value of a member variable), the nomenclature of `ReactionRate::valid()` is consistent.

File: src/kinetics/ChebyshevRate.cpp (hunk 5 above)
Comment (ischoegl) [reply src/kinetics/ChebyshevRate.cpp]: Casting from an integer to a boolean is understood by all compilers, but I don't have a problem using `.empty()`.

File: src/kinetics/PlogRate.cpp (hunk 7 above)
Comment (ischoegl) [reply src/kinetics/PlogRate.cpp]: Not needed, but good practice.

File: src/kinetics/PlogRate.cpp (hunk 8 above)
Comment (ischoegl) [reply src/kinetics/PlogRate.cpp]: `TINY` and `HUGE` are defined in very different contexts. Using `Cantera::Tiny` (1e-20) and `1. / Cantera::Tiny` instead.

**Comment by ischoegl** [comment]
@bryanwweber / @speth ... rebased and ready for a review.

File: src/kinetics/PlogRate.cpp (hunk 8 above)
Comment (bryanwweber) [reply src/kinetics/PlogRate.cpp]: Perfect, that's what I meant 😄 thanks!

File: include/cantera/kinetics/Arrhenius.h [hunk 9]
```diff
@@ -160,18 +159,18 @@ class ArrheniusBase : public ReactionRate
...
+    double m_Ea_R = 0.; //!< Activation energy (in temperature units)
+    double m_E4_R = 0.; //!< Optional 4th energy parameter (in temperature units)
+    double m_logA = NAN; //!< Logarithm of pre-exponential factor
+    double m_order = NAN; //!< Reaction order
+    std::string m_A_str = "A"; //!< The string for the pre-exponential factor
     std::string m_b_str = "b"; //!< The string for temperature exponent
     std::string m_Ea_str = "Ea"; //!< The string for activation energy
     std::string m_E4_str = ""; //!< The string for an optional 4th parameter
-    Units m_rate_units; //!< Reaction rate units
+    Units m_rate_units {0.}; //!< Reaction rate units
```
Comment (speth) [inline include/cantera/kinetics/Arrhenius.h]: Like the other PR, I'd suggest `Units m_rate_units{0.}` here.

File: interfaces/cython/cantera/test/test_kinetics.py [hunk 10]
```diff
@@ -480,6 +480,16 @@ def test_sticking_coeff_err(self):
...
 
 
+def check_raises(yaml, err_msg, line):
+    """Helper function for InputFileErrors"""
+    err_msg = [err_msg]
+    err_msg.append("InputFileError thrown by ")
+    err_msg.append(f"Error on line {line} of ")
+    for err in err_msg:
+        with pytest.raises(ct.CanteraError, match=err):
+            ct.Solution(yaml=yaml)
```
Comment (speth) [inline interfaces/cython/cantera/test/test_kinetics.py]: Is there a way of doing this without calling `ct.Solution` 3 times for each case?

File: src/kinetics/PlogRate.cpp [hunk 11]
```diff
@@ -120,6 +116,14 @@ void PlogRate::setRates(const std::multimap<double, ArrheniusRate>& rates)
         j++;
         rates_.push_back(rate.second);
     }
+    if (!m_valid) {
+        // ensure that reaction rate can be evaluated (but returns NaN)
+        rates_.reserve(2);
+        pressures_[std::log(Tiny)] = {0, 1};
+        rates_.push_back(ArrheniusRate());
+        pressures_[std::log(1. / Tiny)] = {1, 2};
+        rates_.push_back(ArrheniusRate());
```
Comment (speth) [inline src/kinetics/PlogRate.cpp:123]: You can just provide a rate constant for a single, arbitrary pressure value -- the two lines below this already handle extrapolating outside the specified pressure range.

**Review by speth — CHANGES_REQUESTED** [review]
Thanks for this, @ischoegl. Your solution to #1283 was quite a bit cleaner than what I had been expecting to have to do. I just had a couple of minor suggestions.

**Comment by ischoegl** [comment]
@speth ... thanks for the review! I updated per suggestions.

File: src/kinetics/PlogRate.cpp [hunk 12]
```diff
@@ -120,6 +116,12 @@ void PlogRate::setRates(const std::multimap<double, ArrheniusRate>& rates)
         j++;
         rates_.push_back(rate.second);
     }
+    if (!m_valid) {
+        // ensure that reaction rate can be evaluated (but returns NaN)
+        rates_.reserve(1);
+        pressures_[std::log(OneBar)] = {0, 1};
```
Comment (speth) [inline src/kinetics/PlogRate.cpp]: Since there's only one rate at this pressure, I think the range should be `{0, 0}`. You can see that the case where there's only one rate at a pressure is handled specially in `PlogRate::evalFromStruct`, where these two values correspond to (`ilow1_` and `ilow2_`) or (`ihigh1_` and `ihigh2_`).

Comment (ischoegl) [reply src/kinetics/PlogRate.cpp]: thanks for explaining - fixed as recommended.

**Comment by ischoegl** [comment]
I *believe* that things are taken care of now.

**Review by speth — APPROVED** [review]
