### PR TITLE
Fix issue #1593 in evaluating of lambda at boundary point.

### LINKED ISSUE #1593: Non-uniform lambda in using CounterflowTwinPremixedFlame
**Problem description**
When calculating the CounterflowPremixed flame, the lambda should be uniform acorss the compuattional domain. However, the lambda is set to zero in the right symmetry boundary. This might have no significant influence on the overall results. But I believe modify it back should be a good option for consistence.

**Steps to reproduce**
```

import os
import time
import matplotlib.pyplot as plt
import numpy as np
import cantera as ct

def plot_solution(f, solution_num, path='output'):
    fig = plt.figure(figsize=(10,10))
    axs = []
    axs.append(plt.subplot2grid((2,2), (0,0))) # top left
    axs.append(plt.subplot2grid((2, 2), (1, 0)))  # middle left
    axs.append(plt.subplot2grid((2, 2), (0, 1)))  # top right
    axs.append(plt.subplot2grid((2, 2), (1, 1)))  # middle right
    
    axs[0].plot(f.grid, f.T, 'o-')
    axs[0].set_xlabel('Distance, m')
    axs[0].set_ylabel('Temperature, K')
    axs[0].set_ylim([200, 2900])
    
    axs[1].plot(f.grid, f.velocity, 'o-')
    axs[1].set_xlabel('Distance, m')
    axs[1].set_ylabel('Axial Velocity, m/s')
    
    axs[2].plot(f.grid, f.spread_rate, 'o-')
    axs[2].set_xlabel('Distance, m')
    axs[2].set_ylabel('Spread Rate, 1/s')
        
    axs[3].plot(f.grid, f.L, 'o-')
    axs[3].set_xlabel('Distance, m')
    axs[3].set_ylabel('Lambda, m/s')
    fig.tight_layout()
    plt.savefig(path + '/combined_flamelet_' + str(solution_num+1) + '.png')
    plt.close()


# Input parameters
p = 1* ct.one_atm  # pressure
tin = 300.0  # fuel inlet temperature
width = 0.02 # Distance between inlets

comp_o = 'O2:1, N2:3.76'  # oxidizer composition
comp_f = 'H2:1.0'  # fuel composition

loglevel = 1  # amount of diagnostic output (0 to 5)

gas = ct.Solution('gri30.yaml')
gas.TPX = tin, p, comp_f
gas.TPX = tin, p, comp_o

gas.set_equivalence_ratio(phi=1.0, fuel=comp_f, oxidizer=comp_o)
density_u = gas.density
f = ct.CounterflowTwinPremixedFlame(gas, width=width)

# Set the state of the two inlets
f.reactants.mdot = density_u*8
f.reactants.Y = gas.Y
f.reactants.T = tin

#f.set_refine_criteria(ratio=4, slope=0.2, curve=0.3, prune=0.04)
f.set_refine_criteria(ratio=10, slope=0.1, curve=0.1, prune=0.05)

# Solve the problem
f.solve(loglevel, auto=True)
f.save('previous_solution.yaml',overwrite=True)

plot_solution(f, -10, '.')
```

1. Run the above code
2. Check the result of lambda

**Behavior**

A non-uniform lambda is observed at the boundary point. Ideally, this should be uniform across the computational domain.

**System information**

- Cantera version: [commit cde1e79](https://github.com/Cantera/cantera/tree/cde1e79567519646d1b6b9520c4a24d4f22f0f6c)
- OS: wsl-Ubuntu20
- Python/MATLAB/other software versions: Python 3.11

**Attachments**

**Additional context**

This problem arises due to the incorrect set of boundary conditions in function evalRightBoundary at Stflow.cpp. At line 1030 (Stflow.cpp), the code 
`rsd[index(c_offset_L, j)] = lambda(x, j);` should be changed to `rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);`, so that an zero gradient condition is set for the lambda.

### PR DESCRIPTION
**Pull request by yeanment**
**Changes proposed in this pull request**

- right boundary condition for lambda in evalRightBoundary function

**If applicable, fill in the issue number this pull request is fixing**

Closes #1593

**If applicable, provide an example illustrating new features this pull request is introducing**

Fix the bug of non-uniform lambda for strained flow.

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

File: src/oneD/StFlow.cpp [hunk 1]
```diff
@@ -1027,12 +1027,11 @@ void StFlow::evalRightBoundary(double* x, double* rsd, int* diag, double rdt)
     diag[index(c_offset_Y + rightExcessSpecies(), j)] = 0;
     if (m_usesLambda) {
         rsd[index(c_offset_U, j)] = rho_u(x, j);
-        rsd[index(c_offset_L, j)] = lambda(x, j);
```
Comment (ischoegl) [inline src/oneD/StFlow.cpp:1030]:
```suggestion
        rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);
```
zero gradient

File: src/oneD/StFlow.cpp [hunk 2]
```diff
@@ -1027,12 +1027,11 @@ void StFlow::evalRightBoundary(double* x, double* rsd, int* diag, double rdt)
...
     } else {
         rsd[index(c_offset_U, j)] = rho_u(x, j) - rho_u(x, j-1);
-        rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);
```
Comment (ischoegl) [inline src/oneD/StFlow.cpp:1033]:
```suggestion
        rsd[index(c_offset_L, j)] = lambda(x, j);
```
zero (lambda is not used)

File: src/oneD/StFlow.cpp [hunk 3]
```diff
@@ -1027,12 +1027,11 @@ void StFlow::evalRightBoundary(double* x, double* rsd, int* diag, double rdt)
...
     }
 
+    rsd[index(c_offset_L, j)] = lambda(x, j) - lambda(x, j-1);
```
Comment (ischoegl) [inline src/oneD/StFlow.cpp:1034]:
```suggestion
```

**Review by ischoegl — CHANGES_REQUESTED** [review]
@yeanment ... thanks for the fix! I had inadvertently added the zero gradient to the wrong branch in #1555. My suggestion won't change results, but shows the BC a little better.

**Comment by yeanment** [comment]
I agree with you. This has minor influence on the solution.

**Comment by ischoegl** [comment]
@yeanment ... to ensure that the test suite covers this issue, I have suggestions for minor unit test updates, see commit 7b2b855c595d90af8449f398861f7c3f16a43ad2 on https://github.com/ischoegl/cantera/tree/fix-1593 ... feel free to cherry-pick or copy. Also, you can add yourself to the `AUTHORS` list in the main folder (it's alphabetical).

This fix probably should go in before the release of Cantera 3.0 (which is imminent). Thanks again for catching this issue as well as for creating this PR!

**Comment by yeanment** [comment]
@ischoegl Thank you for your prompt reply.  I have checked the commit 7b2b855, believe the unit test updates help cover the issue more comprehensively. 

Btw, I am not that familiar with the github workflow. If applicable, you may add me as Shumeng Xie from National University of Singapore. I'm glad I could contribute to this fascinating tool. Thanks again for your effort in maintenance and improvement on this code.

**Comment by ischoegl** [comment]
> Btw, I am not that familiar with the github workflow. If applicable, you may add me as Shumeng Xie from National University of Singapore. I'm glad I could contribute to this fascinating tool. Thanks again for your effort in maintenance and improvement on this code.

No problem! Thanks again for identifying/fixing this issue.

Unfortunately, I'm unable to add to this PR as your `yeanment/main` branch appears to be protected. The easiest solution is to just accept this PR as is; I will add other changes separately. As a recommendation, it's best to create a new branch on your repository before creating a PR; that way, you won't run into merge conflicts etc.

**Review by ischoegl — APPROVED** [review]
