### PR TITLE
Remove clib *newFromFile from MATLAB / fix memory leaks

### LINKED ISSUE #1756: Ambiguous references in clib's Cabinet<M>::index
**Problem description**

When calling a destructor for a `Solution` object via `soln_del` using the `clib` API, associated `ThermoPhase`, `Kinetics` and `Transport` objects are deallocated. As integer entry numbers ('handles') are not available, the destructor relies on `Cabinet<M>::index`, which returns the last entry of a reverse lookup table. There is no guarantee that the *correct* entry is removed, leading to potentially unpredictable behavior and memory leaks.

**System information**

- Cantera version: 3.1a3
- OS: any
- Python/MATLAB/other software versions: N/A

**Additional context**

- found in context of #1754

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Remove `clib`'s `*_newFromFile` constructors from MATLAB; use pathways using `Solution` exclusively instead
- Fix memory leak in `clib` where automatically added *adjacent* phases could not be removed
- Make MATLAB `Interface.adjacent` consistent with Python version (select phase by name rather than index)
- Fix ambiguous references that will lead to memory leaks (going back to #1448)

**If applicable, fill in the issue number this pull request is fixing**

Resolves #1756
Partially addresses Cantera/enhancements#199

**Example**

New in *experimental* MATLAB:
```
surf = Interface('ptcombust.yaml', 'Pt_surf');
gas = surf.adjacent('gas');
```

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

**Comment by ischoegl** [comment]
Added a fix for #1756: while the issue was pre-existing, this PR surfaced some symptoms, where incorrect `Cabinet` entries were deleted when `Solution` destructors were called. The PR is (again) ready for review.

*PS: force-push was only to fix typos in commit messages / prevent CI failures.*

File: interfaces/matlab_experimental/Base/Solution.m [hunk 1]
```diff
@@ -39,57 +31,62 @@
...
-    % :param trans:
-    %     String, transport modeling. Possible values are ``'default'``, ``'none'``,
-    %     ``'mixture-averaged'``, or ``'multicomponent'``. If not specified,
-    %     ``'default'`` is used.
+    % :param name:
+    %     name of the phase to import as specified in the YAML file.
+    % :param transport_model:
+    %     String specifying transport model. Possible values are ``'default'``,
+    %     ``'none'``, ``'mixture-averaged'``, or ``'multicomponent'``. If not specified,
+    %     ``'none'`` is used.
```
Comment (speth) [inline interfaces/matlab_experimental/Base/Solution.m]: For consistency with the Python and C++ interfaces, shouldn't this use the `default` transport model if the argument is omitted?

File: src/clib/Cabinet.h [hunk 2]
```diff
@@ -61,12 +63,14 @@ class SharedCabinet
     /**
      * Add a new object. The index of the object is returned.
      */
-    static int add(shared_ptr<M> obj) {
+    static int add(shared_ptr<M> obj, int parent=-1) {
         dataRef data = getData();
         data.push_back(obj);
+        parentRef parents = getParents();
```
Comment (speth) [inline src/clib/Cabinet.h]: You could just write:
```suggestion
        auto& parents = getParents();
```
and eliminate the need for the `parentRef` typedef.

File: src/clib/ct.cpp [hunk 3]
```diff
@@ -218,12 +214,35 @@ extern "C" {
...
         } catch (...) {
             return handleAllExceptions(-2, ERR);
         }
     }
 
+    int soln_adjacentName(int n, int a, int lennm, char* nm)
+    {
+        try {
+            auto soln = SolutionCabinet::at(n);
+            if (a < 0 || a >= (int)soln->nAdjacent()) {
```
Comment (speth) [inline src/clib/ct.cpp]: I'd recommend `static_cast<int>` over the C-style cast.

File: test/clib/test_clib.cpp [hunk 4]
```diff
@@ -28,11 +28,21 @@ TEST(ct, cabinet_exceptions)
...
     int ret = soln_del(999);
     ASSERT_EQ(ret, -1);
     err = reportError();
     EXPECT_THAT(err, HasSubstr("delete a non-existing object."));
 
+    int ref = soln_newSolution("h2o2.yaml", "ohmech", "default");
+    soln_del(ref);
+    soln_thermo(ref);
+    err = reportError();
+    EXPECT_THAT(err, HasSubstr("has been deleted."));
```
Comment (speth) [inline test/clib/test_clib.cpp]: You might also want to check the return value from `soln_thermo` here, right?

**Review by speth — COMMENTED** [review]
Thanks, @ischoegl. This looks mostly good to me. Just had a couple of small suggestions.

File: interfaces/matlab_experimental/Base/Solution.m (hunk 1 above)
Comment (ischoegl) [reply interfaces/matlab_experimental/Base/Solution.m]: Whoops - good catch!

**Comment by ischoegl** [comment]
> Thanks, @ischoegl. This looks mostly good to me. Just had a couple of small suggestions.

Thanks for the prompt review! I think it's all taken care of.

**Review by speth — APPROVED** [review]
