### PR TITLE
Doxygen autobrief fixes

### LINKED ISSUE #1560: Doxygen autobrief does not work for `/*!`
**Problem description**

`CONTRIBUTING.md` states a preference for `/*!` over `/**`. However, the former breaks Doxygen's autobrief feature. See, for example, documentation of the [C++ SolutionArray class](https://cantera.org/documentation/dev/doxygen/html/de/d8f/classCantera_1_1SolutionArray.html#pub-methods), where in the list of "public member functions" many instances of `@brief` documentation are not shown (i.e. the docstring is not broken at the dot `'.'`). The supported autobrief version should use `/**` per [Doxygen documentation](https://www.doxygen.nl/manual/docblocks.html).

Per documentation, this works:
```
/** Brief description which ends at this dot. Details follow
 *  here.
 */
```
as well as 
```
//! Brief description, which is
//! really a detailed description since it spans multiple lines.
/*! Another detailed description!
 */
```
While Doxygen is flexible, we apparently recommended a version that doesn't support autobrief, i.e.
```
/*! 
 * This is a detailed description. Autobrief does not work 
 * for this documentation style.
 */
```

I verified that this would work (although it is somewhat ugly):
```
//! Brief description.
/**
 * Detailed description. [...]
 */
```

As an aside, this is also true:
```
//! This is a brief description. It continues after the dot.
```

**System information**

- Cantera version: `main`
- OS: any
- Python/MATLAB/other software versions: doxygen=1.9.1

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

Fix instances where intended autobrief documentation was not rendered correctly. This *mostly* affects newer documentation.

Also, add some citations.

**If applicable, fill in the issue number this pull request is fixing**

Closes #1560 / partially addresses Cantera/enhancements#179

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

File: include/cantera/base/SolutionArray.h [hunk 1]
```diff
@@ -192,68 +194,69 @@ class SolutionArray
...
      *
      *  @param fname  Name of CSV file
-     *  @param overwrite  Force overwrite if file exists; optional (default=false)
-     *  @param basis  Output mass ("Y"/"mass") or mole ("X"/"mole") fractions;
-     *      if omitted (default=""), the native basis of the underlying ThermoPhase
-     *      manager is used - @see nativeState
+     *  @param overwrite  Force overwrite if file exists; optional (default=`false`)
+     *  @param basis  Output mass (`"Y"`/`"mass"`) or mole (`"X"`/`"mole"`) fractions;
+     *      if omitted (default=`""`), the native basis of the underlying ThermoPhase
+     *      manager is used - see @ref Phase::nativeState
```
Comment (speth) [inline include/cantera/base/SolutionArray.h]: `@ref` is unnecessary here.

File: include/cantera/base/SolutionArray.h [hunk 2]
```diff
@@ -272,37 +275,37 @@ class SolutionArray
...
      *  @param overwrite  Force overwrite if file and/or data entry exists; optional
-     *      (default=false)
+     *      (default=`false`)
      *  @param compression  Compression level (0-9); (default=0; HDF only)
-     *  @param basis  Output mass ("Y"/"mass") or mole ("X"/"mole") fractions;
-     *      if not specified (default=""), the native basis of the underlying
-     *      ThermoPhase manager is used - @see nativeState (CSV only)
+     *  @param basis  Output mass (`"Y"`/`"mass"`) or mole (`"X"`/`"mole"`) fractions;
+     *      if not specified (default=`""`), the native basis of the underlying
+     *      ThermoPhase manager is used - see @ref Phase::nativeState (CSV only)
```
Comment (speth) [inline include/cantera/base/SolutionArray.h]: Ditto here.

File: include/cantera/base/SolutionArray.h [hunk 3]
```diff
@@ -311,26 +314,26 @@ class SolutionArray
...
      */
     void readEntry(const AnyMap& root, const string& name, const string& sub);
 
-    /*!
+    /**
      *  Restore SolutionArray data and header information from a container file.
      *
      *  This method retrieves data from a YAML or HDF files that were previously saved
-     *  using the @see save method.
+     *  using the @ref save() method.
```
Comment (speth) [inline include/cantera/base/SolutionArray.h]: And here.

**Comment by speth** [comment]
@ischoegl - I dismissed the review request since this branch keeps changing. Please re-request a review when you're finished here.

**Comment by ischoegl** [comment]
Should be done now. If I find anything else, I’ll attach it elsewhere.

File: src/thermo/WaterPropsIAPWS.cpp [hunk 4]
```diff
@@ -28,7 +28,7 @@ static const doublereal M_water = 18.015268;
 
 static const double R_water = 461.51805; // J/kg/K (Eq. 6.3)
 
-//! Gas constant that is quoted in the paper
+// Gas constant that is quoted in the paper
```
Comment (speth) [inline src/thermo/WaterPropsIAPWS.cpp]: If the above constants (`T_c` etc.) get Doxygen comments, why shouldn't this one as well?

**Review by speth — CHANGES_REQUESTED** [review]

**Comment by ischoegl** [comment]
Thanks, @speth - this should be ready to merge.

**Review by speth — APPROVED** [review]
