### PR TITLE
[Reactor] clarify FlowDevice interface

### LINKED ISSUE #666: Create consistent approach for FlowDevice parameters/functions
### Cantera version

2.4.0 / 2.5.0a3

### Operating System /  Python/MATLAB version

all

### Expected Behavior

`FlowDevice` objects should use a consistent philosophy for the implementation of parameters. I.e. `MassFlowController`, `PressureController` and `Valve`. Function names should be representative of actual behavior. MATLAB and Python implementations should use the same approach.

### Actual Behavior

The implementation of `FlowDevice` objects is not consistent and even differs between Python and MATLAB. ~~Python does not use the vector `m_coeffs` whereas MATLAB can set an array of values that cannot be used by the underlying C++ code.~~ `FlowDevice::updateMassFlowRate` function signatures take time as an argument, which is not implemented for `Valve` objects (which precludes the implementation of time-dependent switching valves).

Some function names in the python interface are misleading (`Valve.set_pressure_coeff`). Python and MATLAB implementations differ (`FlowDevice::setParameters`).

### Steps to reproduce
1. N/A

### PR DESCRIPTION
**Pull request by ischoegl**
This PR seeks to clarify the FlowDevice interface; specifically, the implementation of `Valve.set_pressure_coeff` was non-intuitive (misleading function name and partially incorrect doc string)

Please fill in the issue number this pull request is fixing:

Fixes #666 

(also: addresses comment in #587, and prepares fix needed for #665)

Changes proposed in this pull request:

 - differentiate `Valve::setValveCoeff` from `PressureController::setPressureCoeff`
 - introduce `Valve::setValveLift` for time-dependent valve opening/closing
 - introduce `Valve.set_valve_function` to eliminate `Valve.valve_coeff(Func1)` being erroneously applied to `Valve::setFunction`
 - introduce properties `Valve.valve_coeff` / `PressureController.pressure_coeff` in Cython interface    and deprecate `Valve.set_pressure_coeff` / `PressureController.set_pressure_coeff` (which is consistent with coefficient handling used by other `zeroD` objects)
 - deprecate corresponding function calls in clib interface
 - deprecate `FlowDevice.setParameters` (which was only used by MATLAB interface)

### CODE REVIEW

File: include/cantera/clib/ctreactor.h [hunk 1]
```diff
@@ -3,7 +3,7 @@
  */
 
 // This file is part of Cantera. See License.txt in the top-level directory or
-// at http://www.cantera.org/license.txt for license and copyright information.
```
Comment (speth) [inline include/cantera/clib/ctreactor.h:6]: As before, the "important" change here is using `https`, not removing `www`.

File: include/cantera/zeroD/flowControllers.h [hunk 2]
```diff
@@ -84,26 +94,57 @@ class Valve : public FlowDevice
 public:
     Valve();
 
+<<<<<<< HEAD
```
Comment (speth) [inline include/cantera/zeroD/flowControllers.h]: These merge conflict markers need to be removed.

File: include/cantera/zeroD/flowControllers.h [hunk 3]
```diff
@@ -84,26 +94,57 @@ class Valve : public FlowDevice
...
+    }
+
+    //! Get the valve coefficient.
+    double getValveCoeff() {
+        return m_coeff;
     }
 
+    //! Set the timing for a Valve object. If provided, the function is evaluated
+    //! as a function of time..
+    void setValveLift(Func1* f);
```
Comment (speth) [inline include/cantera/zeroD/flowControllers.h]: I would like to avoid the terminology "lift" which is pretty specific to the poppet valves used in IC engines. Perhaps "opening" would be a more general alternative, i.e. this could be `setOpeningFunction`. Or calling it `setTimeFunction` would provide a parallel to naming f(dP) the `pressureFunction`.

File: include/cantera/zeroD/flowControllers.h [hunk 4]
```diff
@@ -84,26 +94,57 @@ class Valve : public FlowDevice
...
+>>>>>>> bfab8a070... [Reactor] clarified FlowDevice interface
     }
 
     //! Set the proportionality constant between pressure drop and mass flow
     //! rate
     /*!
      * *c* has units of kg/s/Pa. The mass flow rate is computed as:
+     * \f[\dot{m} = c l(t) f(\Delta P) \f]
+     * where *l* and *f* are functions of time and pressure drop that are set
+     * by `setValveLift` and `setFunction`, respectively. If no functions are
```
Comment (speth) [inline include/cantera/zeroD/flowControllers.h]: Isn't part of the confusion here that it's unclear which function `setFunction` should set? Shouldn't the method to set f(dP) be called something like `setPressureFunction`?

File: interfaces/cython/cantera/reactor.pyx [hunk 5]
```diff
@@ -772,13 +773,18 @@ cdef class Valve(FlowDevice):
...
 
     where :math:`f` is the arbitrary function that returns the mass flow rate given
-    a single argument, the pressure differential. See the documentation for the
-    `set_valve_coeff` method for an example. Note that it is never possible for
-    the flow to reverse and go from the downstream to the upstream
-    reactor/reservoir through a line containing a `Valve` object.
+    a single argument, the pressure differential. Further, a valve lift curve
+    :math:`l` may be specified using the method `set_valve_lift`, such that
+
+    .. math:: \dot m = K_v*l(t)*f(P_1 - P_2)
```
Comment (speth) [inline interfaces/cython/cantera/reactor.pyx]: I'd recommend almost any other symbol for the first function here -- `l(t)` looks too much like `1(t)` in most fonts, at least to me.

File: interfaces/cython/cantera/reactor.pyx [hunk 6]
```diff
@@ -804,7 +854,18 @@ cdef class Valve(FlowDevice):
...
         >>> V.set_valve_coeff(1e-4)  # Set the value of K to a constant
         >>> V.set_valve_coeff(lambda dP: (1e-5 * dP)**2)  # Set the value of K to a function
+
+        .. deprecated:: 2.5
+
+             To be deprecated with version 2.5, and removed thereafter.
+             Replaced by property to be consistent with other coefficient definition
+             (e.g. Walls). Doc string for set_valve_coeff is further not consistent
+             with C++ implementation (Func1 value is not handled as a coefficient,
+             making its usage non-intuitive).
```
Comment (speth) [inline interfaces/cython/cantera/reactor.pyx]: In general, I would suggest that the deprecation notation does not need to go into the rationale for the deprecation, but just provide the recommended alternative.

File: interfaces/cython/cantera/examples/reactors/ic_engine.py [hunk 7]
```diff
@@ -125,15 +125,15 @@ def piston_speed(t):
     # define opening and closing of valves and injector
     if (np.mod(crank_angle(t_i) - inlet_open, 4 * np.pi) <
             np.mod(inlet_close - inlet_open, 4 * np.pi)):
-        inlet_valve.set_valve_coeff(inlet_valve_coeff)
+        inlet_valve.valve_coeff = inlet_valve_coeff
         test[n1] = 1
     else:
-        inlet_valve.set_valve_coeff(0)
+        inlet_valve.valve_coeff = 0.
```
Comment (speth) [inline interfaces/cython/cantera/examples/reactors/ic_engine.py:131]: Now that the valve opening can be specified as a function of time, can't we define this as a function, and resolve #665?

**Review by speth — CHANGES_REQUESTED** [review]
I think having valve flow rate be a function of both time and the pressure difference will be a nice addition. The implementation looks good to me. I just had a few comments, mainly about the terminology used for the new functions.

File: interfaces/cython/cantera/examples/reactors/ic_engine.py (hunk 7 above)
Comment (ischoegl) [reply interfaces/cython/cantera/examples/reactors/ic_engine.py:131]: Exactly! That was the incentive for this PR.

File: include/cantera/clib/ctreactor.h (hunk 1 above)
Comment (ischoegl) [reply include/cantera/clib/ctreactor.h:6]: Done.

File: include/cantera/zeroD/flowControllers.h (hunk 3 above)
Comment (ischoegl) [reply include/cantera/zeroD/flowControllers.h]: `setTimeFunction` and `setPressureFunction` are excellent suggestions.

File: include/cantera/zeroD/flowControllers.h (hunk 4 above)
Comment (ischoegl) [reply include/cantera/zeroD/flowControllers.h]: `setPressureFunction` it is.

File: interfaces/cython/cantera/reactor.pyx (hunk 5 above)
Comment (ischoegl) [reply interfaces/cython/cantera/reactor.pyx]: No problem.

File: interfaces/cython/cantera/reactor.pyx (hunk 6 above)
Comment (ischoegl) [reply interfaces/cython/cantera/reactor.pyx]: Ok.

File: src/clib/ctreactor.cpp [hunk 8]
```diff
@@ -438,10 +440,50 @@ extern "C" {
         }
     }
 
-    int flowdev_setFunction(int i, int n)
```
Comment (ischoegl) [inline src/clib/ctreactor.cpp]: Needs to be properly deprecated.

**Comment by ischoegl** [comment]
@speth ... thanks for the review! Your comment and suggestion regarding the naming convention led me to clarify further, and I believe the interface is even clearer now: using a coefficient plus `set_time_function` and `set_pressure_function` there is no ambiguity left. Internally, all `FlowDevice` objects use the same approach (i.e. coefficient multiplied with function(s)). I also tested associated changes of clib from Matlab.

You are correct that those changes were necessary to properly address #665.

On a separate note: on my last merged PR (#660) for some reason my author tag was overwritten (no idea how a rebase/fixup may cause this: a squash is the likely culprit). The effect is that the commits aren't associated with @ischoegl: the associated sha's are d26356667072de4eb727f82e6998a1af3e0eb3ad and 77295b2103210f513187522da549df30069b00de. I can't fix this myself at this point, but I'm also not sure whether it matters and/or that it needs to be changed.

File: include/cantera/zeroD/FlowDevice.h [hunk 9]
```diff
@@ -93,28 +93,58 @@ class FlowDevice
...
+        warn_deprecated("FlowDevice::setFunction()",
+                        "To be removed after Cantera 2.5. "
+                        "Use FlowDevice::setTimeFunction or "
+                        "FlowDevice::setPressureFunction instead.");
+        if (typeStr()=="MassFlowController") {
+            setTimeFunction(f);
+        } else if (typeStr()=="Valve") {
+            setPressureFunction(f);
+        } else {
+        }
```
Comment (speth) [inline include/cantera/zeroD/FlowDevice.h:119]: The empty `else` block is unnecessary.

File: include/cantera/zeroD/FlowDevice.h [hunk 10]
```diff
@@ -93,28 +93,58 @@ class FlowDevice
...
         m_mdot = mdot;
     }
 
 protected:
-    doublereal m_mdot;
-    Func1* m_func;
-    vector_fp m_coeffs;
+    double m_mdot;
+    Func1* m_pfunc;
+    Func1* m_tfunc;
```
Comment (speth) [inline include/cantera/zeroD/FlowDevice.h:149]: Docstrings for the new variables would be nice. Something simple like "function used by setTimeFunction" would be fine.

File: include/cantera/zeroD/flowControllers.h [hunk 11]
```diff
@@ -28,6 +29,27 @@ class MassFlowController : public FlowDevice
...
+     * \f[\dot{m} = m g(t) \f]
+     * where *g* is a function of time that is set by `setTimeFunction`.
+     * If no function is specified, the mass flow rate defaults to:
+     * \f[\dot{m} = m \f]
+     */
+    void setMassFlowCoeff(double m) {
+        m_coeff = m;
+    }
+
+    //! Get the mass flow rate.
```
Comment (speth) [inline include/cantera/zeroD/flowControllers.h]: Should be "coefficient", not "rate", right?

File: interfaces/cython/cantera/test/test_reactor.py [hunk 12]
```diff
@@ -600,6 +660,52 @@ def test_pressure_controller(self):
...
+    def test_pressure_controller_deprecations(self):
+        # Make sure Python deprecation warnings actually get displayed
+
+        self.make_reactors()
+        res = ct.Reservoir(self.gas1)
+        mfc = ct.MassFlowController(res, self.r1, mdot=0.6)
+
+        p = ct.PressureController(self.r1, self.r2, master=mfc, K=0.5)
+
+        with warnings.catch_warnings(record=True) as w:
```
Comment (speth) [inline interfaces/cython/cantera/test/test_reactor.py:698]: I didn't know you could do this, so thanks for teaching me something. :sunglasses:

**Review by speth — CHANGES_REQUESTED** [review]

**Comment by speth** [comment]
@ischoegl The issue with commit ownership applies to this PR as well -- the "commiter" will get reset to me (or whoever merges this PR), but the "author" field will be preserved. The problem is that your "author" information is using your GMail address, while the "committer" field is using your LSU address (which I guess is your primary address on GitHub). After updating your Git configuration, you can reset this for this commit by doing `git commit --amend --reset-author`.

File: include/cantera/zeroD/FlowDevice.h (hunk 9 above)
Comment (ischoegl) [reply include/cantera/zeroD/FlowDevice.h:119]: absolutely

File: include/cantera/zeroD/FlowDevice.h (hunk 10 above)
Comment (ischoegl) [reply include/cantera/zeroD/FlowDevice.h:149]: Done.

File: interfaces/cython/cantera/test/test_reactor.py (hunk 12 above)
Comment (ischoegl) [reply interfaces/cython/cantera/test/test_reactor.py:698]: NP. [stackoverflow](https://stackoverflow.com/questions/3892218/how-to-test-with-pythons-unittest-that-a-warning-has-been-thrown) taught me ;)

**Comment by ischoegl** [comment]
Thanks for the clarification: I will fix that momentarily (both here and for #676). It's highly confusing as my commits still show up with my tag.

**Comment by ischoegl** [comment]
Alright. I changed my primary address to my work and made sure that the commit shows the same. (Until now, I had my primary address set to gmail, which I used to set my account up years ago.) Let's see what happens ... .
EDIT: mystery solved ... typo in e-mail address (!)

**Comment by ischoegl** [comment]
Mystery solved: typo in e-mail address.

**Review by speth — APPROVED** [review]

**Comment by speth** [comment]
The one remaining to-do for this change is to update the "science" documentation for the reactor model on cantera.org (https://cantera.org/science/reactors.html#reactor-networks-and-devices).

**Comment by ischoegl** [comment]
@speth ... I can tackle this, but need to know how the docs are generated? Is there a primer you can direct me to?

**Comment by bryanwweber** [comment]
The restructuredText documents are stored in the Cantera/cantera-website repo. That file will be in the pages/science/reactors.rst I think (sorry no links, I'm on my phone).

**Comment by ischoegl** [comment]
@bryanwweber ... when is an appropriate time to change the cantera website for features only implemented in the development branch?

**Comment by bryanwweber** [comment]
That's a great question. I think the best thing to do is mark the updates as "development version only", to the extent that you can do that without deleting existing content. Anything that will be removed should be marked as deprecated or changed somehow. Let's try that out and see how it goes.

**Comment by ischoegl** [comment]
@bryanwweber ... would it make sense to create a branch that holds information until 2.5 goes live? (there are obviously multiple ways of handling this)

**Comment by bryanwweber** [comment]
I think (maybe?) it would make sense for the information to be deployed now, but clearly marked as for the development version only. But let's move this conversation over to the website repo.
