### PR TITLE
Perform a comprehensive set of thermodynamic consistency tests for all thermo models

### LINKED ISSUE #114: Improve testing of thermodynamic consistency
**Abstract**

Rather than ad hoc testing that `ThermoPhase` objects satisfy basic thermodynamic relations, consolidating all of these tests into a single test suite that operates over all thermo models would automatically provide comprehensive coverage and allow us to remove a number of other isolated tests.

**Motivation**

Cantera `ThermoPhase` objects calculate a large number of different quantities, some of which can be computed from other available quantities but which in practice are calculated directly for the sake of computational efficiency. While the test suite contains some tests addressing such identities, a full set of tests is not done for every thermo model.

The lack of these tests has repeatedly resulted in implementation errors (e.g. Cantera/cantera#998 and Cantera/cantera#1080).

Consolidating such testing would all but eliminate the need for a good portion of some model-specific test suites, e.g. [BinarySolutionTabulatedThermo_Test.cpp](https://github.com/Cantera/cantera/blob/main/test/thermo/BinarySolutionTabulatedThermo_Test.cpp), [MaskellSolidSolnPhase_Test.cpp](https://github.com/Cantera/cantera/blob/main/test/thermo/MaskellSolidSolnPhase_Test.cpp), [PengRobinson_Test.cpp](https://github.com/Cantera/cantera/blob/main/test/thermo/PengRobinson_Test.cpp), etc.). It would also provide a quick starting point for testing new thermo model implementations.

**Possible Solutions**

Add a new GTest test class which includes specific tests for various identities. The main ones that come to mind are:
* dot product of partial molar properties and mole fractions equals the mixture properties with
  * `getPartialMolarEnthalpies` and `enthalpy_mole`
  * `getPartialMolarEntropies` and `entropy_mole`
  * `getPartialMolarIntEnergies` and `intEnergy_mole`
  * `getChemPotentials` and `gibbs_mole`
  * `getPartialMolarCp` and `cp_mole`
  * `getPartialMolarVolumes` and `molarVolume`
* Thermodynamic relations at the current state, for both the mixture properties and the partial molar properties:
  * h = u + P*v
  * g = h - T*s
* Thermodynamic derivatives that can be compared to finite difference calculations
* cp = dh/dT at constant P,N_i
* cv = du/dT at constant V,N_i
* `isothermalCompressibility` = -1/v * dv/dP at constant T,N_i
* `thermalExpansionCoeff` = 1/v * dv/dT at constant P,N_i
* Relationships among activities / activity coefficients
* Relationships among the standard / reference / non-dimensionalized properties

The test would then be parameterized to use different input files and mixture states. We would also want a way to disable specific tests for certain models, for example those that don't implement specific methods.

We could also use this structure for doing regression tests on known/assumed good output values for different models, where the test values were stored in a YAML file. This file could look something like:
```yaml
- input-file: whatever.yaml # group by phase definitions
  phase-name: PR_CO2
  - state: {T: 330, P: 100 bar, X: {CO2: 0.9, H2O: 0.1} # loop over different states
    - enthalpy_mass: 1.234e5 # values to check for this state
    - partial_molar_entropies: [1.2, 3.4, ...] # array over all species
    - ... # additional properties to check
  - state: # more states where some properties have values to check
- input-file: # Next input file / phase name
  ...
```

**References**

* Cantera/cantera#998 
* Cantera/cantera#1080

### PR DESCRIPTION
**Pull request by speth**
**Changes proposed in this pull request**

- Introduce a uniform set of thermodynamic consistency tests that can be performed for all thermo models with a minimal amount of code duplication, totaling nearly 2000 distinct unit tests.
- Provide options for skipping certain tests for specific thermo models when there are known failures
- Specific tests are skipped automatically if a method raises a `NotImplementedError`
- Bump the version of Googletest used, which also bumps the minimum version of Visual Studio to 2017 (though the oldest version we can test on is 2019, due to a SCons bug).
- Remove a number of now-redundant ad hoc tests of thermodynamic consistency

I've already uncovered several bugs using these tests, and have created issues for the ones that aren't being resolved as part of this PR (all of which tag this PR).

**If applicable, fill in the issue number this pull request is fixing**

Resolves Cantera/enhancements#114

**If applicable, provide an example illustrating new features this pull request is introducing**

All of the configuration for a set of consistency tests is specified in a YAML file, `consistency-tests.yaml`:
```yaml
binary-solution-tabulated:
  setup:
    file: thermo-models.yaml
    phase: graphite-anode
    known-failures:
      g_eq_h_minus_Ts: Inconsistent results when P != 1 atm (states 2 and 3)
      g_eq_sum_gk_Xk: Inconsistent result when P != 1 atm (states 2 and 3)
  states:
  - {T: 300, P: 1 atm, X: {"Li[anode]": 0.3, "V[anode]": 0.7}}
  - {T: 320, P: 1 atm, X: {"Li[anode]": 0.3, "V[anode]": 0.7}}
  - {T: 300, P: 10 atm, X: {"Li[anode]": 0.6, "V[anode]": 0.4}}
  - {T: 300, P: 10 atm, X: {"Li[anode]": 0.0, "V[anode]": 1.0}}
```

And there is just a short block of code to create the parameterized test suite:
```c++
INSTANTIATE_TEST_SUITE_P(BinarySolutionTabulated, TestConsistency,
    testing::Combine(
        testing::Values(getSetup("binary-solution-tabulated")),
        testing::ValuesIn(getStates("binary-solution-tabulated")))
);
```

Which runs a set of different tests for each of the specified state vectors. Failing tests show the information about the particular case that is failing, e.g.:
```
[ RUN      ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/0
[       OK ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/0 (0 ms)
[ RUN      ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/1
[       OK ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/1 (0 ms)
[ RUN      ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/2
[       OK ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/2 (0 ms)
[ RUN      ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/3
test/thermo/consistency.cpp:118: Failure
The difference between phase->enthalpy_mole() and phase->mean_X(hk) is 7.232221142950948, which exceeds atol, where
phase->enthalpy_mole() evaluates to 13068.183201924798,
phase->mean_X(hk) evaluates to 13060.950980781847, and
atol evaluates to 1.0000000000000001e-05.
[  FAILED  ] BinarySolutionTabulated/TestConsistency.h_eq_sum_hk_Xk/3, where GetParam() = (file: thermo-models.yaml,
phase: graphite-anode, state: {T: 300, P: 10 atm, X: {Li[anode]: 0.0, V[anode]: 1.0}}) (0 ms)
```

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

File: test/thermo/consistency.cpp [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+{
+    double h1 = phase->enthalpy_mole();
+    double cp1 = phase->cp_mole();
+    double T1 = phase->temperature();
+    double dT = 1e-5 * phase->temperature();
+    phase->setState_TP(T1 + dT, phase->pressure());
+    double h2 = phase->enthalpy_mole();
+    double cp2 = phase->cp_mole();
+    double cp_mid = 0.5 * (cp1 + cp2);
+    double cp_fd = (h2 - h1)/dT;
```
Comment (ischoegl) [inline test/thermo/consistency.cpp]:
```suggestion
    double cp_fd = (h2 - h1) / dT;
```

File: test/thermo/consistency.cpp [hunk 2]
```diff
@@ -0,0 +1,244 @@
...
+    double dT = 1e-5 * phase->temperature();
+    if (phase->isCompressible()) {
+        phase->setState_TR(T1 + dT, phase->density());
+    } else {
+        phase->setTemperature(T1 + dT);
+    }
+    double u2 = phase->intEnergy_mole();
+    double cv2 = phase->cv_mole();
+    double cv_mid = 0.5 * (cv1 + cv2);
+    double cv_fd = (u2 - u1)/dT;
```
Comment (ischoegl) [inline test/thermo/consistency.cpp]:
```suggestion
    double cv_fd = (u2 - u1) / dT;
```

File: test/thermo/consistency.cpp [hunk 3]
```diff
@@ -0,0 +1,244 @@
...
+    if (m.hasKey("file")) {
+        s << fmt::format("file: {}, phase: {}",
+                         m["file"].asString(), m.getString("phase", "<default>"));
+    } else {
+        s << "\n" << m.toYamlString();
+    }
+    return s;
+}
+
+class TestConsistency : public testing::TestWithParam<std::tuple<AnyMap, AnyMap>>
```
Comment (ischoegl) [inline test/thermo/consistency.cpp:60]: Some minimal comments would be good to have as a documentation, especially as this test is assuming YAML input that is formatted a very specific way. While it's not extremely difficult to understand, it does take more time to read the code.

**Review by ischoegl — CHANGES_REQUESTED** [review]
@speth ... this looks great. The only thing that I believe is needed are some comments documenting how this test works - the code is readable, but it may be daunting for anyone not sufficiently familiar with `AnyMap` and testing.

As a comment, I am also wondering whether google tests mind splitting things into `*.h` and `*.cpp`, as the actual tests only start on line 184 of `consistency.cpp`. If not, then some comments indicating of what users should add where would be good to have.

File: test/thermo/consistency.cpp (hunk 3 above)
Comment (speth) [reply test/thermo/consistency.cpp:60]: This isn't marked "ready for review" for a reason. Obviously this test setup warrants some documentation.

**Comment by ischoegl** [comment]
About googletest: they now follow a [Abseil live at head](https://github.com/google/googletest#live-at-head) philosophy that won’t patch issues and recommends using the most recent commit. I am wondering whether this has something to do with the failures here?

**Comment by speth** [comment]
I don't think the idea of "[Abseil live at head](https://github.com/google/googletest#live-at-head)" is that they won't patch issues, it's that they (mostly) won't backport patches to the previous version or make a bug fix release, and that if you want a version that has all the latest bug fixes, you should just run the latest commit to the `main` branch.

The current error is because MSVC++ 14.1 (Visual Studio 2017) doesn't seem to be available on the Github Actions builders -- only 14.0, 14.2, and 14.3, depending on whether it's the Windows 2019 or Windows 2022 builder.

**Comment by bryanwweber** [comment]
@speth Is that the [known problem](https://github.com/SCons/scons/issues/3664) with SCons rearing its head again?

**Comment by ischoegl** [comment]
@bryanwweber ... good point, ~although~ the failure on my windows box (which has all MSVC versions installed for VS2022) looks different - ~it fails much earlier~ *Edit; I configured for less output, so it is the same ... I am just compiling `main`*:
```
(cantera-dev) PS C:\Users\ischo\GitHub\cantera> scons build msvc_version=14.1
scons: Reading SConscript files ...
INFO: SCons 4.3.0 is using the following Python interpreter:
C:\Users\ischo\miniconda3\envs\cantera-dev\python.exe (Python 3.10)
Compiling with MSVC 14.1
Compiling for architecture: amd64
Compiling using the following toolchain(s): ['default']

scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: ['14.3', '14.0']
File "C:\Users\ischo\GitHub\cantera\SConstruct", line 727, in <module>

scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: ['14.3', '14.0']
File "C:\Users\ischo\GitHub\cantera\SConstruct", line 727, in <module>
INFO: Building Cantera from git commit '3d5de8222'
INFO: Configuration variables read from 'cantera.conf' and command line:
    msvc_version = '14.1'

INFO: Adding conda include and library paths: C:\Users\ischo\miniconda3\envs\cantera-dev
Checking for C++ header file cmath... no
ERROR: The C++ compiler is not correctly configured (incomplete include paths).
See 'config.log' for details.
```
Locally, I can only use 14.0 (oldest) or 14.3 (newest), with none of the others working. Fwiw, my SCons version is 4.3.0.

**Comment by ischoegl** [comment]
@bryanwweber / @speth ... hold on. It *is* the same issue :tada:

**Comment by bryanwweber** [comment]
How much overlap is there between the phases you're identifying here and the list of undocumented and interested phases in the issue that I can't find because I'm on my phone? Are there any phases that we can remove?

File: test/thermo/consistency.cpp [hunk 4]
```diff
@@ -0,0 +1,691 @@
+#include "gtest/gtest.h"
```
Comment (ischoegl) [inline test/thermo/consistency.cpp:1]: I think it would be good to add a header with a short description and a note indicating that tests are documented in `test/data/consistency-cases.yaml` (also, that relevant test loaders start below line 521).

It could also be argued that the yaml file isn't cantera input data, but data that belongs to this googletest, and move the YAML into `test/thermo`.

**Review by ischoegl — DISMISSED** [review]
@speth ... as indicated earlier, this looks great. I only have one minor suggestion.

File: test/thermo/consistency.cpp (hunk 4 above)
Comment (speth) [reply test/thermo/consistency.cpp:1]: I did hesitate about putting the YAML fiile in `test/data`. The difficulty with putting it in `test/thermo` is that isn't on the data path when the test runs (the working directory is `build/test/thermo`), and you'd have to specify the input file using a somewhat fragile relative path.

Comment (ischoegl) [reply test/thermo/consistency.cpp:1]: I think it’s fine leaving it where it is, but this makes the comment in the header more important.

**Review by bryanwweber — DISMISSED** [review]
LGTM! Thanks @speth, this is a big lift that will have a big long term benefit I think

File: test/thermo/consistency.cpp (hunk 4 above)
Comment (ischoegl) [reply test/thermo/consistency.cpp:1]: On second thought ... is there a simple way to have SCons copy YAML over from `test/thermo` to `build/test/thermo`? I think that would be the preferred solution. `test/data` (still) is a large folder where things aren't easily found.

Comment (speth) [reply test/thermo/consistency.cpp:1]: I'm of course fine with adding an explanatory comment to this file, but I'd rather not have to introduce an extra complication in `test/SConscript` that's really only used for this one case. Also, the more magic that we implement in `SCons`, the harder it is to reliably run tests outside of SCons, which is something that is occasionally necessary, for instance when you want to run the tests in `gdb`.

Comment (ischoegl) [reply test/thermo/consistency.cpp:1]: Sounds good - it's a really minor point, and not worth the effort if it complicates things.

Comment (ischoegl) [reply test/thermo/consistency.cpp:1]: Thanks!

**Review by ischoegl — APPROVED** [review]
