### PR TITLE
Fix member groupings in doxygen

### LINKED ISSUE #1275: Doxygen member groupings formatted incorrectly
**Problem description**

Among other instances, the following documentation
https://github.com/Cantera/cantera/blob/2bc02637b1d6df0fb4203b70c4efafe14e0fb9fc/include/cantera/kinetics/Kinetics.h#L1190-L1208
does not produce the expected output in the [doxygen documentation](https://cantera.org/documentation/docs-2.6/doxygen/html/d4/dc4/classCantera_1_1Kinetics.html#a562bd1bb719af977b3eb0c35ea482d92). 

**Behavior**

Presumbably, the `* @{ ` starts a new section that includes multiple methods (ending with the next `//! @}`). Instead, the section description is merged with the first method listed.

**System information**

- Cantera version: Cantera 2.6
- OS: N/A (online documentation)

### PR DESCRIPTION
**Pull request by ischoegl**
**Changes proposed in this pull request**

- Update formatting of doxygen member groupings
- Update formatting of doxygen module groupings

Per [#1275](https://github.com/Cantera/cantera/issues/1275#issuecomment-1118962304), there are two working  formatting variants of member grouping commonly found (while others don't work and don't produce the expected output). This PR consistently applies the following
```C++
\\! @name GroupName
\\! description of the grouping
\\! @{
[...]
\\! @}
```

**If applicable, fill in the issue number this pull request is fixing**

Closes #1275

**If applicable, provide an example illustrating new features this pull request is introducing**

**Checklist**

- [x] The pull request includes a clear description of this code change
- [x] Commit messages have short titles and reference relevant issues
- [x] Build passes (`scons build` & `scons test`) and unit tests address code coverage
- [x] Style & formatting of contributed code follows [contributing guidelines](https://github.com/Cantera/cantera/blob/main/CONTRIBUTING.md)
- [x] The pull request is ready for review

### CODE REVIEW

File: include/cantera/thermo/DebyeHuckel.h [hunk 1]
```diff
@@ -33,7 +33,7 @@ namespace Cantera
 #define DHFORM_PITZER_BETAIJ 4
 //! @}
 /*!
- *  @name  Acceptable ways to calculate the value of A_Debye
+ * @name  Acceptable ways to calculate the value of A_Debye
```
Comment (speth) [inline include/cantera/thermo/DebyeHuckel.h]: Why isn't this one being converted to a `//!` comment?

File: include/cantera/thermo/MargulesVPSSTP.h [hunk 2]
```diff
@@ -341,12 +338,12 @@ class MargulesVPSSTP : public GibbsExcessVPSSTP
...
-    ///     constructing the phase and setting its parameters from a
-    ///     specification in an input file. They are not normally used in
-    ///     application programs. To see how they are used, see importPhase()
-    /// @{
+    //! @}
+    //! @name Initialization The following methods are used in the process of
+    //!     constructing the phase and setting its parameters from a
+    //!     specification in an input file. They are not normally used in
+    //!     application programs. To see how they are used, see importPhase()
+    //! @{
```
Comment (speth) [inline include/cantera/thermo/MargulesVPSSTP.h]: While you're at it, you could fix the formatting of this heading -- presumably, only `Initialization` is meant to be the heading, rather than `Initialization The following methods are used in the process of`, which is what gets put in the HTML docs.

File: include/cantera/thermo/MixtureFugacityTP.h [hunk 3]
```diff
@@ -145,14 +145,11 @@ class MixtureFugacityTP : public ThermoPhase
...
-     * Within MixtureFugacityTP, these properties are calculated via a common
-     * routine, _updateStandardStateThermo(), which must be overloaded in
-     * inherited objects. The values are cached within this object, and are not
-     * recalculated unless the temperature or pressure changes.
-     */
+    //! @name  Properties of the Standard State of the Species in the Solution
+    //! Within MixtureFugacityTP, these properties are calculated via a common
+    //! routine, _updateStandardStateThermo(), which must be overloaded in
+    //! inherited objects. The values are cached within this object, and are not
+    //! recalculated unless the temperature or pressure changes.
```
Comment (speth) [inline include/cantera/thermo/MixtureFugacityTP.h]: At least in some of the cases like this, I think the blank comment line between the heading and the extended description helped with legibility.

File: include/cantera/thermo/PDSS.h [hunk 4]
```diff
@@ -158,10 +158,10 @@ class PDSS
     PDSS& operator=(const PDSS& b) = delete;
     virtual ~PDSS() {}
 
-     //! @}
-     //! @name Molar Thermodynamic Properties of the Species Standard State in
-     //!     the Solution
-     //! @{
+    //! @}
+    //! @name Molar Thermodynamic Properties of the Species Standard State in
+    //!     the Solution
```
Comment (speth) [inline include/cantera/thermo/PDSS.h]: This gets formatted with `the Solution` being interpreted as the extended description rather than part of the heading. In this case, I think the easiest thing to do is just drop the excessively verbose "in the Solution" suffix.

**Review by speth — CHANGES_REQUESTED** [review]
Thanks for working through this, @ischoegl. I know this kind of comment reformatting can be a bit tedious. I had only a couple spots where I think there were some additional things worth cleaning up.

File: include/cantera/thermo/DebyeHuckel.h (hunk 1 above)
Comment (ischoegl) [reply include/cantera/thermo/DebyeHuckel.h]: This is a module grouping, which I didn't touch yet (I focused on member groupings). I can though - let me know ...

Comment (speth) [reply include/cantera/thermo/DebyeHuckel.h]: Ah, I see. I only commented because this line was in the diff.

File: include/cantera/thermo/MixtureFugacityTP.h (hunk 3 above)
Comment (ischoegl) [reply include/cantera/thermo/MixtureFugacityTP.h]: I added an empty line in all cases.

File: include/cantera/thermo/PDSS.h (hunk 4 above)
Comment (ischoegl) [reply include/cantera/thermo/PDSS.h]: I shortened this (and corresponding instances)

**Comment by ischoegl** [comment]
@speth ... done. It was tedious, but searching for `@name` in VSCode is actually not too bad.

**Comment by ischoegl** [comment]
Ended up taking care of module groupings also, so every grouping is now formatted consistently

**Review by speth — APPROVED** [review]
Thanks, @ischoegl. Hopefully, having the existing style for these be consistent will encourage consistent usage in the future as well.
